### ISSUE TITLE
Document behaviour when environment variable is already set on the machine

### ISSUE THREAD

**Issue by silhouettes** [motdotla/dotenv#102]
My team had multiple issues between environments this week that, after much confusion, boiled down to environment variables not being set by dotenv because they were already set to different values on certain machines.

Of course we were being silly and this little detail of dotenv's behavior flew over our heads, but I think it would be extremely helpful to document this behavior as it is not mentioned anywhere and the (possibly erroneous) temptation is to assume that the environment of the application is whatever is in the .env file.

Also, maybe a boolean flag to specify which thing 'wins' would be very helpful, although not essential!

**Comment by geof90** [comment]
:+1:

**Comment by maxbeatty** [comment]
Sorry for the trouble and confusion! [Here's the implementation if you're still curious](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L33). We should definitely document this.

I'm waiting for feedback on #101 and could include it there. Even if that doesn't get accepted, a PR with ideas on what and how to explain the behavior would be helpful.

**Comment by silhouettes** [comment]
Okay, no worries and thanks! I'll submit a quick PR with an update on the FAQ section, and you can feel free to modify it as desired.
