### ISSUE TITLE
You can now also send configuration variables to vanilla node

### ISSUE THREAD

**Issue by pmoelgaard** [motdotla/dotenv#103]

**Comment by pmoelgaard** [comment]
in the documentation it says that its only iojs1.6.+, however you can with the later versions of Node... anyways, thanks for the good stuff !

**Comment by maxbeatty** [comment]
"iojs-v1.6.0 or later" includes node v4 which is the only major version that supports preloading and thus command line arguments for configuration. Will remove "iojs" references once v4 becomes more mainstream.

**Comment by pmoelgaard** [comment]
I'm using Node 4.2.1, and haven't done anything special to get a 4+... anyways, you know what you are doing, so no worries, just thought I would leave a comment about it...

I'm grateful for your work and sharing it, so thank you again for the good stuff !
