### ISSUE TITLE
Add load.js script for a cleaner invocation style in ES2015

### ISSUE THREAD

**Issue by callumlocke** [motdotla/dotenv#106]
Currently it's possible to load env vars with a single line using CommonJS:

```js
require('dotenv').load();
```

But using ES2015 imports, it has to be two lines:

```js
import dotenv from 'dotenv';
dotenv.load();
```

My suggestion is to add a script in the root of the project, `load.js`, which would do `require('.').load();`. This would make it possible to import and load in one neat statement:

```js
import 'dotenv/load';
```

**Comment by jcblw** [comment]
I know we have `dotenv/config` I think that will do what you are look for.

```
node -e "require('dotenv/config'); console.log(process.env.TEST);"
```

**Comment by maxbeatty** [comment]
If you are using a newer version of node, [preloading](https://github.com/motdotla/dotenv#preload) can eliminate dotenv from your source ([example](https://github.com/motdotla/dotenv/tree/master/examples/es6-preload))

**Comment by callumlocke** [comment]
awesome, missed this, thanks!
