### ISSUE TITLE
Option to overwrite env variables

### ISSUE THREAD

**Issue by tmarciszewski** [motdotla/dotenv#107]
Hi,

I'm wondering why optional overwriting of existing env variables is not supported at the moment. Are there any problems with that feature?

It was implemented here: https://github.com/jordansexton/dotenv

My use case is as follows:

I want to set env variables in dev environment. I'm using gulp to restart project if some files change. In my case environment variables should change if I change .env file.

Should I prepare pull request with this feature?

Best Regards
Tomasz

**Comment by maxbeatty** [comment]
Can you provide a simplified example of your setup? If your gulp restart isn't restarting the process, then `process.env` will already be populated and [not reassigned](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L33).
