### ISSUE TITLE
Some variables are not recognized

### ISSUE THREAD

**Issue by mgol** [motdotla/dotenv#108]
Having the `.env` file (dev data, don't worry):
```sh
COOKIE_SECRET='$c|{u;%Z9|l8{=;ek"D1AhO?u}z,U*LWF<hp4]q_(!ClgH<4NKQ8BR`e:14PPKn%'
```
and using:
```js
require('dotenv').load();
```
doesn't work, the variable is set, but to an empty string. But once I set it to be a simple string like:
```sh
COOKIE_SECRET=bbb
```
it works fine. `dotenv@1.2.0`.

**Comment by maxbeatty** [comment]
My guess is that your `COOKIE_SECRET` starting with `$` is being identified as a variable to expand which is something I'm proposing we remove in #101. If you remove the quotes and begin with a `\`, does that work? (Basically escaping the "variable")

**Comment by Yvem** [comment]
@maxbeatty Same problem, your solution works, thanks ! this should be outlined in the doc.

**Comment by nickdarnell** [comment]
Oh awesome, i hit this issue too.  Came here to report it :+1:

**Comment by maxbeatty** [comment]
New release is coming shortly that no longer supports variable expansion so you won't have to dance around how you declare variables
