### ISSUE TITLE
calling config() actually loads() ??

### ISSUE THREAD

**Issue by Yvem** [motdotla/dotenv#109]
I'm using dotenv as a sub-library. I want to configure it THEN load env variables at a later time (or maybe not calling it at all).

```javascript
var dotenv = require('dotenv');
dotenv.config({ silent: true });

...later, maybe :
dotenv.load()
```
However, calling `config()` actually loads the .env file immediately. Looking at the `dotenv` code, I see :

```javascript
module.exports.load = module.exports.config
```

This is completely unexpected and disregard the principle of last surprise.

Could the API be fixed ?

**Comment by Yvem** [comment]
Looking at the doc, I see this is documented. However, I maintain this is completely counter-intuitive.

I suggest removing `config()` completely.

**Comment by jcblw** [comment]
What is the reasoning for wanting to defer the loading of variables into your process? Why not just call `dotenv.config` when you want to load the variables in?

**Comment by motdotla** [comment]
@Yvem yeah, I'd recommend @jcblw's approach.

Keep in mind:

> Note: config and load are synonyms. You can pass options to either.

**Comment by Yvem** [comment]
Whatever I tried to do, that's crazy to have a `config()` func which is a synonym for `load()`. At last ditch config().
