### ISSUE TITLE
Load .envrc files like direnv.

### ISSUE THREAD

**Issue by adjohnson916** [motdotla/dotenv#113]
Either in addition to or as a fallback in case of missing `.env` file, it may be nice to also check for `.envrc` file, e.g. from [direnv](https://github.com/direnv/direnv), and gracefully attempt to parse & load it.

Probably relies on an implementation of #112.

**Comment by maxbeatty** [comment]
I'd suggest using the [custom path option](https://github.com/motdotla/dotenv#path) if you know you're looking for `.envrc`. It's also harmless to try to attempt to load two or more files yourself.

```js
const dotenv = require('dotenv')
dotenv.config()
dotenv.config({ path: '.envrc' })
```

**Comment by adjohnson916** [comment]
Thanks @maxbeatty, I'll try that.

**Comment by wilmoore** [comment]
@adjohnson916 This should work for very specific cases where you are absolutely sure that your `.envrc` file only includes variable assignments; however, it could easily go south if your `.envrc` file includes other commands which `dotenv` does not support.

Also, I'm just curious to hear of other people's workflow...if you are already using `direnv`, why use `dotenv` locally at all? Shouldn't `direnv allow` be enough?

**Comment by adjohnson916** [comment]
@wilmoore I figured. Why? Might not be running the app from the current working directory, or from a different user account e.g. a system account that's not running with a shell and/or doesn't have direnv configured . Might want to use `dotenv` on a server to provide environment-specific configuration to the deployed application.

**Comment by wilmoore** [comment]
Thanks @adjohnson916 -- good to know.
