### ISSUE TITLE
custom path doesn't work

### ISSUE THREAD

**Issue by kamoljan** [motdotla/dotenv#116]
Hi guys

I am trying to move my `.env.production` file into `config` dir.
However, it doens't work.

```
//var dotenv = require('dotenv'); // it works
var dotenv = require('dotenv').config({path: './config/.env.production'}); // doesn't work
dotenv.load();
```

`config` dir the same level as `app.js`

**Comment by kamoljan** [comment]
sorry, kind of missed it in the doc.
```
require('dotenv').config({path: './config/.env.production'});
```
instead of 
```
var dotenv = require('dotenv').config({path: './config/.env.production'}); // doesn't work
```

**Comment by maxbeatty** [comment]
Sorry for the confusion. Trying to make it clearer in #101 that `config` is an alias to `load`

**Comment by kamoljan** [comment]
@maxbeatty awesome!

**Comment by justinmarsan** [comment]
I'm sorry but I don't get it...

I'm unsure where I should require, or set it to `const dotenv`... Could someone please share a working example, I understand that `config.()` and `const dotenv = require` can't be on the same line but I don't understand what it should be if not that... ALso I couldn't find anything regarding `load`...

Thanks in advance.

**Comment by maxbeatty** [comment]
You can call config many times but process.env will not be overwritten

**Comment by justinmarsan** [comment]
Arf, indeed, I don't know what I'd had done, I thought it worked but clearly it doesn't...

Then I guess I still don't get it, I have the code I've written above, I do get what I've defined in my root .env file, but I'm not getting the variables I've written in the one I'm explicitly calling with .config()...

What did I miss ?

**Comment by maxbeatty** [comment]
Here's how to debug and inspect what dotenv is doing:

```js
const dotenv = require("dotenv")

// enable debugging
const { parsed, error } = dotenv.config({ debug: true })

// was there an error?
console.error(error)

// what was parsed?
console.log(parsed)

// compare to process.env
console.dir(process.env)
```

**Comment by SiMoG97** [comment]
I've faced the same issue some weeks ago . . . 
and the simplest solution i came up with is this 


```js
//  importing join from path module 
const {join} = require('path')

//  join : for gluing two separate paths 
// __dirname : for current file path
// __dirname.replace(/\\/g, "/") : replacing backslashes with forward slashes

require('dotenv').config({ path :  join(__dirname.replace(/\\/g, "/"),"/../envdir/dev.env")}) 
```
i guess this isn't the prefect answer but it works !

**Comment by camgrafiman** [comment]
> 
> 
> I've faced the same issue some weeks ago . . .
> and the simplest solution i came up with is this
> 
> ```js
> //  importing resolve from path module 
> const {resolve} = require('path')
> 
> require('dotenv').config({path: resolve(__dirname,"../../config/dev.env")})
> ```
> 
> i guess this isn't the prefect answer but it works !

@SiMoG97 worked for me! thanks!!

**Comment by abdulghani** [comment]
I'm sorry, neither of the solution works for me

```javascript
// ./src/index.js
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: "../.env.dev" });

// tried this also don't work
dotenv.config({ path: path.resolve(__dirname, "../.env.dev") });

```

```javascript
// ./.env.dev
PORT=3000
# some other config
```

**Comment by hqMoura** [comment]
Just a simple reminder of what have worked for me: You dont need to put the relative path inside `path `string. Just try **maxbeatty** code. For whatever dir you have on the root folder.

```
const dotenv = require("dotenv");
dotenv.config({ path: "./config/.env" });
```

**Comment by MrSergeyB** [comment]
> ```js
> const {resolve} = require('path')
> ```

Thanks a lot.  It works

**Comment by PurpleUltralisk** [comment]
> I've faced the same issue some weeks ago . . .
> and the simplest solution i came up with is this
> 
> ```js
> //  importing resolve from path module 
> const {resolve} = require('path')
> 
> require('dotenv').config({path: resolve(__dirname,"../../config/dev.env")})
> ```
> 
> i guess this isn't the prefect answer but it works !

This helped me in finding the .env file 1 level up.
Thanks!
