### ISSUE TITLE
CLI helper to generate .env.example from .env file

### ISSUE THREAD

**Issue by jgoux** [motdotla/dotenv#119]
Hello,
would it be possible to include a CLI utility to generate a `.env.example` file with empty values from a `.env` file present in the folder in which the command is executed ?

Basically, given this `.env` file : 
```
FOO=BAR
BAZ=YOLO
```

If we type for example `dotenv --example`

Then the following `.env.example` file is generated : 
```
FOO=
BAZ=
```

**Comment by wilmoore** [comment]
I'm not sure it worth building and supporting an entire tool for what amounts too:

```
sed 's/=.*/=/' .env > .env.example
```

**Comment by maxbeatty** [comment]
Thanks for the bash-foo, @wilmoore! In total agreement, this is something better left to bash or even using the already existing `parse` method.

```js
const fs = require('fs')
const dotenv = require('dotenv')

console.dir(Object.keys(dotenv.parse(fs.readFileSync('.env')))
```

**Comment by maxbeatty** [comment]
#120 will return an object with your `.env` vars as keys so this will be simpler

```js
console.dir(Object.keys(require('dotenv').config()))
```

**Comment by marat-dimaev** [comment]
1. add this code in /routes/console.php

Artisan::command('env:example', function () {
    $lines = file(base_path().'/.env');
    $content = '';
    foreach ($lines as $line_num => $line) {
        if(preg_match("/#.*env_hide/", $line)) {
            $line = preg_replace("/^([^=]+)=([^#]*[^\s])(\s*)#([^#]*)/", "$1=*****$3#$4", $line);
        }
        $content .= $line;
    }
    file_put_contents(base_path().'/.env.example', $content);
})->describe('Auto-generate .env.example');

2. add #env_hide in .env
...
DB_CONNECTION=mysql
DB_HOST=127.0.0.1 #env_hide
DB_PORT=3306
DB_DATABASE=db_name #env_hide
DB_USERNAME=root #env_hide
DB_PASSWORD= #env_hide
...
3. run this command 
php artisan env:example

**Comment by stavalfi** [comment]
why is `.env.example` is needed?! and why there is no word about it in the docs?

I'm struggeling to find this out.

thanks guys

**Comment by ahmedu007** [comment]
It would be for this:
https://github.com/rolodato/dotenv-safe

**Comment by rubiin** [comment]
for whoever is looking for such, here is a cli https://github.com/rubiin/sample-env

**Comment by Sleepful** [comment]
following wilmoore comment, just add it to a makefile, and if you feel inclined, to a git precommit hook

**Comment by motdotla** [comment]
you can do this using dotenvx these days:

1. `dotenvx ext genexample` - https://dotenvx.com/docs/features/genexample
2. `dotenvx ext precommit --install` - https://dotenvx.com/docs/advanced/precommit-install
