### ISSUE TITLE
CLI doesn't appear to load env

### ISSUE THREAD

**Issue by marr** [motdotla/dotenv#121]
I have a simple example, my .env file includes: `DEBUG=app:test`.
I run a test script thusly: `node -r babel-register -r dotenv/config bin/test.js`
The contents of the script are:
```
import _debug from 'debug'
const debug = _debug('app:test')
debug(process.env.DEBUG)
```
Nothing is output from the CLI.
However, if I run the script with `DEBUG=* node -r babel-register -r dotenv/config bin/test.js` I see the output:`app:test * +0ms`

**Comment by maxbeatty** [comment]
This smells like #114 where babel is compiling the source which messes with load order. I verified [the es6-preload example](https://github.com/motdotla/dotenv/tree/master/examples/es6-preload) still works. You might want to `console.log(process.env.DEBUG)` to see if it's populated. If it is, `debug` is getting called too early in the babel compiling.

**Comment by marr** [comment]
Ok, the console.log does output the correct value. However I initially thought there was a problem because I ran `node -r dotenv/config` and then ran `process.env.DEBUG` in the repl. `undefined` is output.

I guess thats just an oddity with how the repl runs?

**Comment by hyperh** [comment]
I'm having the same issue. I do get the correct output when I do `console.log(process.env.DEBUG)`, but `debug` still not working for me.
