### ISSUE TITLE
Deployment to Heroku fails if dotenv is required in production

### ISSUE THREAD

**Issue by guilsa** [motdotla/dotenv#126]
Documentation should be instructing users to require dotenv only in development. I just ran through this yesterday with the Sinatra version of dotenv as well and the same as happened in Express. Based on the change below, a simple Express scaffold will or won't run on Heroku.

`if (app.get('env') == 'development'){
require('dotenv').config();
}`

**Comment by jcblw** [comment]
@guilsa it should work no matter what environment that you use it in, maybe this is something application specific that is breaking when an incorrect env is loaded? Do you have a, shareable, stack trace of the crash that dotenv is creating?

We do have mention inside of our [README](https://github.com/motdotla/dotenv#should-i-commit-my-env-file) that the `.env` file should not be committed.

> No. We strongly recommend against committing your .env file to version control.

as well a deter people from using it in multiple environments

> No. We strongly recommend against having a "main" .env file and an "environment" .env file like .env.test. Your config should vary between deploys, and you should not be sharing values between environments.

I would say it should run fine if ran in the other environments, and the recommending the usage of `dotenv` to be something like...

```javascript
if (process.env.NODE_ENV !== 'production') require('dotenv').config()
```

would be kinda weird to put in our README.

**Comment by motdotla** [comment]
Yeah, like @jcblw said, this is likely because you are committing your `.env` to version control @guilsa. 

Going to go ahead and close this with that assumption. If that is not the case let us know and we'll dive deeper.

**Comment by guilsa** [comment]
I wasn't committing .env to version control. When I have some time will
mock up a test app and try to reproduce. Thanks yall.

**Comment by migueloller** [comment]
@guilsa, the reason it fails is because `.env` doesn't exist and thus when `dotenv` tries to read it there is an error.

**Comment by SOSANA** [comment]
@motdotla @jcblw so if I get this right, this should only be used for development? I thought the purpose was to apply env variables for production.

The project I just kicked off today I was going to use this, its a private repo that will have continuous integration. I was going to include the .env so it sets my production env.

So should I not use this for production? just use this for development?

**Comment by maxbeatty** [comment]
We *log* an error if anything goes wrong reading the file, parsing it, or assigning to `process.env` ([src](https://github.com/motdotla/dotenv/blob/6349be85913f72f692585ff5d802761a81c53d9d/lib/main.js#L39)). This seems to scare more people than it helps.

This has been covered many times before but it's quicker just to type it out than find all the other references.

1. `dotenv` can be used safely in any environment (development, staging, qa, production, etc.)
1. Do not commit your `.env` file to source control. Don't put any sensitive data in source control.
2. You can conditionally silence the *logged* (not thrown) error with the [silent option](https://github.com/motdotla/dotenv/blob/6349be85913f72f692585ff5d802761a81c53d9d/README.md#silent) (`require('dotenv').config({ silent: process.env.NODE_ENV === 'production' })`). This will keep your Heroku deploy logs clean (or any other PaaS like AWS Elastic Beanstalk where environment variables are populated for you)
3. We can't help you if you don't share any meaningful code

**Comment by amit-coditas** [comment]
i just stumbled on to this thread and am confused with the conflicting statements here.

**Comment by maxbeatty** [comment]
1. [We **strongly** recommend against committing your .env file to version control.](https://github.com/motdotla/dotenv#should-i-commit-my-env-file)
2. `dotenv` can be used safely in any environment (development, staging, qa, production, etc.)

**Comment by gkatsanos** [comment]
I still fail to see the usefulness of this plugin if it requires manual actions

**Comment by maxbeatty** [comment]
Please use GitHub Issues to advance this project instead of venting your own frustrations. We are very open to improving the developer experience through better documentation and other messaging.

**Comment by gkatsanos** [comment]
But, Max, you have had probably 10 to 20 identical tickets asking for the same thing. Why don't you rethink things a little? See what the CRA did with .env for example. No offense.

**Comment by migueloller** [comment]
@gkatsanos, `dotenv` is a good tool to read a `.env` file and assign those variables to `process.env`.

`process.env` will contain the current environment's env vars, so `dotenv` doesn't have to be used in those cases. What this ends up looking like is that you want to use `dotenv` in development to load your `.env` file but not in production since the environment should have the env vars you need (i.e., in `process.env`).

A way you can keep `dotenv` outside your code and still benefit from it is by using this in your `package.json` for development:

```"dev": "node -r dotenv/config ."```

If you don't want to use `dotenv`, you can always replace that line with the following:

```"dev": "env $(cat .env | grep -v ^# | xargs) node ."```

Hope this helps!

**Comment by maxbeatty** [comment]
@gkatsanos if you're referring to create-react-app, [they use this module](https://github.com/facebookincubator/create-react-app/blob/v1.0.17/packages/react-scripts/package.json#L34).

**Comment by jcblw** [comment]
@gkatsanos if you like you could make a module that builds this functionality on-top of the `dotenv` library. @maxbeatty referances `create-react-app` and [here is code they use](https://github.com/facebookincubator/create-react-app/blob/v1.0.17/packages/react-scripts/config/env.js#L25).

```javascript
var dotenvFiles = [
  `${paths.dotenv}.${NODE_ENV}.local`,
  `${paths.dotenv}.${NODE_ENV}`,
  // Don't include `.env.local` for `test` environment
  // since normally you expect tests to produce the same
  // results for everyone
  NODE_ENV !== 'test' && `${paths.dotenv}.local`,
  paths.dotenv,
].filter(Boolean);

// Load environment variables from .env* files. Suppress warnings using silent
// if this file is missing. dotenv will never modify any environment variables
// that have already been set.
// https://github.com/motdotla/dotenv
dotenvFiles.forEach(dotenvFile => {
  if (fs.existsSync(dotenvFile)) {
    require('dotenv').config({
      path: dotenvFile,
    });
  }
});
```

This module looks to provide baseline functionality that can be extended.

**Comment by gkatsanos** [comment]
I would like to use it also on production but hard-coding it would mean
that on every heroku build I would have to re-create it as files not
created automatically are not persisted (unless I'm wrong).
I'll see one of the workarounds offered but I would ideally try to find a
more convenient way of doing this. (I still don't know how I could tell
heroku what my MONGO url is or what the jwt secret is for example..)

**Comment by Candy-Tewari** [comment]
Starting process with command `node server.js`
2020-11-13T05:35:05.638637+00:00 app[web.1]: internal/modules/cjs/loader.js:834
2020-11-13T05:35:05.638648+00:00 app[web.1]: throw err;
2020-11-13T05:35:05.638649+00:00 app[web.1]: ^
2020-11-13T05:35:05.638649+00:00 app[web.1]: 
2020-11-13T05:35:05.638649+00:00 app[web.1]: Error: Cannot find module 'dotenv'
2020-11-13T05:35:05.638649+00:00 app[web.1]: Require stack:
2020-11-13T05:35:05.638650+00:00 app[web.1]: - /app/server.js

The starting of my server.js is like exactly this. The first line:
if (process.env.NODE_ENV !== 'production') {
    require('dotenv').config();
}

I set the environment variables like keys etc in the heroku environment. Also set:
NODE_ENV : production

Can anyone rectify me

**Comment by stoplion** [comment]
Having the same issue in 2020
