### ISSUE TITLE
Variables not being loaded in Mocha tests

### ISSUE THREAD

**Issue by i-aakopian** [motdotla/dotenv#127]
I'm trying to run a mocha test but all of my variables are undefined. Even when I explicitly call
```javascript
require('dotenv').config({path: path/to/.env});
```
in my test file.

Any way to get this to work properly?

**Comment by jcblw** [comment]
do you get any errors when trying to run this? maybe your path is incorrect?  Dotenv should work in  mocha tests.

**Comment by i-aakopian** [comment]
My directory structure looks like the following:
```
MyProject
  lib/
  tests/
    unit/
        MyTest.test.js
  .env

```
 
In MyTest.test.js I have
```javascript
var path = require('path');
var dotEnvPath = path.resolve('../../../');
require('dotenv').config({ path: dotEnvPath});

```

When I print dotEnvPath it gives me:  /home/i-aakopian/projects/MyProject

Still doesn't work when I specify .env explicitly

**Comment by motdotla** [comment]
@i-aakopian this is almost certainly because you are call loading dotenv after you've already required your config file. Instead your code should look something like this:

```
var path = require('path');
var dotEnvPath = path.resolve('./.env');
require('dotenv').config({ path: dotEnvPath});

var config = require('../../lib/config/config.js')
console.log(process.env.API_KEY, config)
```

Not how the config file is required after dotenv has been required and loaded.

**Comment by lmj0011** [comment]
for anyone else in this predicament.

- don't do this
`dotenv.config({path: './tests/api/'});`

- do this: specify the .env file in the path 
`dotenv.config({path: './tests/api/.env'});`

**Comment by vishnu2prasadh** [comment]
@i-aakopian 
have you got the solution? because am too experiencing the same issue. any suggestion?

**Comment by zachdini** [comment]
This is also a problem for me. It was working until last week. Now my environment variables are not loaded by the time I get to my test setup.

I load dotenv in my mocha config file:

```
--compilers=js:babel-register
--require=dotenv/config
--require=babel-polyfill
--require=./test/vendor/chai.js
```

and run the tests using `./node_modules/.bin/mocha ./test/integration --opts test/mocha.integration.opts`

This worked up until last week. Any idea why it might not work anymore?

**Comment by nikhilgoud** [comment]
In my case, the tree is roughly like this. In the config.js file, I'm setting conn URL, which is extracted from the .env file. 
─lib
│   └───api
│       └───v1
│           ├───user
│           │   ├───tests
│           │   └───user.js
              [...]
│           ├───index.js
│           ├───config.js
│           ├───mongo-conn.js
├───.env.test
├───.env
├───server.js
├───server.test.js
For testing I wanted t configure a different URL, So I did like this in test file 
```
import path from 'path';
process.env.NODE_ENV = 'test' ;
const dotEnvPath = path.resolve(`./.env${process.env.NODE_ENV === 'test' ? '.test':''}`);
import * as dotenv from 'dotenv';
dotenv.config({ path: dotEnvPath });

import config from '../../config';
console.log(process.env.MONGODB_URI, config);
```
added this in config.js file
```
import path from 'path';
const dotEnvPath = path.resolve(`./.env${process.env.NODE_ENV === 'test' ? '.test':''}`);
import * as dotenv from 'dotenv';
dotenv.config({ path: dotEnvPath });
module.exports = {
    MONGODB_URI: process.env.MONGODB_URI,
    PORT: 3000   
};
```

But the config.js file is still reading from` .env` file instead of `.env.test` file? 
Am I missing any configuration.

**Comment by JimTheMan** [comment]
For me, dotenv gets loaded properly for the first run, but when I use `--watch` with mocha the env vars are undefined when the tests are rerun.

**Comment by ibrod1983** [comment]
I found a solution, that works for me. Just require the .env file, **in the test file it self**. Solves it.

I'm using Jest right now, but being that i had exactly the same problem with Mocha - i can only assume this solution would work also with the latter.

**Comment by KoffiBikor** [comment]
Please, ibrod1983 

Can you show your code with Jest for exemple because it dosen't work for me:

beforeAll(async () => {
   dotenv.config({ path: '../.env'});

   const module = await Test.createTestingModule({
      imports: [ApplicationModule],
    })
      .compile();
   app = await module.createNestApplication();
   await app.init();

  });

**Comment by pete2786** [comment]
Oh probably

**Comment by sgd2z** [comment]
> In my case, the tree is roughly like this. In the config.js file, I'm setting conn URL, which is extracted from the .env file. ─lib │ └───api │ └───v1 │ ├───user │ │ ├───tests │ │ └───user.js [...] │ ├───index.js │ ├───config.js │ ├───mongo-conn.js ├───.env.test ├───.env ├───server.js ├───server.test.js For testing I wanted t configure a different URL, So I did like this in test file
> 
> ```
> import path from 'path';
> process.env.NODE_ENV = 'test' ;
> const dotEnvPath = path.resolve(`./.env${process.env.NODE_ENV === 'test' ? '.test':''}`);
> import * as dotenv from 'dotenv';
> dotenv.config({ path: dotEnvPath });
> 
> import config from '../../config';
> console.log(process.env.MONGODB_URI, config);
> ```
> 
> added this in config.js file
> 
> ```
> import path from 'path';
> const dotEnvPath = path.resolve(`./.env${process.env.NODE_ENV === 'test' ? '.test':''}`);
> import * as dotenv from 'dotenv';
> dotenv.config({ path: dotEnvPath });
> module.exports = {
>     MONGODB_URI: process.env.MONGODB_URI,
>     PORT: 3000   
> };
> ```
> 
> But the config.js file is still reading from` .env` file instead of `.env.test` file? Am I missing any configuration.

I'm running into this exact same problem:
`require('dotenv').config({ path: path.resolve(process.cwd(), 'test/test.env') })`

It still loads the .env file and no errors.
