### ISSUE TITLE
Email address in .env file is getting stripped.

### ISSUE THREAD

**Issue by nerdybeast** [motdotla/dotenv#128]
I am trying to add my username into the .env file which happens to be an email address. Everything after the @ symbol is getting stripped off:
`USERNAME="therealnerdybeast@gmail.com"` is turning into `{ USERNAME: 'therealnerdybest' }`

I have tried (with no luck):
`USERNAME="therealnerdybeast@gmail.com"`
`USERNAME='therealnerdybeast@gmail.com'`
`USERNAME="therealnerdybeast\@gmail.com"`
`USERNAME=therealnerdybeast\@gmail.com`

If I have encased the email in quotes, it should be pulled in exactly how it is in the .env file.

Thanks ahead for looking into this.

**Comment by motdotla** [comment]
Ouch. Will take a look into this.

**Comment by jcblw** [comment]
just ran

```
node -r 'dotenv/config' -e 'console.log(process.env.EMAIL)'
```

with the .env file 

```
EMAIL=therealnerdybeast@gmail.com
```

and everything seemed to spit out fine. Can you post the version of `dotenv` being used as well as `node`.

**Comment by nerdybeast** [comment]
Well, I might deserve a slap on the wrist but I am running node version 5.6.0, dotenv version 2.0.0.

**Comment by maxbeatty** [comment]
@nerdybeast sorry, I can't reproduce locally using node v.5.6.0 and [travis-ci passed with a new test case using v5.9.1](https://travis-ci.org/motdotla/dotenv/jobs/119128563). please chime in on #131 if this is still a problem

**Comment by brian-learningpool** [comment]
Late to the party on this but I found this issue when I myself experienced something similar.  

In my case it was caused by an environment variable with that name already being set elsewhere, and it corresponding exactly to everything before the `@` symbol.

**Comment by maxbeatty** [comment]
Will you share some data to reproduce? I'd like to add a test case

**Comment by maxbeatty** [comment]
Ah, this is a classic conflict. Maybe I'll add a "debug" option to highlight these as part of Hacktoberfest
