### ISSUE TITLE
'TypeError: fs.readFileSync is not a function' when used with webpack

### ISSUE THREAD

**Issue by patoncrispy** [motdotla/dotenv#129]
I'm not sure why, but when I try to use dotenv in my app I get the above error message in my console. 
I'm importing dotenv the es6 way:

`import dotenv from 'dotenv';`
`dotenv.config();`

But for some reason, I'm getting that error. The following tickets on other packages suggest it's something to to with webpack, but I don't understand what it could be: 
https://github.com/substack/brfs/issues/36
https://github.com/pixijs/pixi.js/issues/2078

The fixes on those sites do not solve the issue I am having, either. :(

**Comment by jcblw** [comment]
I recommend against using this client-side like this, essentially what would need to happen for this to work the client is that the entire file would need to be included into the client bundle so we could parse the data. Issue is that a lot of the time `.env` is where you should put sensitive data that you do not want to keep inside your revision history, and doing this would make all the info available to anyone who can look at the source of your site.

A method I have used is injecting the values into the views of the website, if you are running a node server. Or another option is if you have a static site, write the needed variables to a file that could be bundled with webpack or browserify.

Sorry for the not so straight forward answer.

**Comment by patoncrispy** [comment]
That actually makes perfect sense. I feel silly for not thinking of that myself! Thanks for the tip! 






On Mon, Mar 14, 2016 at 11:15 AM -0700, "Jacob Lowe" <notifications@github.com> wrote:












I recommend against using this client-side like this, essentially what would need to happen for this to work the client is that the entire file would need to be included into the client bundle so we could parse the data. Issue is that a lot of the time .env is where you should put sensitive data that you do not want to keep inside your revision history, and doing this would make all the info available to anyone who can look at the source of your site.



A method I have used is injecting the values into the views of the website, if you are running a node server. Or another option is if you have a static site, write the needed variables to a file that could be bundled with webpack or browserify.



Sorry for the not so straight forward answer.

**Comment by jcblw** [comment]
:beers: closing down this issue

**Comment by heymartinadams** [comment]
Good catch, @ patoncrispy. Would never have found it on my own. Thanks.
