### ISSUE TITLE
Default environment value to check whether dotenv is loaded

### ISSUE THREAD

**Issue by posquit0** [motdotla/dotenv#132]
I think it will be nice feature if I can check whether dotenv is loaded. Then, we can integrate `require('dotenv').config();` into `config.js` file configuring an optional values which don't need to store in process environment. `config.js` file might be loaded several times during application life-cycle.

For example,

```node
# Will execute `require('dotenv').config();
process.env.DOTENV_LOADED || require('dotenv').config();
# Won't
process.env.DOTENV_LOADED || require('dotenv').config();
```

It can prevent repeated loading `dotenv`.

**Comment by ashwell** [comment]
Hey @posquit0 I think you're a little confused about how `require` works. When you run `require('dotenv')` node finds the main script file in node_modules for the dotenv package. Node then executes the script, gets the value of `module.exports` and returns the original `require` call. The next time `require('dotenv')` is called node simply looks up the previous value and returns that, **it does not re-execute the script**.

So putting `require('dotenv').config()` in a `config.js` file and doing `require('./config.js')` multiple times will only execute dotenv once (unless you are calling the `.config` function multiple times, don't do that)

Also note that dotenv uses synchronous file reading methods so `process.env` is fully populated for every line of code that executes after `dotenv.config()`.

@jcblw feel free to back me up on this

**Comment by jcblw** [comment]
@posquit0 you can do this is already without any modification to the core lib, If you were to put the `DOTENV_LOADED=true` into your `.env` file. It will set the env the first time and then based of your current logic it would not reload the env on the the next time let say you call a function with that line of code. 

If you have any more questions about how to implement feel free to ask! closing this.
