### ISSUE TITLE
Error: ENOENT: no such file or directory, open '.env'

### ISSUE THREAD

**Issue by gragra100** [motdotla/dotenv#135]
Hi,
I am working on a Ubuntu 14 Virtual Machine. If i run my `node server.js` inside the project folder that contains my .env file it's all ok! BUT if i run for example `node /home/myapp/server.js` it return this error:

> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

and then my server starts on a random port.
Can anyone help me? I need to run the server on startup so i need to add a .conf file on /etc/init with the `node /home/myapp/server.js` command.

**Comment by jcblw** [comment]
I think we are just logging out this error, your server should be running fine. If you want to get rid of the log you can pass the option of `silent: true`.

```javascript
require('dotenv').config({silent: true})
```

 Im assuming your setting your port via `.env` all you would need to do on your server is set that process variable in you upstart script or something like that 

```
export PORT=5000
```

**Comment by maxbeatty** [comment]
By default, the `.env` file is loaded from [`process.cwd()`](https://nodejs.org/docs/latest/api/process.html#process_process_cwd). When you run `node server.js`, the current working directory is `/home/myapp/` so your file is found. When your upstart script runs or you run `node /home/myapp/server.js`, the current working directory is whatever `pwd` returns so your file isn't found.

Here are two ways to work around this:

1. configure [path](https://github.com/motdotla/dotenv#path) to `/home/myapp/.env`
2. use something like [`pushd`](https://en.wikipedia.org/wiki/Pushd_and_popd) to set your directory stack in your init script (e.g. `pushd /home/myapp >& /dev/null && node server.js`)

**Comment by caggie** [comment]
`require('dotenv').config({path: __dirname + '/.env'});`

Use this and you can run `node /home/myapp/server.js`

**Comment by samson212** [comment]
`__dirname` won't work if your app isn't run directly with node, i.e. you're using `systemctl`. I had to use `process.env.HOME` instead.

**Comment by battalian** [comment]
I am getting this error when i tried to install cordova & ionic "sudo npm install -g cordova ionic", what should i do??

![image](https://user-images.githubusercontent.com/18572376/27468284-9edc5236-5806-11e7-881b-0ef35b0f6606.jpg)

**Comment by jesmarquez** [comment]
I have the file env in directory root. I get this message:

Error: ENOENT: no such file or directory, open '.env'

The value process.cwd() is correct.

Development environment: Ubuntu, Node 6.11.2, NPM 3.10.10

**Comment by mouafa** [comment]
If someone stumbles in this as I did, it's not `vue-cli` fault, somehow if you create the file via a text editor (vscode in my case) node fs module can't read it, I couldn't even do ```cat .env``` 

the solution is to use the terminal, run ```touch .env``` in your project root folder, a new .env file will be created and node fs could read it.

happy coding!

**Comment by mouafa** [comment]
The first `.env` was created with `touch .env` command, and you could see that it's using the proper icon.
The second one was created from vscode.
I don't know what's the difference, but apparently not all `.env` are a `.env` 🙈 

<img width="552" alt="screenshot 2019-01-10 at 22 41 46" src="https://user-images.githubusercontent.com/1658799/50998828-f7b1a380-1528-11e9-9ef4-6ca75c942d5b.png">

**Comment by msmfsd** [comment]
If you get this error only on Travis CI builds then this my help:
```
const dotenv = require('dotenv').config()
...
if (process.env.NODE_ENV !== 'test' && dotenv.error) throw dotenv.error
```

**Comment by ujjawalsidhpura** [comment]
> `require('dotenv').config({path: __dirname + '/.env'});`
> 
> Use this and you can run `node /home/myapp/server.js`

THIS works! Thank you

**Comment by MateusPaixao** [comment]
> `require('dotenv').config({path: __dirname + '/.env'});`
> 
> Use this and you can run `node /home/myapp/server.js`

THIS works! But I need to add a path for example file as well... Thank you
