### ISSUE TITLE
Encrypt env variables

### ISSUE THREAD

**Issue by danilodeveloper** [motdotla/dotenv#136]
Hey guys!
There is a way (or a plan) to encrypt env variables? I need something like this to encrypt AWS secret tokens, email token and etc.
I looked for about that and I think that we can do with [crypto.createCipher](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password).
What do you think about?

**Comment by maxbeatty** [comment]
dotenv is for plain key-value data. Your keys or values can be encrypted but dotenv doesn't treat them any differently (they are just strings).

You could use [AWS Key Management Service](https://aws.amazon.com/kms/) or something similar to decrypt encrypted environment variables.

```
ENCRYPTED_TOKEN=reallyLONGrandomSTRING
```

```js
require('dotenv').config()
var AWS = require('aws-sdk')
var decryptParams = {
    CiphertextBlob: new Buffer(process.env.ENCRYPTED_TOKEN, 'base64')
}

var kms = new AWS.KMS({
    apiVersion: '2014-11-01'
})

kms.decrypt(decryptParams, function (error, data) {
    if (error) {
        console.log(error)
    } else {
        console.log('decrypted token', data.Plaintext.toString('ascii'))
    }
})
```

**Comment by danilodeveloper** [comment]
Hi @maxbeatty, good idea, I'll take a look at the kms. Thanks dude!
