### ISSUE TITLE
Isn't setting process.env in Electron app

### ISSUE THREAD

**Issue by tashoecraft** [motdotla/dotenv#139]
I am running an electron application with webpack and it seems to be pulling in the values from the .env file, but process.env isn't getting set. 

I have placed the require('dotenv').config() at the entrance to the application where webpack starts building, which is my where all my vendor files live. 

If I set a variable to the result of the require, it stores my variables, but when I go to use them only my Node_ENV variable is available.
 
.env

    GAUTHID=secretID

vendor.js

    module.exports = function() {
    require('dotenv').config();
    //lots of modules loaded in below
    }

home.js

    console.log(process.env)

logs => {NODE_ENV: 'Development'}

Wondering why it seems to access the values fine, but isn't saving them. I've tried different locations, using .load(), but all have no effect.

**Comment by maxbeatty** [comment]
Can you provide a [gist](https://gist.github.com) or similar example code to demonstrate how your project is laid out and the order of operations? As-is, I can't help 😿

**Comment by calebmer** [comment]
I am also experiencing this problem.

**Comment by maxbeatty** [comment]
@calebmer will you provide more details or example code to demonstrate the issue?

**Comment by tashoecraft** [comment]
@maxbeatty The project was based off the electron react boilerplate (**https://github.com/chentsulin/electron-react-boilerplate**), angular has been swapped for react but that shouldn't make a difference. I'm requiring in dotenv in the vendor.js file.

**Comment by maxbeatty** [comment]
I got dotenv working with that stack [here](https://github.com/maxbeatty/electron-react-boilerplate/commit/48c1878ad9245737315d6fa1aa26feb0ee1b4ef1). I'm very much so a webpack newbie. As I understand what was happening, their use of [`DefinePlugin`](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) to specify `process.env` overwrote everything in node's original `process.env` (hence only seeing `NODE_ENV`). Closing as a configuration issue.

**Comment by tashoecraft** [comment]
@maxbeatty That works perfectly. Should have assumed it was a webpack. Thank you.

**Comment by Tolsee** [comment]
I guess the problem was not getting `process.env` in the `Node` side.

**Comment by fc** [comment]
I'm also using `electron-react-boilerplate` and in `webpack.config.main.prod.js`, I added the following to inject the dotenv vars into webpack at build time.:
```
import dotenv from 'dotenv';

/* webpack stuff */

    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      ...dotenv.config().parsed // <-- this line
    }),

```
