### ISSUE TITLE
Use dotenv in npm scripts to load environment variables

### ISSUE THREAD

**Issue by JaKXz** [motdotla/dotenv#146]
I'm trying to use `dotenv` to load tokens needed for a CLI, but I think I'm missing something or there's an issue setting the variable on `process.env`. This is what my package.json scripts look like:

```json
"prerelease": "npm test",
"release": "node -e \"require('dotenv').config()\" && conventional-github-releaser -p angular -r 0",
```

and in my `.env` file the first line is `CONVENTIONAL_GITHUB_RELEASER_TOKEN=token`

I also tried using `node -r dotenv/config` but it expects a `.js` script as the next argument so it never actually runs. What am I missing? 

I'm using the latest releases of node (6.3.1) and npm (3.10.x) at time of writing.

**Comment by maxbeatty** [comment]
`-r` is the way to go. See [our example](https://github.com/motdotla/dotenv/blob/8252786cebf934d0282311f945b9d948000f3353/examples/preload/run_me#L5) and [another one of mine](https://github.com/maxbeatty/passplum/blob/068b9c8698b3262a4fb0d8b780e939674ce80820/package.json#L7)
