### ISSUE TITLE
A question about managing test and development on the same machine

### ISSUE THREAD

**Issue by juanpaco** [motdotla/dotenv#150]
I apologize in advance for posting what isn't actually an issue with the library.  I wasn't sure what other channel to ask this question through.

v1 removed auto `.env.${ NODE_ENV }` overrides, and so forth, and this was a fine change IMO.  I buy into the separate deployments. My question is more about your workflow as the library owners.

When I'm developing an app on my machine, I'm generally doing stuff in development and test, and these each have their own database they work with.  I've had it in my head that I need separate databases for those "environments," so that my unit tests don't clobber when I'm just poking around in a browser.

I do a branch on `process.env.NODE_ENV` to find the correct file for `dotenv` to load.  It works well enough, but still feels like a hack to support 2 separate "deployments" on a single machine.

So, I'm just wondering how you folks deal with doing development and testing on the same machine.  Do you do a similar branch on an env var?  Do you just do development and testing in the same DB?  Feed the db connection stuff in through the command line?  Something else?

I read through all the closed issues, and when this subject was touched on, branching based on an env var was mentioned.  Just wondering if there's something more refined.

**Comment by maxbeatty** [comment]
TIMTOWTDI so do whatever works best for you 🌠 

When we have target resources like a database or S3 bucket that varies per environment, we use the convention of appending the environment.

```js
const mysql = require('mysql')
const conn = mysql.createConnection({
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASS,
  database: 'application_name_' + process.env.NODE_ENV.toLowerCase()
})
```

```js
const AWS = require('aws')
const s3 = new AWS.S3()
s3.getObject({
  Bucket: 'my-gifs-' + process.env.NODE_ENV.toLowerCase(),
  Key: 'kangaroo-party'
})
```

I've been using Docker more and more so if I want to load different databases I can usually just change the mounted data volume on the database container without changing anything in the app.

**Comment by juanpaco** [comment]
With those different names I do the same thing, but I still have to have different `.env` files to have them.  When you're not doing Docker, do you just edit your .env before doing the thing that uses the other resources?

**Comment by maxbeatty** [comment]
I don't quite follow your setup. If you could share some simplified code, that's a big help.

My test runner sets `NODE_ENV` to `test` which takes precedence over whatever I have in `.env` (usually 'development') so I don't have to change anything.

**Comment by juanpaco** [comment]
Sorry for the delay in getting back.

Right now I have something like

```
var envFromRealEnvironment = process.env.NODE_ENV || 'development'
var path = `.env.${ envFromRealEnvironment }`

dotenv.config({ path, silent: envFromRealEnvironment === 'production' })
```

For running in dev mode, I have a `.env.development` and for running in test I have `.env.test`.  I got the impression from reading the docs that having different .env files on the same machine was frowned upon.

> Should I have multiple .env files?

> No. We strongly recommend against having a "main" .env file and an "environment" .env file like .env.test. Your config should vary between deploys, and you should not be sharing values between environments.

I haven't found a great way to separate my development environment from my test one.  I'm essentially having 2 "deployments" on the same machine, and I don't see how to do that without multiple .env files.  I was just wondering in light of that recommendation in the FAQ how other folks do test vs. dev.

That comment may have been about having a main one that gets overridden by an environment specific one, of course, in which case I'm just misreading it.  I took it to mean that even though one is developing and running tests on the same machine, ideally there should only be 1 .env file.

**Comment by maxbeatty** [comment]
> That comment may have been about not having a main one that gets overridden in a few values by an environment-specific one

Bingo. ["In a twelve-factor app, env vars are granular controls, each fully orthogonal to other env vars."](http://12factor.net/config) I understand why people want to define "defaults" and customize  per environment, but like 12factor says, it leads to more brittle deploys so dotenv tries to keep you disciplined.

**Comment by juanpaco** [comment]
I gotcha.  So having the separate ones as I do is totally in line with the recommendation, because there's no overriding or anything like that.  There's one complete set for development and another complete set for test, and there isn't any crossover between them.  Is that correct?

**Comment by maxbeatty** [comment]
yep looks good to me

**Comment by juanpaco** [comment]
Oh cool.  Thank you for the clarification.  Would you be open to a PR clarifying that point in the documentation?  I've had this nagging feeling that I had this dirty hack going on (because I do have multiple distinct .env files), but it stemmed from a misreading of that part in the FAQ.

**Comment by maxbeatty** [comment]
Thanks but I'm content leaving it as-is for now

**Comment by juanpaco** [comment]
kk.  Sounds good.  Thanks again for the explanation and for the library!

**Comment by lapinskicho** [comment]
> Should I have multiple .env files?
> 
> No. We strongly recommend against having a "main" .env file and an "environment" .env file like .env.test. Your config should vary between deploys, and you should not be sharing values between environments.


I had the same feeling as @juanpaco from reading the FAQ that having different .env files on the same machine was frowned upon...

**Comment by machineghost** [comment]
One more "me too".  I don't understand why you want to purposely confuse your users when a ten second change of a sentence or two could make matters so much clearer.

In fact, since having "test" and "dev" environments are almost a universal, and one of the main reasons people start using environmental variables in the first place, it's really strange that the documentation makes no mention of them whatsoever.

**Comment by NealHumphrey** [comment]
Bump on putting this in the docs! I also was confused by the docs statement cited above, and Google'd around until I found this thread. The [comment in #200](https://github.com/motdotla/dotenv/issues/200#issuecomment-306008625) makes it clear and would be a great addition to the docs.

**Comment by stouf** [comment]
Same here, I also find the current docs misleading. A few lines to clarify the matter as it is explained in this issue wouldn't hurt and would avoid many wonders in my opinion.

**Comment by cristiboariu** [comment]
+1 me too. Spent 2 hours until this was clarified for me here because from README it's totally unclear.

**Comment by mjlehrke** [comment]
>...The comment in #200 makes it clear and would be a great addition to the docs.

Wow, the README is the exact opposite of that comment.  Glad you posted it because I too was confused.
