### ISSUE TITLE
Environment specific vars are ignored

### ISSUE THREAD

**Issue by teckays** [motdotla/dotenv#151]
I have two env files `.env` and `.env.local`. For obvious reasons my `.env.local` file contains db credentials for my local database, however when I run `NODE_ENV=local node index.js` the vars from `.env.local` are ignored, therefore NOT SET. Clues? Is it possible to do even?

**Comment by jcblw** [comment]
We removed the feature of autoloading `.env.${NODE_ENV}`, around version 1.0.

you should still be able to do this functionality by specifying the path to the file using a config option.

```javascript
require('dotenv')
  .config({path: `./.env.${process.env.NODE_ENV`})
```
