### ISSUE TITLE
Request: provide a cli interface to dotenv

### ISSUE THREAD

**Issue by abelnation** [motdotla/dotenv#152]
so that you could pull in your `.env` file before running a command, e.g. in an npm script:

```
...
"scripts": {
  "build": "dotenv && gulp build"
},
...
```

**Comment by jcblw** [comment]
This is actually kinda tricky, was thinking about adding this a couple month ago. The main hurdle is that when running `dotenv && gulp build` you are creating two different processes. Which means adding env to a `process.env` in one does not carry over to the other. I have seen this work in the other dotenv libs by wrapping the command in a subprocess. 

I don't think we are going to want to maintain that functionality in this repo. I would encourage you or anyone looking for this functionality attempt to wrap that around the current functionality in this repo.

**Comment by abelnation** [comment]
yeah, i came to that thought as well when trying to come up w/ my own solution :-/

**Comment by maxbeatty** [comment]
if `gulp` is your primary use case for the CLI, doesn't that mean you'll have a "gulpfile" where you could configure and run dotenv? are there other CLI use cases you had in mind? (don't forget we support [preloading](https://github.com/motdotla/dotenv#preload))

**Comment by abelnation** [comment]
yup, and that's what i ended up doing
