### ISSUE TITLE
fs.readFileSync is not a function error 

### ISSUE THREAD

**Issue by Bobeta** [motdotla/dotenv#153]
I followed the installation procedure, I get the following error by just requiring dotenv:

`fs.readFileSync is not a function`

I'm using node v6.6.0.

**Comment by wilmoore** [comment]
Would you mind posting your .envrc file?

**Comment by maxbeatty** [comment]
[readFileSync](https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readfilesync_file_options) is a function that's been around since v0.1.8 of Node.js. Really unlikely this is a problem with dotenv

**Comment by Bobeta** [comment]
@maxbeatty That's what I thought as well, but I don't have the error when I don't require 'dotenv', strange.

**Comment by wilmoore** [comment]
@Bobeta - You might also check into whether this is a node v6.x.x issue by trying an older version of node.

**Comment by jcblw** [comment]
@Bobeta there seems to be something with your configuration. Just tested

> node v6.6.0 (npm v3.10.3)

```
node -r dotenv/config -e 'console.log(process.env.FOO)'
```

and

```
node -e "require('dotenv').config(); console.log(process.env.FOO)"
```

both worked as expected.

**Comment by Bobeta** [comment]
Thanks folks for your replies!

@jcblw Hmm, it works for me as well in node console. I forgot to mention that I use watchify and babelify. I get that error after it outputs it to ES5. My start script in package.json looks something like this:

`
    "start": "watchify src/main.jsx -v -t [ babelify --presets [ react ] ] -o public/js/main.js",`

**Comment by Bobeta** [comment]
@maxbeatty How is it not ap roblem with dotenv when in dotenv/lib/main.js on line 30, you have the following snippet:

```
 try {
      // specifying an encoding returns a string instead of a buffer
      var parsedObj = this.parse(fs.readFileSync(path, { encoding: encoding }))
...
```

That also happens to be the snippet the console error is referring to.

**Comment by jcblw** [comment]
@Bobeta `dotenv` is a server side library, and will not work if your include it into your browser bundle. I would suggest using something like [envify](https://github.com/hughsk/envify) with `dotenv` to achieve this.

**Comment by Bobeta** [comment]
@jcblw I figured that out as I was typing the comment, wouldn't make sense to have it in the browser bundle. Silly me.. Thanks for your help!
