### ISSUE TITLE
Child Process

### ISSUE THREAD

**Issue by jcampbell05** [motdotla/dotenv#157]
Will child processes inherit these ?

**Comment by maxbeatty** [comment]
Per usual, it depends how you are spawning child processes. [`child_process` includes an environment key-value pairs option](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) that you can pass the dotenv-populated `process.env`

```js
require('dotenv').config()
const cp = require('child_process')

cp.exec('node thing_two.js', {
  env: process.env
})
```
