### ISSUE TITLE
Command interpolation in variable values

### ISSUE THREAD

**Issue by tscizzle** [motdotla/dotenv#159]
Would be wicked helpful to allow inserting the output of arbitrary commands into the values of the environment variables. And there is precedent for it.

From https://github.com/bkeepers/dotenv Usage section:

> You need to add the output of a command in one of your variables? Simply add it with $(your_command):
>
> DATABASE_URL="postgres://$(whoami)@localhost/my_database"

Awesome package, by the way.

**Comment by maxbeatty** [comment]
Interpolation has been discussed many times before. tl;dr it's very error-prone. 

Executing arbitrary commands seems like a lazy crutch given that one example. I'm not sure this is something we want to add.
