### ISSUE TITLE
express ignores NODE_ENV set by dotenv

### ISSUE THREAD

**Issue by guilhermecvm** [motdotla/dotenv#160]
`export NODE_ENV=`
.env
```
NODE_ENV=production
```
```javascript
console.log(process.env.NODE_ENV) //production
console.log(app.get('env')) //development
```

**Comment by jcblw** [comment]
What does your initialization of dotenv look like. I would assume as long as dotenv is imported before express this should work.

**Comment by maxbeatty** [comment]
dotenv does not override existing environment variables so if you export `NODE_ENV` and then define it in `.env`, it will not be set.
