### ISSUE TITLE
Multi-line JSON

### ISSUE THREAD

**Issue by kdschaffe** [motdotla/dotenv#161]
Is there a way to have variables be in multi-line JSON format? I see you can do JSON and multi-line with \n if it's in quotes but that doesn't seem to work with quoted JSON keys/values.

**Comment by jcblw** [comment]
can you put an example of what this would look like?

**Comment by maxbeatty** [comment]
it would also be helpful to explain why you need to change out an entire JSON blob for different environments

**Comment by kdschaffe** [comment]
Sure - I'll preface, there's nothing I'm doing that can't be done another way but I have come across a few different environment variables that are used in a cloud hosting environment that I'm trying to mimic locally with dotenv. Some are large structures and some small but either way it looks cleaner to be able to format the JSON. I can expand on why if needed but it's really just install/security process and other architectural decisions that lead to them being created this way. 

As far as what this would look like, it'd really be any json structure. E.g.
`
JSON_VAR=[
  { "foo": "bar",  "foo2": "bar2"}, 
  { "foo": "bar",  "foo2": "bar2"}
]
`

I'm not exactly sure what the ideal approach to allowing this would be. Maybe escaping start and end so you don't have to have \n on each line.

**Comment by maxbeatty** [comment]
I don't think dotenv is the tool for your job here. I'd suggest just using JSON directly
