### ISSUE TITLE
Issue importing config into client-side files

### ISSUE THREAD

**Issue by rockchalkwushock** [motdotla/dotenv#173]
Not exactly sure why this is occurring, my thought is it's possibly a file structure thing; but when I do an `import '../../../api/config/envConfig';` into my _openWidget.js_ file and run the project I am met with the following error:

**Uncaught SyntaxError: Unexpected token import**
![screen shot 2017-01-13 at 1 50 15 pm](https://cloud.githubusercontent.com/assets/19720404/21943540/47a927a2-d997-11e6-8aac-fa042623233a.png)

The file structure pertinent to the error is below. I initial built the backend an made a config directory for holding all configs through out the api. I'm wondering if the fact I'm trying to import from the `api/` into the `client/` if there is some `babel` magic getting lost.

I realize this is not necessarily a `dotenv` issue as much as it is a `babel` issue. I am just curious about file structure. Should the `config/` be located on the root level instead of how I have it now?

```plaintext
api/
  config/
    envConfig.js
  index.js <-- server
client/
  src/
    helpers/
      openWidget.js
    index.js <-- entry point for create-react-app
.env
index.js <-- entry point for calling API Server.
start-client.js <-- entry point for calling client.
```

I have things set up so that my client is performing a _proxy_ on the API Server running on `8000` while the CRA dev-server runs on `3000`. To run both at the same time I'm using `concurrently`:

```json
"start": "concurrently \"npm run server\" \"npm run client\"",
"server": "nodemon index.js",
"client": "babel-node start-client.js",
```
_index.js_ (entry point for server)
```javascript
require('babel-register');
require('babel-polyfill');
require('./api');
```

_start-client.js_ (entry point for server)
```javascript
const args = ['start'];
const opts = { stdio: 'inherit', cwd: 'client', shell: true };
require('child_process').spawn('npm', args, opts);
```
I'm wondering if I need to do `require('babel-register');` & `require('babel-polyfill');` in the _start-client.js_ to handle this babel issue.

Like I said really just interested in feedback on the file structure and if that is something I should think about changing. Thanks!

**Comment by maxbeatty** [comment]
Sorry you're having trouble. This sort of question is probably better for StackOverflow. My quick 2 cents is to use webpack (that comes with create-react-app) to manage env vars on the client

**Comment by rockchalkwushock** [comment]
@maxbeatty 

I have done some reconfiguration to where I make the env vars available immediately in project:

_index.js_ (API Server entry point)
```javascript
import 'babel-register';
import 'babel-polyfill';
import 'dotenv/config';
import './api'; // reads off index.js which is my API server code.
```
If I do a `console.log(process.env)` everything listed in my `.env` is present in the object and being made available to `/api` 💯 

Now I don't have slightest clue of how to do the same in:

_start_client.js_
```javascript
const args = ['start'];
const opts = { stdio: 'inherit', cwd: 'client', shell: true };
require('child_process').spawn('npm', args, opts);
```
So I did the following in the entry point for the client:

_client/index.js_
```javascript
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { IntlProvider, IntlActions } from 'react-redux-multilingual';
import ReduxToastr from 'react-redux-toastr';
import { store } from './redux/store';
import Routes from './Routes';
import { translations } from './modules';

require('dotenv').config({ path: '../../.env' }); // double checked and this is the correct path.

console.log(process.env);

const DEFAULT_LANGUAGE = 'ru';
store.dispatch(IntlActions.setLocale(DEFAULT_LANGUAGE));

render(
  <Provider store={store}>
    <IntlProvider translations={translations}>
      <div className='provider'>
        <Routes />
        <ReduxToastr
          timeOut={2500}
          newestOnTop={false}
          preventDuplicates
          position="top-right"
          transitionIn="bounceIn"
          transitionOut="bounceOut"
          progressBar
        />
      </div>
    </IntlProvider>
  </Provider>,
  document.getElementById('root')
);
```
What I'm seeing on the `console.log`:

![screen shot 2017-01-16 at 10 34 01 am](https://cloud.githubusercontent.com/assets/19720404/21991226/53ff6a74-dbd7-11e6-92ec-1255a42b05e8.png)

So at the end I'm not being able to make these env vars available to the `/client`. Any ideas or places I'm going wrong? This is a link to the last commit with the changes I've made: https://github.com/rockchalkwushock/photography-backend/commit/c18c053a577d9052c1041867cfc49d8caf49a157

**Comment by maxbeatty** [comment]
`create-react-app` already includes `dotenv` in its [build and start scripts](https://github.com/facebookincubator/create-react-app/blob/v0.8.5/packages/react-scripts/scripts/build.js#L19) so you don't need it in your client code

**Comment by rockchalkwushock** [comment]
I see that; but if my `.env` is not present in the directory that houses the CRA code then the `dotenv` present there will not read it. Is it possible to in either the `build` or `start` script to declare in the command where to look for the `.env`?

Maybe something like the following?

```json
"start": "npm run config && react-scripts start",
"config": "node -r dotenv_config_path=../../.env"
```
