### ISSUE TITLE
last version in amazon lambda code

### ISSUE THREAD

**Issue by endymion00** [motdotla/dotenv#174]
Hi,
I'm using dotenv in amazon lambda code and as I see the last version (4.0.0) supports node engines >= 4.6.0.
I'm wondering if there is something it can be done in order to support node.js in amazon lambdas because they run on node 4.3.2.

**Comment by maxbeatty** [comment]
It'll work just fine. The node engine range is mostly to keep up with the latest LTS releases (v4 enters maintenance in 2 months).

[AWS Lambda has built-in Environment Variables](http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html) which is a better way to go
