### ISSUE TITLE
Proper usage

### ISSUE THREAD

**Issue by cloud-tribal** [motdotla/dotenv#175]
I think I understand the value of the package. Environment variables scoped to a project.

I also think I understand why .env should be in .gitignore.

To clarify: should there be an exclusive .env file for each environment in each environment?

**Comment by maxbeatty** [comment]
Yes, each variable should be different in each environment so you would have a `.env` file for each environment. 

An easy example is database configuration. When developing locally, you may have a database running on your machine with easy-to-use-but-insecure credentials.

```dosini
DB_HOST=localhost
DB_PASS=password
```

When you're ready to run your app in a hosted environment, you'll want to use a different database instance and a stronger password.

```dosini
DB_HOST=my-project.r4nd0m.us-west-2.rds.amazonaws.com
DB_PASS=long-does-not-mean-secure
```

Meanwhile, your application code doesn't change.

```js
const db = require('./db')

db.connect(process.env.DB_HOST, process.env.DB_PASS, (err) => {
  if (err) {
    throw err
  }
});
```
