### ISSUE TITLE
Dotenv vars missing from npm run-scripts environment

### ISSUE THREAD

**Issue by keithws** [motdotla/dotenv#178]
Dotenv looks great and I'm excited to use it. I would especially like the environment variables I define in my .env file to be visible to the npm run-scripts I define in package.json.

It took a bit of research, but I think I have solution. What do you think?

I figured out I could preload the dotenv module in npm with the following .npmrc file in my project.
```ini
onload-script = dotenv/config
```

I had to install dotenv globally to get this to work. Can that be avoided? Will that cause problems?

**Comment by maxbeatty** [comment]
If your npm run-scripts are node-based, you should be able to use [preload](https://github.com/motdotla/dotenv#preload) ([example](https://github.com/motdotla/dotenv/tree/master/examples/preload))

```json
{
  "scripts": {
    "example": "node -r dotenv/config example.js"
  },
  "dependencies": {
    "dotenv": "latest"
  }
}
```

If they are some other sort of binary, then a global install won't hurt anything (but it may not be the right tool for the job).

**Comment by juliocanares** [comment]
@maxbeatty how can I pass the path to the dot file using `--require`

**Comment by maxbeatty** [comment]
You can use the `dotenv_config_path` argument. All options are supported in this fashion. [See README](https://github.com/motdotla/dotenv/blob/825c1b221e80c3fedb61d36abc077851abde94d2/README.md#preload) for full example.
