### ISSUE TITLE
Question: proper usage of dotenv and gitignore

### ISSUE THREAD

**Issue by itaied246** [motdotla/dotenv#180]
Considering the deployment cycle and development environment,
I can't understand why shouldn't I commit my dotenv file.

For development purposes, I want some local db (sqlite), keys, passwords, tokens (etc) values,
which I can't remember or don't want every developer to copy from some place.
I think I would rather publish them and use them just for the development / test environments.

In my production environment, however, I will set environment variables in the machine (docker for example).

Just wanted to hear your thoughts, what do you guys think?

**Comment by maxbeatty** [comment]
1. Do whatever works for you and your team
2. Make it hard for other people to make mistakes

[I am a lazy git committer](https://github.com/maxbeatty/dotfiles/blob/9dc5dd30599ab75e459f652e184930db362cc466/.aliases#L41) so if `.env` is tracked by git it would be setting me up to commit something sensitive. Once a secret is on GitHub, consider it compromised. It's a lot easier to ignore a file than to change the behavior of everyone contributing to your repo.

There's lots of ways to ease populating a `.env` file with defaults. jsPerf used to have a [setup script](https://github.com/jsperf/jsperf.com/blob/ac98e5dfab07012dd4de3200b0ef27fd89e63a1c/setup/index.js). Copying and pasting defaults from a README is pretty low effort to prevent accidental leaks, but like I said– do what works for you and your team.
