### ISSUE TITLE
Random Corruption of Client ID Stored in .env

### ISSUE THREAD

**Issue by tetreault** [motdotla/dotenv#183]
Hello, 

I store my API keys in the .env file. I have a config.js file server side that pulls in the values from the .env file via `process.env.FIELD_NAME`. If I hard code my API keys when we instantiate a new SpotifyWebApi object inside server.js it is functional but otherwise pulling it via .env will fail.

I scanned the .env file for any invisible characters that somehow got introduced thru VIM that were messing things up but there was nothing there.

Furthermore, I have other API keys stored in the .env file (after the Spotify API keys) and there was zero issue getting those API keys from that file into config.js. The issue here was only present with the Spotify Client ID.

I know the keys are correct because I copied them from the .env file and hardcoded them into my server.js file - I didn't re-copy them from the Spotify Dev dashboard.

To make matters even more confusing I printed out the keys from **.env -> config.js -> server.js**. For the Spotify Client ID only there is an extra single quote being added to the end of it. The Client Secret is not affected however. I checked all through - no extra single quote anywhere plus again the other API keys in the .env file dont have this issue.

Apologies if this issue sounds vague, it feels like it is since I haven't had this happen before. 

**Versions**:
- dotenv: 4.0.0
- npm: 3.10.9
- node: 7.2.0

**Comment by motdotla** [comment]
Possibly you've found an extreme edge case here, and my hunch would be it is choking on the regex inside the dotenv lib. It's a guess at least.

Do you have the ability to generate a new Spotify client ID and see if that one works?

**Comment by tetreault** [comment]
Thanks for the replay @motdotla and thanks for this module - love it a ton. I wont have the chance to get around to that till later this week but the second I do I'll report back here!

**Comment by motdotla** [comment]
Sounds good. In the meantime, I'm closing this. Just comment in the closed ticket.
