### ISSUE TITLE
How do I run testing without creating .env.test?

### ISSUE THREAD

**Issue by shai32** [motdotla/dotenv#184]
Hi,
How do I run testing without creating .env.test?
when I run the test (that inside test folder), it uses the .env file in the main folder.
but I want to run the test with different environment variables.
![image](https://cloud.githubusercontent.com/assets/16700996/24589395/4308beb8-17e2-11e7-8f17-611f36b1beeb.png)

**Comment by motdotla** [comment]
Hi @shai32, great question.

Ideally, you should mock or set them individually in each test. Here is a nice tool to mock them:

https://www.npmjs.com/package/mock-env

and here is a good example of setting them:

http://stackoverflow.com/questions/24589021/how-to-stub-process-env-in-node-js

**Comment by shai32** [comment]
mock-env look redundant.
the stackoverflow suggestion is to just change it directly (and return the original value to env after)
but this also is not a good idea. because I have a lot of tests files that all need the same env variables 
so I need to write down those variables for each file.

adding .env.test solve all this issues.

**Comment by motdotla** [comment]
Try to work your tests toward smaller chunks - where your test is only dependent on an ENV or two at a time. Mocking really helps with this and `mock-env` will do the trick for you.

If you really want to include a `.env.test` you can do so by specifying the path to it, and then call `dotenv.config(path: '')` inside a before suite hook of your test suite: https://github.com/motdotla/dotenv#path

**Comment by shai32** [comment]
@mostlyjason yea I used the path options, works great.

**Comment by Quocnamit** [comment]
Hi @motdotla and @shai32 

I'm working on Unit Test of angular 2. I use Dotenv for defining application variables for Dev and Prod env. 
Now I want to use for my test. Could you show me the way in details ?
Thanks
Nam
