### ISSUE TITLE
Where is the spec?

### ISSUE THREAD

**Issue by franciscop** [motdotla/dotenv#186]
Is there an official specification for `.env` files? In particular, I'd like to know if there's a recommended way of storing "object" information such as:

```js
const obj = {
  a: 'a',
  b: 'b',
  c: 'c'
};
```

It seems that many projects just use the `_` like:

```
DB_HOST=...
DB_USER=...
```

However there are also variables that use the `_` just as a separator:

```
NODE_ENV=production
```

So, is there a standard way? Is there an official specification?

PS, thanks a lot for the project, I'm using it with [https://serverjs.io/](server for Node.js).

**Comment by motdotla** [comment]
They should be treated as simple key values. So in your case I would use the underscore and adjust those to `OBJ_A=something`, etc.

They are just OS env variables. Here's more info on them:

+ https://en.wikipedia.org/wiki/Environment_variable
+ https://12factor.net/config
