### ISSUE TITLE
`dotenv` won't install when listed in the package.json dependencies

### ISSUE THREAD

**Issue by joelataylor** [motdotla/dotenv#187]
Not sure what's going on here, but we've had this happen a few times (both local and on Heroku) but when we specify `"dotenv": "^4.0.0",` in our `package.json` file and run `npm install`. The package is *not* installed.

We have to install it manually with: `npm install dotenv`.

I'm on Node: 6.6.0
NPM: 4.0.5

Any suggestions?

**Comment by maxbeatty** [comment]
Sorry, not much we can do about npm failures
