### ISSUE TITLE
Loading dot env file in Unit Testing

### ISSUE THREAD

**Issue by Quocnamit** [motdotla/dotenv#190]
Hi @motdotla ,

I'm writing unit test for my angular 2 app with jasmine + karma. Could you show me the way to load dot env to test component ?

Thanks
Nam

**Comment by maxbeatty** [comment]
if your unit tests depend on something outside of the code you're testing, it's not a unit test 😁

**Comment by motdotla** [comment]
@maxbeatty is right, but if you are looking for some ways to solve your problem, take a look at this thread: https://github.com/motdotla/dotenv/issues/184

**Comment by picosam** [comment]
@motdotla on another note, how would you resolve the fact that we need to get, for instance, an auth token to execute the tests? The issue really is that each developer will get the auth token using their own account on Auth0, which requires several environment settings that should ideally not be shared between developers or committed to git. Any ideas?
