### ISSUE TITLE
File Structure Matter? 

### ISSUE THREAD

**Issue by Bharwcb** [motdotla/dotenv#191]
My file structure looks like this:

- app
  - auth_code
    - app.js
    - public
      - index.html
  - .env
    
.env file:
```
CLIENT_ID=12345
```

And testing 'dotenv' in app.js prints null:

```
require('dotenv').config()
console.log("CLIENT_ID: ", proces.env.CLIENT_ID);
```

If anyone has any idea on what I'm doing wrong, I'd greatly appreciate it.

**Comment by maxbeatty** [comment]
Try using the [path option](https://github.com/motdotla/dotenv/blob/v4.0.0/README.md#path) and work backwards from there. dotenv reads from the current directory of where the node process was invoked so `node app.js` would explain it not being found but `node auth_code/app.js` should work given what you've outlined.

**Comment by Bharwcb** [comment]
Thank you @maxbeatty !

**Comment by itPiligrim** [comment]
Absolute path to .env file is not good idea. My solution:
package.json
....
"scripts": {
    "watch-node": "cd app/ && nodemon server.js",
},
....

**Comment by csimpi** [comment]
@maxbeatty hardcoding a path to a development folder sounds like a really bad idea, this shouldn't be closed.
Altough, this is not a `dotenv` issue, more like a nodemon, you shouldn't recommend hardcoding paths IMHO
