### ISSUE TITLE
App can't find env variable

### ISSUE THREAD

**Issue by brianlizhou** [motdotla/dotenv#192]
My current file structure is pretty basic, it's just

- app.js
- passwords.env
- routes
&nbsp; -index.js

with a require('dotenv').config() as the first line inside index.js in routes, but it keeps saying that my environment variable is undefined.

I've installed dot env properly using the documentation instructions, it compiles properly, and my passwords.env file is literally just
PASSWORD=RANDOMPASSWORD
with my reference in the javascript file as:
console.log(process.env.PASSWORD). 
I'm running require('dotenv').config() as the first line but it's still giving me undefined for the environment variable.
Can anyone give me any pointers as to how I might be configuring this wrong? I'm using Macos

**Comment by brianlizhou** [comment]
Never mind, it works if you use .env instead of passwords.env. My bad! Could someone please close this issue? Thanks

**Comment by thameera** [comment]
@brianlizhou If you want to use a custom name for the file, you can configure that too: https://github.com/motdotla/dotenv#path
