### ISSUE TITLE
Not working with debug

### ISSUE THREAD

**Issue by hyperh** [motdotla/dotenv#193]
I can't seem to get `debug` working with `dotenv`. It works fine when I set the env var from outside of .env like so:

package.json
```
"dev": "NODE_ENV=development DEBUG=*,apicache nodemon",
```

```
npm run dev
```

server.js
```
import 'babel-polyfill';
import makeDebug from 'debug';
import dotenv from 'dotenv';

const env = dotenv.config();
console.log(process.env.DEBUG); // outputs *,apicache correctly
const debug = makeDebug('brainfm:server/index');
debug('.env', env); // Doesn't show anything
```

.env
```
DEBUG =*,apicache
```

https://github.com/visionmedia/debug/issues/446#issuecomment-297514555

**Comment by maxbeatty** [comment]
You have a space between `DEBUG` and `=` in your `.env`. When I tried to reproduce using this `package.json`, it worked fine

```json
{
  "dependencies": {
    "babel-cli": "^6.24.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "debug": "^2.6.4",
    "dotenv": "^4.0.0",
    "nodemon": "^1.11.0"
  },
  "scripts": {
    "start": "babel-node server.js --presets=es2015"
  }
}
```

```
$ yarn start
yarn start v0.23.2
$ babel-node server.js --presets=es2015 
*,apicache
✨  Done in 1.19s.
```

**Comment by OllieJennings** [comment]
@maxbeatty This issue is now occurring again, when using `DEBUG` within the `.env` file, nothing inside of your app is being logged out to terminal.

**Comment by maxbeatty** [comment]
Will you provide detailed steps to reproduce?

**Comment by OllieJennings** [comment]
Sure @maxbeatty, contents of files below

**.env**
```env
DEBUG='worker'
```

**index.js**
```js
const debug = require('debug')('worker');

console.log('Debug below');
debug('message from worker');
console.log('Debug above');
```

**package.json**

```json
"scripts": {
  "start": "babel-node -r dotenv/config ./src/index.js"
}
```


**output**

```sh
$ Debug below
$ Debug above
```


Versions
- dotenv: **8.0.0**
- debug: **4.1.1**
- node: **10.11.0**
- babel/node: **7.2.2**

**Comment by xamgore** [comment]
Same here, the `debug v3.2.6` works with `dotenv v8.0.0`, but fails with `debug v4.0.0`.

**Comment by xamgore** [comment]
@maxbeatty could you open the issue, please, so people will be informed about potential problems?

**Comment by maxbeatty** [comment]
From #398 

> To be clear, this is a configuration issue with babel and/or debug and not a problem with dotenv.
