### ISSUE TITLE
Environment variables fail to load when run as a command line app

### ISSUE THREAD

**Issue by ajibigad** [motdotla/dotenv#194]
So am working on a command line app to send mails.
After doing npm link to make the app a command line app that can run in the cmd irrespective of the folder, the app fails when run as a cmd app.
When i run the app as a node app using the usual node command e.g node mailer.js, it works fine but when i run as a command line app eg mailer, it fails to load the environment variables. 

**My package.json**
```
{
  "name": "mailer",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "preferGlobal": true,
  "bin": "./mailer.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "commander": "^2.9.0",
    "dotenv": "^4.0.0",
    "inquirer": "^3.0.6",
    "mongoose": "^4.9.2",
    "nodemailer": "^4.0.1"
  }
}
```
**Snippet from my mailer.js**
```
#!/usr/bin/env node
require('dotenv').config()
```
Pls help. Thanks

**Comment by maxbeatty** [comment]
I'm guessing this is a path issue and [this recent comment](https://github.com/motdotla/dotenv/issues/191#issuecomment-296782179) may help debug.

My two cents: if you're intending on distributing a command line tool that requires configuration (env vars), consider using an argument parser like [yargs](http://yargs.js.org/)

**Comment by csimpi** [comment]
@maxbeatty what if we want to pass some sensitive data and don't want to use arguments?
