### ISSUE TITLE
Usage reason?

### ISSUE THREAD

**Issue by VenPot** [motdotla/dotenv#198]
Not an issue but a curious question. I keep my config values in a file ,iterate through it and assign it to process.env.xxxx.when the app starts. How is this package any different than how I currently load my config and why are so many people downloading the package for such a trivial task? Could some one please explain.? I just want to make sure I understand the context and what is lacking in my simple approach  before I pick up this module. Thank you for your time and do excuse if this is too basic a question to ask....

**Comment by maxbeatty** [comment]
Check out [Sindre's explanation about small modules in general](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328)
