### ISSUE TITLE
Add an option which allows override environment variables

### ISSUE THREAD

**Issue by ApacheEx** [motdotla/dotenv#199]
**It's a feature request.**

I think it would be cool if there will be option `override` or similar which can allow/disallow overriding of environment variables.
Like this:
```
require('dotenv').config({
  override: true
});
```
some discussions can be found here https://github.com/facebookincubator/create-react-app/issues/2230#issuecomment-302921036. 
What do you think?

**Comment by maxbeatty** [comment]
This has been discussed before (sorry I'm too lazy to find old links). It's not a good idea because you could accidentally mess with variables that node or your system depend on. You can always override env vars via the command line.

**Comment by juanpaco** [comment]
This is unfortunate in my case. :(  create-react-app is binding to the wrong host because HOST is set in my system environment.  I've always treated the .env files as me stating this MUST be my environment.  It is what it is though, and dotenv is still a useful library.

**Comment by dschaller** [comment]
Hey @juanpaco I had the same need and built this functionality out in https://github.com/dschaller/dotenv/tree/overwrite-option. Give it a try :D

**Comment by miguelmota** [comment]
@maxbeatty the override flag is a must have. There's no harm in including this feature since the default behavior will be as it currently is. dotenv becomes essentially pointless if you have to pass environment variables in the command line. dotenv should override process.env variables and not export them system wide so I don't see how it could affect node or the system it's running on

**Comment by userpixel** [comment]
I've made a PR and done my best to update tests and documentations. I hope it'll get merged and soon we'll have a minor version bump to celebrate :tada:

**Comment by tylerlong** [comment]
- https://www.npmjs.com/package/dotenv-override
- https://www.npmjs.com/package/dotenv-override-true

**Comment by furryablack** [comment]
A primitive review case with dotenv-expand &&  dotenv
```js
const dotEnv = require("dotenv")
const dotEnvExpand = require("dotenv-expand")

const getDotEnvFiles = (dotEnvPath = `${ROOT_PATH}/.env`) => ([
  `${dotEnvPath}.${NODE_ENV}`,
  `${dotEnvPath}`,
])

const setupDotEnv = (dotEnvFile) => {
  dotEnvExpand(
    dotEnv.config({
      path: dotEnvFile,
    }),
  )
}

getDotEnvFiles().forEach((dotEnvFile) => {
  if (fs.existsSync(`${dotEnvFile}.local`)) {
    setupDotEnv(`${dotEnvFile}.local`)
  }
  if (fs.existsSync(dotEnvFile)) {
    setupDotEnv(dotEnvFile)
  }
})
```
env files for example:
- .env.production
APP_NEEDS_MINIMIZE=true
- .env.production.local
APP_NEEDS_MINIMIZE=false

**Comment by GitStorageOne** [comment]
This feature should be implemented as stated below:  
* Load specified env file, and apply all settings that does't present in process.env.
   **Optional** option to override system variables `overrideSystemVariables` is appreciated since developers better know which variables they want use or override, default behavior should not override, but if developer need do such thing, good customizable project should give necessary power.
* If `dotenv.config` called again with another path to env file library should load variables:
  * if `overrideSystemVariables=false` then override parameters that was loaded from any env file before but should not touch any system variables.
  * if `overrideSystemVariables=true` then override any parameters.

**Comment by MaffooBristol** [comment]
@tylerlong's solution works very nicely. I'd love to see it brought into core, it's optional after all. It could even have a warning in the documentation...!

**Comment by berkus** [comment]
Definitely a must-have. If it's a configuration option that defaults to false no default installations of dotenv would be harmed.

**Comment by motdotla** [comment]
Re-opening this issue. We are going to do this. It is more intuitive.

**Comment by motdotla** [comment]
This is now available in `v14.1.0` and above 🎉: https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1410-2022-01-17

Docs: https://github.com/motdotla/dotenv#override

**Comment by MaffooBristol** [comment]
Thank you @motdotla!

**Comment by TerryGoh** [comment]
I can't seems to override the variables in the .env file
 my codes : 

  require('dotenv').config({ path: './.env',override: false });
  let test = process.env.test
  process.env.test = "r34343"

but test variable in the .env was not update

**Comment by TerryGoh** [comment]
I can't seems to override the variables in the .env file
my codes :

    require('dotenv').config({ path: './.env',override: true});
    let test = process.env.test
    process.env.test = "r34343"

But the test variable in the .env was not update. Any idea how to update variables in the .env file via in js.

**Comment by berkus** [comment]
> But the test variable in the .env was not update. Any idea how to update variables in the .env file via in js.

It works the other way around, variables defined in `.env` override whatever was in the environment previously. dotenv doesn't write to any files.

**Comment by atljoseph** [comment]
Trouble is that old versions of node can't use the newer version!

**Comment by taljacob2** [comment]
> I can't seems to override the variables in the .env file my codes :
> 
> ```
> require('dotenv').config({ path: './.env',override: true});
> let test = process.env.test
> process.env.test = "r34343"
> ```
> 
> But the test variable in the .env was not update. Any idea how to update variables in the .env file via in js.

I found out that you need to re-state the `require('dotenv').config({ path: './.env', override: true });` line after overriding the env variable:

In you case:

```js
require('dotenv').config({ path: './.env', override: true });
let test = process.env.test
require('dotenv').config({ path: './.env', override: true });
process.env.test = "r34343"
```
