### ISSUE TITLE
optionally change the file name of ".env"

### ISSUE THREAD

**Issue by sidazhang** [motdotla/dotenv#20]
I have a complex set of environments which meant simultaneously having multiple .env.staging / .env.development / .env.development2 etc. 

I would like to the ability to optionally override the file which you load env. 

``` js
    _loadEnv: function(fileName) {
       if (!fileName) {
             fileName = ".env"
      }
      return dotenv._getKeysAndValuesFromEnvFilePath(fileName);
    },
```

**Comment by tianhuil** [comment]
You can set it either in javascript via
```
require('dotenv').config({ path: '/full/custom/path/to/your/.env' })
```

or by passing it through the command line

```
DOTENV_CONFIG_PATH=/full/custom/path/to/your/.env node -r dotenv/config your_script.js
```

Both examples are documented in the [README.md](https://github.com/motdotla/dotenv#preload)

**Comment by LagomarsinoHS** [comment]
sorry for revive this trend but my question is:
can i name a .env file differently? like idk, environmentFile and then how can i call it?
just dotenv.config({path:"rute/to/environmentFile"})

Thank u
