### ISSUE TITLE
Existing (but falsy) env vars are overridden

### ISSUE THREAD

**Issue by marcoow** [motdotla/dotenv#202]
When an env var already exists (but is falsy, e.g. an empty string) it is overridden which I'd say is wrong.

Example:

```
cat .env
MYVAR=value

MYVAR='' node
> process.env.MYVAR
''
> const dotenv = require('dotenv');
> dotenv.config()
{ MYVAR: 'value' }
```

That behavior is caused by this line: https://github.com/motdotla/dotenv/blob/master/lib/main.js#L63

**Comment by maxbeatty** [comment]
Can you expand on why you'd say it is wrong? What would be the correct behavior to you?

**Comment by marcoow** [comment]
`MYVAR` shouldn't be overridden in that case because it's set (although to a falsy value). I'd expect

```
cat .env
MYVAR=value

MYVAR='' node
> process.env.MYVAR
''
> const dotenv = require('dotenv');
> dotenv.config()
{ MYVAR: '' }
```

The use case here is that in my `.env` I'm setting something like

```
MYVAR=value
```

but then in some cases (e.g. when running tests) I want to override this to

```
MYVAR=''
```

which is currently not possible. The only way to do that would be to modify the `.env` file.

**Comment by maxbeatty** [comment]
Thanks for including a use case (that's usually my next question). I'd welcome a PR to improve the "is this variable set" logic.

If you're looking for a quick workaround in unit tests, I usually do this for absolute control.

```js
let oldVar

before(() => {
  oldVar = process.env.MY_VAR
  process.env.MY_VAR = ''
})

after (() => {
  process.env.MY_VAR = oldVar
})
```

**Comment by marcoow** [comment]
My use case isn't really a unit test but an integration test scenario where I start up a server (and then make requests against that and assert on the response) that itself reads its settings from `.env`  but in the integration test scenario I want to override some of the values.
