### ISSUE TITLE
pre-loading with custom path does not working

### ISSUE THREAD

**Issue by PedramMarandi** [motdotla/dotenv#204]
Hello guys, 

I'm loading dotenv with custom path within my running scripts, but I get an error which says 
`Error: Cannot find module '/Users/PedramMarandi/projects/express-mvc/dotenv/config'`

Also here is how my script looks like 
` "run-dev": "nodemon -r dotenv/config ./bin/www dotenv_config_path=./.env --exec babel-node"`

dotenv installed as main dependency    `"dotenv": "^4.0.0"`

Cheers,

**Comment by PedramMarandi** [comment]
I think the is a misunderstanding in document, 
It's written 
`$ node -r dotenv/config your_script.js dotenv_config_path=/custom/path/to/your/env/vars`

But the path does not have any effect on the env variables path,  changing the dotenv/config part of the script solved my issue.

**Comment by maxbeatty** [comment]
Sorry, this looks to be an issue with your nodemon and babel setup and not with dotenv. Check out [this example](https://github.com/motdotla/dotenv/tree/v4.0.0/examples/es6-preload) for guidance. StackOverflow may be a better place to get help debugging this.

**Comment by bluedge** [comment]
Same problem. Such a lazy answer. Not us, the other guy...

**Comment by bluedge** [comment]
Here is how you can do it in your package.json 
```
"scripts": {
    "staging": "nodemon --require dotenv/config app.js dotenv_config_path=.env.staging"
}
```

**Comment by motdotla** [comment]
thanks @bluedge for the example for others.

also, you might prefer [`dotenvx`](https://github.com/dotenvx/dotenvx) for this kind of thing going forward. i recommend it now over preloading.
