### ISSUE TITLE
How to run dotEnv config when there isn't a .env file?

### ISSUE THREAD

**Issue by mjhamm75** [motdotla/dotenv#205]
I have a project that locally has a `.env` file.  When I set up the environment variables on my local machine I use:

    import dotEnv from "dotenv";
    dotEnv.config();
It find the `.env` and loads up all the variables.  When I push the project to Heroku, I don't push up the `.env` file.  I expected `dotEnv` to understand that, but I get this error:

    { Error: ENOENT: no such file or directory, open '.env'
How do I get around that I am not pushing up a `.env` file?  What is the proper way to use `.dotEnv`?

https://stackoverflow.com/q/44608833/968801

**Comment by maxbeatty** [comment]
You can safely ignore this error. It is returned for your convenience in case something isn't working as expected.
