### ISSUE TITLE
Environment not loaded when module is imported

### ISSUE THREAD

**Issue by nareshbhatia** [motdotla/dotenv#206]
According to the docs:
> As early as possible in your application, require and configure dotenv

I am doing that as the very first step in my application:

    require('dotenv').config();
    import OrderService from './OrderService';

However, in the OrderService module when I try to use an environment variable it is undefined:

```
import authService from 'authService';
const authInstance = authService(process.env.API_KEY);

export default class OrderService {
    ...
}
```

I suspect it has something to do with module loading order. Are there any known issues with this? Could it have something to do with `require` vs. ES6 `import`. While I am using `require` to load dotenv, rest of my application is written in ES6 and uses imports. I tried to load dotenv using an import, but that doesn't help.

**Comment by maxbeatty** [comment]
imports are hoisted so order often isn't guaranteed. you might try requiring dotenv via node's CLI ([example](https://github.com/motdotla/dotenv/tree/v4.0.0/examples/es6-preload)). I'll spend some time today updating the docs

**Comment by nareshbhatia** [comment]
Thanks for the clarification, @maxbeatty.

**Comment by gregorip02** [comment]
Import the module as follows to solve this.

```js
import 'dotenv/config';

// Here we can use .env variables in process.env
```

**Comment by dcolley** [comment]
Create a `dotenv.js`
```js
import * as dotenv from 'dotenv'
dotenv.config()
```

In your `index.js`, import `dotenv.js`
```js
// index.js
import './dotenv.js' // <== this import will resolve before the next import is processed
import OrderService from './OrderService';
```

**Comment by tfarhan00** [comment]
> Create a `dotenv.js`
> 
> ```js
> import * as dotenv from 'dotenv'
> dotenv.config()
> ```
> 
> In your `index.js`, import `dotenv.js`
> 
> ```js
> // index.js
> import './dotenv.js' // <== this import will resolve before the next import is processed
> import OrderService from './OrderService';
> ```

Thank you for this!, could you explain me a little bit of what is exactly happening here?
