### ISSUE TITLE
request for option to throw errors

### ISSUE THREAD

**Issue by mjhm** [motdotla/dotenv#209]
I noticed https://github.com/motdotla/dotenv/pull/154 effectively made all errors silent. My preference would generally be to throw on all errors.  So perhaps `.config` could have an error handling option
```
Dotenv.config({errors: ( 'silent'|'log'|'throw') })
```
where `silent` is the default.

**Comment by maxbeatty** [comment]
`config` returns any error so you can handle to your preference

```js
const result = dotenv.config()

if (result.error) {
  throw result.error // or log or ignore
}

console.log(result.parsed)
```
