### ISSUE TITLE
Does it support multiple environment specification in the .env file?

### ISSUE THREAD

**Issue by tannakartikey** [motdotla/dotenv#211]
Hello,

Thanks for the good work first of all.

If we want to declare variables for development, staging, and production environment in the same file; is it possible?

For example,
```
development:
     DB_USERNAME=value
     DB_PASSWORD=value
staging:
     DB_USERNAME=value
     DB_PASSWORD=value
production:
     DB_USERNAME=value
     DB_PASSWORD=value
```

**Comment by maxbeatty** [comment]
No, you should create a `.env` file in each environment. It may be helpful to read [The Twelve-Factor App](https://12factor.net/config) on this topic.

**Comment by tannakartikey** [comment]
Okay. Thanks

**Comment by gkatsanos** [comment]
If that's not possible then I don't see what's the purpose of the .env module. It's just like any other file.
