### ISSUE TITLE
Make dotenv work with PhantomJS?

### ISSUE THREAD

**Issue by redaxmedia** [motdotla/dotenv#212]
Hello,

environment variables in PhantomJS are living under `system.env` instead of `process.env`. Is there a way to make dotenv work with it? I tried to hack / modify the `config` method of dotenv by replacing `process` with `system` but this just does not work.

See: http://phantomjs.org/api/system/property/env.html

Best regards

**Comment by maxbeatty** [comment]
This is a bummer. I think you'd have to majorly rewrite dotenv to work with PhantomJS's custom file system module.
