### ISSUE TITLE
Allow for optional `export` at the beginning of each line

### ISSUE THREAD

**Issue by DesignByOnyx** [motdotla/dotenv#213]
Sometimes it is useful to export the contents of the `.env` file into the current terminal session so that individual scripts can be tested in isolation. The only way it is possible right now is to use a rather convoluted script to read the contents and export them:

```
$ export $(cat .env | grep -v ^# | xargs)
```
It would be nice to allow for an optional `export` word at the beginning of each line:

```
export FOO=bar
```

This would allow users to `source` their environment vars into the current bash/terminal session:

```
source .env
```

**Comment by maxbeatty** [comment]
Discussion in #112 and #118 are still valid to me. Check out [dotenv-export](https://github.com/AndersDJohnson/dotenv-export)

**Comment by sneakertack** [comment]
@DesignByOnyx If this is still bugging you, I recently wrote [nvar](https://github.com/sneakertack/nvar). It works mostly like dotenv, except its syntax follows Shell instead of INI, so things like `export` will work. You may find it to be a better fit for your use case.

**Comment by metaskills** [comment]
Thanks for the nvar recommendation.

**Comment by coolaj86** [comment]
I'm a little confused. Isn't the point of this to follow the dotenv spec as set forth by the [original dotenv](https://github.com/bkeepers/dotenv)?
