### ISSUE TITLE
Last newline is truncated.

### ISSUE THREAD

**Issue by khairulashraff** [motdotla/dotenv#219]
I'm storing my private keys in my `.env` and loading them is missing the final `\n` I stored it with.

Example;
`TEST_KEY="some\nfancy\nconfig\n"`

Result from dumping entire `process.env`:
`TEST_KEY: 'some\nfancy\nconfig'`

**Comment by maxbeatty** [comment]
Most likely same issue as #218 

I'd love to know why storing private keys and certificates in environment variables suddenly became a popular idea.

**Comment by lukecwilliams** [comment]
@khairulashraff If you're looking to convert the \n chars, I posted our solution at https://github.com/motdotla/dotenv/issues/218#issuecomment-325044380.

**Comment by maxbeatty** [comment]
the final newline is being removed because of `trim`. documentation added in #207
