### ISSUE TITLE
Can dotenv throw an error when path is incorrect?

### ISSUE THREAD

**Issue by ClarenceL** [motdotla/dotenv#225]
Rather than writing extra code for all our scripts it'd be great if dotenv would fail if it can't find the env file passed into path option. Or even make this another option, like pathRequired: true to enforce failing in this instance.

**Comment by jcblw** [comment]
@ClarenceL there is a few plugins that do some similar behavior that your looking for in your applications. Could one of these work for your application.

https://github.com/motdotla/dotenv#go-well-with-dotenv

**Comment by ClarenceL** [comment]
Thanks didn't see that, those work perfectly!
