### ISSUE TITLE
Env variables undefined when starting with pm2

### ISSUE THREAD

**Issue by mtnptrsn** [motdotla/dotenv#229]
It seems like dotenv doesn't work when you start it with pm2. Is this a known issue?

**Comment by maxbeatty** [comment]
I have a hunch this is a configuration issue. Try configuring dotenv with an absolute path to your .env file. Alternatively, you can specify environment variables in the pm2 config

**Comment by semiautomatix** [comment]
Absolute path doesn't seem to work.

**Comment by kingjerod** [comment]
This package does work with PM2, I'm doing it in dev right now. Make sure to set `cwd` in the pm2 config to the correct directory for any calls to `dotenv.config()`. 

**Example:**
Your index.js file is in /app/src, your .env file is in /app. Your index.js file has this

`dotenv.config({path: "../.env"});`

Your pm2 json config should have this:
` "cwd": "/app/src", "script": "index.js"`

You could also use `dotenv.config({path: path.join(__dirname, "../.env")});` to avoid the CWD issue. You will still have a problem if you move the .env or the index.js file relative to each other.

**Comment by ritesh-nitw** [comment]
@kingjerod  Won't work in pm2 cluster mode

**Comment by Leland-Kwong** [comment]
Pm2 has its own setup file to inject environment variables. http://pm2.keymetrics.io/docs/usage/environment/

Once you define the environment, dotenv will work as usual.

**Comment by wannymiarelli** [comment]
@Leland-Kwong yes but we use the .env file to not store our variables in code. Doing like this exposes them.

**Comment by jamesdixon** [comment]
@ritesh-nitw did you ever figure this out? Works for me when running `pm2-dev` but not `pm2` in cluster mode.

**Comment by qwang07** [comment]
`dotenv` works when I start the app at first time, but every environment variables in `.env` becomes undefined when I restart app. Any updates?

**Comment by semiautomatix** [comment]
Is the restart occuring in the same folder?

**Comment by danielharrison** [comment]
Looks like if you use a path like this then it doesn't work:

`pm2 start /path/to/myapp/blah.js`

So you need to navigate to the root dir where your file lives and run the command like:

`pm2 start blah.js`

This seems to work correctly for me

**Comment by chovy** [comment]
This does not work for me with pm2@3.x.

I have two apis, each with a root server.js and a root .env. The app works fine with nodemon and proper environment is detected, but with pm2 both apis are sharing one of the .env config files.

**Comment by alanhg** [comment]
> This does not work for me with [pm2@3.x](mailto:pm2@3.x).
> 
> I have two apis, each with a root server.js and a root .env. The app works fine with nodemon and proper environment is detected, but with pm2 both apis are sharing one of the .env config files.

I have same issue

**Comment by alanhg** [comment]
@chovy 
you should add `--env production`, and you can get env variables.

**Comment by stringbeans** [comment]
can confirm this still doesn't work... 

im running: 

```
pm2-runtime --node-args="--require dotenv/config" start process.yml
```

and the apps dont seem to pickup the .env values

**Comment by RNKushwaha022** [comment]
For me this worked-

    pm2 start ecosystem.config.js server.js --node-args="--require dotenv/config" --env production

by using `pm2 ecosystem` one can generate the ecosystem.config.js file

**Comment by FuDesign2008** [comment]
> can confirm this still doesn't work...
> 
> im running:
> 
> ```
> pm2-runtime --node-args="--require dotenv/config" start process.yml
> ```
> 
> and the apps dont seem to pickup the .env values

Putting node-args  config into `ecosystem.config.js` can works, see `node_args` in https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/

**Comment by briantuju** [comment]
Environment variables worked for me when I started pm2 inside the project folder

**Comment by chovy** [comment]
if your'e in docker use `pm2-runtime`

**Comment by VictorLM** [comment]
> Environment variables worked for me when I started pm2 inside the project folder

Worked here when I do the PM2 Start in the same folder of the .env file, using this parameters:
pm2 start src/server.js --name name --node-args="-r dotenv/config"

Thnaks you, man.

**Comment by DewangS** [comment]
Thanks @VictorLM yours is the right answer

**Comment by thanhchuongbmd** [comment]
> > Environment variables worked for me when I started pm2 inside the project folder
> 
> Worked here when I do the PM2 Start in the same folder of the .env file, using this parameters: pm2 start src/server.js --name name --node-args="-r dotenv/config"
> 
> Thnaks you, man.

thanks

**Comment by KirBoy** [comment]
> > Environment variables worked for me when I started pm2 inside the project folder
> 
> Worked here when I do the PM2 Start in the same folder of the .env file, using this parameters: pm2 start src/server.js --name name --node-args="-r dotenv/config"
> 
> Thnaks you, man.

you are life saver <3
--node-args="-r dotenv/config" is the key

**Comment by motdotla** [comment]
these days you can also use dotenvx. you might find it more straightforward. 

https://dotenvx.com/docs/process-managers/pm2

**Comment by anderecc** [comment]
> > Variáveis ​​de ambiente funcionaram para mim quando iniciei o pm2 dentro da pasta do projeto
> 
> Funcionou aqui quando eu faço o PM2 Start na mesma pasta do arquivo .env, usando estes parâmetros: pm2 start src/server.js --name name --node-args="-r dotenv/config"
> 
> Obrigado, cara.

Thanks!!
