### ISSUE TITLE
How to run require('dotenv').config(); before all the other imports

### ISSUE THREAD

**Issue by simibac** [motdotla/dotenv#230]
`require('dotenv').config();`
is on the first line in my app.js file which is called when starting the application. In this file I also import a module (models.js) that connnects to the DB. It seems that the import is run before the require statement since the env-variables are undefined in models.js. 

How can I make sure that 
`require('dotenv').config();`
is before any other code is executed?

**Comment by maxbeatty** [comment]
Hopefully [this section of the README](https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import) fixes your issue. If not, please reopen with more code to demonstrate your problem and setup
