### ISSUE TITLE
Error: ENOENT: no such file or directory, open '.env' runing throught cron

### ISSUE THREAD

**Issue by leocavalcante** [motdotla/dotenv#232]
JavaScript can't find `.env` when running thought a cron job.
Already tried prepending `$HOME/.profile` to the command or using `#!/usr/bin/env bash` at shell script.

Any ideas?

**Comment by maxbeatty** [comment]
Try specifying the absolute path to your `.env` file and work backwards from there. I'm guessing that your cron command is running your script in a way where the working directory isn't what you expect.

**Comment by leocavalcante** [comment]
Yeah, tried `cd /to/my/path` at cron script, but for those who run into this, it only worked when the Node process was at there: `process.chdir(__dirname)`. Thank you anyway.
