### ISSUE TITLE
Windows - Fails due to fs not being found.

### ISSUE THREAD

**Issue by MattLocke** [motdotla/dotenv#234]
ERROR  Failed to compile with 1 errors9:51:08 PM
This dependency was not found:
* fs in ./~/dotenv/lib/main.js
To install it, you can run: npm install --save fs

===============
When trying to run in a Windows environment.  I checked issues log and didn't see any mention of it anywhere.  Hopefully I'm not just wasting your time!

**Comment by maxbeatty** [comment]
[`fs`](http://nodejs.org/api/fs.html#fs_file_system) is a core module of Node.js. I'm guessing you're using dotenv in a browser environment which is not recommended.
