### ISSUE TITLE
Setting NODE_ENV in .env doesn't work when using environment specific .env files

### ISSUE THREAD

**Issue by Ventis** [motdotla/dotenv#24]
This:
```
environment:      process.env.NODE_ENV || "development",
```
in combination with this:
```
_loadEnvDotEnvironment: function() {
      return dotenv._getKeysAndValuesFromEnvFilePath(".env."+dotenv.environment);
}
```
is wrong in my opinion. If I have environment specific variables in my EnvDotEnvironment files and for example set NODE_ENV=production in my general .env file, it will still load .env.development instead of .env.production because it only sets environment once.

**Comment by motdotla** [comment]
closing this. it is no longer relevant to `1.0.0` - which has done away with multiple environment support. `.env` should be isolated to the environment you are working in.
