### ISSUE TITLE
Not able to decode .env file

### ISSUE THREAD

**Issue by nitinsinghit** [motdotla/dotenv#242]
Hi,
I am using the example given in the documentation -` var dotenv = require('dotenv').config({path: '/custom/path/to/your/env/vars', encoding: 'base64'})` I see the `dotenv` has parsed object but I am not to figure out how I can decode thay so I cann access variable from` process.env`. 

Thanks for the help

**Comment by d4nyll** [comment]
I believe this is a bug in the `dotenv` package.

The relevant line is [here](https://github.com/motdotla/dotenv/blob/40e9efcdc5495966d46540fefe786e8d2425b4b1/lib/main.js#L62). It shows that `dotenv` is using Node's `fs.readFileSync` with encoding set to (in your case) `'base64'`. But Node's `fs.readFileSync` behaviour is actually to read the file and then _convert_ it into a `base64`-encoded string (useful for creating base64-encoded images, for example).

For example, if your `.env` contains:

    SOME=VAR

Then the result from `fs.readFileSync` would be `U09NRT1WQVI=`, which is not what you want. I believe what the `dotenv` author actually wants to to read the file first, and then decode it.

**Comment by maxbeatty** [comment]
Can you outline why your file is base64 encoded? There wasn’t much thought put into the documentation example beyond it being something other than utf8
