### ISSUE TITLE
Could you please release 4.0.1?

### ISSUE THREAD

**Issue by shyiko** [motdotla/dotenv#248]
The reason I'm asking is to avoid referencing dotenv@https://github.com/motdotla/dotenv/pull/203 (merged in June) by commit.

**Comment by zenflow** [comment]
That would be a breaking change though wouldn't it? That would mean a major release, i.e. 5.0.0

In any case, might want to hold off on releasing it since it seems that that new feature doesn't work as expected on Windows. See #241

**Comment by shyiko** [comment]
@zenflow interesting. Thanks for the heads up.

**Comment by maxbeatty** [comment]
I have created a project to track progress on this release. It'll be a major version release. https://github.com/motdotla/dotenv/projects/1

**Comment by shyiko** [comment]
@maxbeatty thank you
