### ISSUE TITLE
refresh in visual studio code debug mode

### ISSUE THREAD

**Issue by oussamaABID** [motdotla/dotenv#249]
hi 

not refresh value of **.env.Key** with IDE visual studio code _(debug mode)_ when reload debug
my app.js
`const dotenv = require('dotenv').config();`
my package.js
```
 "dependencies": {
    "@google/maps": "0.4.3",
    //...
  },
  "devDependencies": {
    "dotenv": "4.0.0",
    "eslint": "4.7.0",
   //...
  }
```
my lunch.js
```
{
    "version": "0.2.0",
    "configurations": [

        {
            "env": {
                "NODE_ENV": "development",
                "NODE_CONFIG_DIR": "${workspaceRoot}/config/"
            },
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/src/app.js"
        }
    ]
}
```

**Comment by maxbeatty** [comment]
Sorry, I don’t understand your issue. Can you explain it a bit more?

**Comment by oussamaABID** [comment]
sorry my english is not very good.

i use visual studio code to develop a simple application.
when i change value of my key in .env file :
`GOOGLE_API_KEY=tototototo`
and restart my app, value no change,  like use cache value 

![capture](https://img15.hostingpics.net/pics/150142Capture.jpg)

**Comment by oussamaABID** [comment]
[https://github.com/Microsoft/vscode/issues/14523](solution)

**Comment by oussamaABID** [comment]
[https://github.com/Microsoft/vscode/issues/14523](https://github.com/Microsoft/vscode/issues/14523)
