### ISSUE TITLE
Should I commit my .env file

### ISSUE THREAD

**Issue by maxcc0** [motdotla/dotenv#250]
One quick question here, we work on windows system and use .bat to set our env vars in local windows env.  .bat file is also checked in to version control so that all team members can pull this file and reuse it. I am planning to use dotenv instead of a .bat approach. If i do not commit .env file to source control, how do you recommend the reuse of this file. Thanks!

**Comment by maxbeatty** [comment]
1. You could document development defaults in your README or a wiki that are easy to copy and paste. 
2. You could write a CLI script that prompts a user for values and also provides defaults ultimately writing out a `.env` file. 
3. You could keep a `.env.example` file in source control with development defaults (e.g. `MYSQL_HOST=localhost`) that gets copied or symlinked to `.env`. 

Whatever you do, don't put your sensitive data like production passwords and API keys in source control.
