### ISSUE TITLE
fs.readFileSync is blocking the event loop

### ISSUE THREAD

**Issue by Jakobud** [motdotla/dotenv#252]
Here you are using `fs.readFileSync` instead of `fs.readFile`

https://github.com/motdotla/dotenv/blob/master/lib/main.js#L62

As I have understood how Node.js works in a website environment, using a Synchronous command temporary blocks other requests, even from other clients/visitors. So if you are loading `dotenv` on every single page load for a popular website, that means every time a page loads, then requests for every single other visitor to the website is temporarily blocked. I know it's a very short amount of time, but if you have 1000's of visitors hitting your website all at once, every single one of those requests having a Sync action in them could be a real problem.

http://blog.mixu.net/2011/02/01/understanding-the-node-js-event-loop/

Any thoughts on this? I'm not a Node.js expert and this is simply how I have always interpreted the Sync commands to work in a website (multi-user) project. If anyone could correct me or educate me if I'm wrong I would be interested in hearing it though.

And switching this over to an async statement would be very easy to do.

**Comment by maxbeatty** [comment]
We purposely read the file synchronously so nothing else happens that may depend on an environment variable (e.g. start connecting to a database). You should only run `dotenv.config` once when your process begins and not during each request.

**Comment by Jakobud** [comment]
Ah okay I understand. That makes sense. Thanks,
