### ISSUE TITLE
Use of "#" as a generic comment character as dotenv in php does?

### ISSUE THREAD

**Issue by barlowm** [motdotla/dotenv#253]
In the [PHP dotenv](https://github.com/vlucas/phpdotenv#comments) module, the "#" character can be used as a comment either at the beginning of a line or at the end of a line:

> You can comment your .env file using the # character. E.g.
> ```
> # this is a comment
> VAR="value" # comment
> VAR=value # comment
> ```
Currently, this module only appears to support # at the beginning of a line as a comment.
It DOES, however, support standard comments /* */ at the beginning or end of a line.

Are there any plans to support # for comments either at the beginning or end of a line?

**Comment by maxbeatty** [comment]
Nope. We've explored it in the past and the additional parsing logic didn't outweigh the value of inline comments.

**Comment by jtara1** [comment]
could we get some config property whose value is my function that does the parsing?
