### ISSUE TITLE
Ability to require/include other .env files ?

### ISSUE THREAD

**Issue by fritx** [motdotla/dotenv#256]
```plain
- root
  - env
    - dev.env
    - prod.env
    - prod.secret.env
```

I want to saperate some secrets out to another .env file and gitignore it.
How can I tell prod.env to include prod.secret.env ?

**Comment by maxbeatty** [comment]
You can call `dotenv` twice or however many times you like to set variables from multiple files.

```js
const dotenv = require('dotenv')
dotenv.config({ path: 'prod.env' })
dotenv.config({ path: 'prod.secret.env' })
```

**Comment by fritx** [comment]
But I don't want to change the business logic, any other thoughts?
- Just let the *.env could require each other

**Comment by zenflow** [comment]
@fritx 

>But I don't want to change the business logic

Why not?

**Comment by fritx** [comment]
@zenflow for example, I had a boilerplate of electron+vuejs: https://github.com/fritx/dapp/blob/3e1c9b06c539b46035e2ed5fb082ed2ab0e4f618/package.json#L8

```shell
cp env/prod.env app/dist/.env
```

If I had to modify the business logic, I should change it to be

```shell
cat env/prod*.env >  app/dist/.env
```

which is not good, so that's why I had the question above.

**Comment by mayeaux** [comment]
@maxbeatty will you accept a PR if I write this into the docs? (the fact you can include multiple dotenv files)

**Comment by maxbeatty** [comment]
I think a blog post explaining why (and why not) you might want to do this along with example code would be more effective. There’s only so much you can put in a README before it starts to work against its purpose. A blog post can expand on an idea, provide examples, and is easier to discover.

**Comment by MXTcomunica** [comment]
I use `.env` variables consumed by a `docker-compose.yml` file for my docker environment, so I think I cannot use the suggested solution from maxbeatty more above (https://github.com/motdotla/dotenv/issues/256#issuecomment-359116714).

My `.env` file contains tons of default variables shared by every environment, plus the "secret" variables to be used in different environments, so I experienced the same "tedious manual process to compare and figure out what need to be added or removed in the other enviroments" (cit: https://www.npmjs.com/package/dotenv-extended)

So like Fritx, I really need so put the secrets out to another .env file and gitignore it, to simplify things also with my CI/CD scripts.

Is there a possibility to add this "require/include" feature in .env files?

Thank you very much for considering this.

**Comment by Tofandel** [comment]
> ```
> dotenv.config({ path: 'prod.env' })
> dotenv.config({ path: 'prod.secret.env' })
> ```

This doesn't work for me if both have the variables declared and the second one is supposed to override the values of the other one

**Comment by crux** [comment]
lots of options here, but as I liked none of them for one reason or another I did my own package for that:

https://www.npmjs.com/package/@joe_six/multi-env-cmd

to ad-hoc combine arbitrary .env files from the cmdline and run programs in it:

`$ multi-env .env.sqs.dev .env.db.local .env.saas.staging -- ./bin/app-under-development`

have fun, ymmv

**Comment by vamcs** [comment]
It's possible to set `override: true` so the second env file that is loaded will override existing envs, for example:

```typescript
dotenv.config({
 path: 'original.env',
})

dotenv.config({
 path: 'overrides.env',
 override: true,
})
```
