### ISSUE TITLE
Use dotenv with Jenkins Workflow

### ISSUE THREAD

**Issue by josecolella** [motdotla/dotenv#258]
Hello,
First of all I want to thank you for such a great npm module. Great work. 
I am trying using dotenv in my project and I've come to a roadblock. I am using Jenkins as my CI and I am declaring my environment variables in the Jenkinsfile. When I run tests, my application calls:

`require('dotenv').config()`

and the problem is that it expects a .env file to be present. Though as per security considerations, the .env file is not committed to the repository. Is this case, the environment variables have been set by the Jenkinsfile. My question is how to integrate dotenv with a CI workflow.

Would you have to do something like the following:

```javascript
const dotenv = require('dotenv');

if (process.env.SOME_ENVIRONMENT_VARIABLE_SET_BY_JENKINS === null) {
    const result = dotenv.config()
    if (result.error) {
        throw result.error
    }
    console.log(result.parsed)
}
```

Is there a more elegant solution?

**Comment by maxbeatty** [comment]
I would not change any of your code for CI. Instead, I would configure your CI to populate your environment accordingly ([this might be relevant](https://jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables)). `dotenv` can then fail silently for no .env file being present (totally fine)

**Comment by josecolella** [comment]
@maxbeatty Thanks for your response.
