### ISSUE TITLE
Publish dotenv pre-compiled to ES5

### ISSUE THREAD

**Issue by CarlousF** [motdotla/dotenv#261]
I've been developing a React app using dotenv, with create-react-app, and when it came to building for production, the build failed due to some ES6 code in dotenv:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/dotenv/lib/main.js:23 

Read more here: http://bit.ly/2tRViJ9
```

I've been able to fix this myself by compiling dotenv to ES5 manually, but think it'd be a good idea for dotenv be published to npm pre-compiled to ES5, to prevent other people from running into similar issues in the future.

**Comment by maxbeatty** [comment]
You should not be including dotenv in client bundles as it relies on the file system and populates `process.env` which is a Node.js construct. Instead, it may be useful _during_ the build process as [create-react-app is doing here](https://github.com/facebook/create-react-app/blob/25184c4e91ebabd16fe1cde3d8630830e4a36a01/packages/react-scripts/config/env.js#L44-L46)

**Comment by elie222** [comment]
What about projects that have both a client and server folder in the same repo?

**Comment by zenflow** [comment]
@danielrvoigt @elie222 whether the client and server are in the same repo, or even in the same package (sharing a package.json) makes no difference. Your bundler (webpack if you are using create-react-app) will only pull in the modules that are `import`ed (or `require`d) by your client code. If you have a minimal reproduction I would be happy to take a look at what's going wrong.

**Comment by moparlakci** [comment]
I had this problem also with an outdated Create React App project. Just remove the following from the index.js file. Create React App projects don't include this anymore.

```
import dotenv from 'dotenv';

dotenv.config();
```

**Comment by listatt** [comment]
Make npm install --save @types/node. It works for me.
I have found some node dependencies like 'fs' and others in donenv module.
