### ISSUE TITLE
How can I handle dev and testing environment on a single machine?

### ISSUE THREAD

**Issue by christopher-francisco** [motdotla/dotenv#272]
I want to start by saying "thanks" to the contributors as I think this library is great.

Now, my question is different from #220.

I'm starting on a dummy project, and I want to add some integration testing using https://github.com/visionmedia/supertest.  I will definitely need to load different env variables for the development env, which I access through the browser; and the test env, which mocha runs. Different mongodb urls, Etc.

I'm not talking about committing production/qa envs, but local envs for different environments (I think this are also called "flavors"?)

What approach could I take here?

Also, if this thread becomes useful and informative, I'd like to request for it to be put in the FAQ README section, as I think many people could benefit from it.

Thanks in advance

**Comment by maxbeatty** [comment]
Solving for this is really up to personal preference. 

You could accomplish it via the file system by symlinking files.

```sh
ln -s .env.dev .env
rm .env
ln -s .env.test .env
```

You could conditionally load files based on an _environment variable_.

```js
const dotenv = require("dotenv")

const envFile = process.env.NODE_ENV ? `.env.${process.env.NODE_END}` : '.env'
dotenv.config({ path: envFile })
```

**Comment by chris-fa** [comment]
@maxbeatty This is similar to the approach I had thought before I read your recommendation of not having multiple `.env` files.

**Comment by pennyandsean** [comment]
IMHO the library should do it.

**Comment by gsanikidze** [comment]
In `config` folder I have two files `prod.env` and `dev.env`. I`m Starting `node` with command `ENVIRONMENT=dev node index.js` or `ENVIRONMENT=prod node index.js`. Below is implementation.

---------------------------

`
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path:  path.resolve(__dirname, `../config/${process.env.ENVIRONMENT}.env`)});
`

**Comment by hajimurtaza** [comment]
> In `config` folder I have two files `prod.env` and `dev.env`. I am Starting `node` with the command `ENVIRONMENT=dev node index.js` or `ENVIRONMENT=prod node index.js`. Below is implementation.
> 
> import dotenv from 'dotenv';
> import path from 'path';
> 
> dotenv.config({ path: path.resolve(__dirname, `../config/${process.env.ENVIRONMENT}.env`)});

Getting cant open file error when using ${process.env.ENVIRONMENT}, but when I hard code the filename.env I am able to access the values

![screenshot from 2019-02-19 01-43-50](https://user-images.githubusercontent.com/29270236/52995194-e1c8b580-33e7-11e9-8586-0b535a5cf9b2.png)

**Comment by AdamZaczek** [comment]
> In `config` folder I have two files `prod.env` and `dev.env`. I am Starting `node` with the command `ENVIRONMENT=dev node index.js` or `ENVIRONMENT=prod node index.js`. Below is implementation.
> 
> import dotenv from 'dotenv';
> import path from 'path';
> 
> dotenv.config({ path: path.resolve(__dirname, `../config/${process.env.ENVIRONMENT}.env`)});

The best solution, love it

**Comment by jasonkarns** [comment]
> For people working with Javascript , replace ${variableName} with +variableName followed by 'string'

@hajimurtaza that is javascript, but the blockquote formatting is making the backticks render as `code` instead of leaving them as literals. It should read as:

```js
dotenv.config({ path: path.resolve(__dirname, `../config/${process.env.ENVIRONMENT}.env`)});
```

The backticks are [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by FireWall-e** [comment]
Solutions above didn't work for me. I am using Windows 10. Ended up with creating cli argument parse method, that i gets invoked in the main file (index.js or whatever you like). This solution is universal. I would like to share with you, guys, in case someone has the similar problem. _CommonJS module syntax is used_

**File**: parse-cli.js
**Description**: returns flag value based on the flag name (--[flagName]=[flagValue]), undefined otherwise. It should have **at least** single dash at the beginning.

```
exports.parseCliFlagValue = (flagName) => {
    const flag = process.argv.find(argument => argument.indexOf(`-${flagName}=`) > -1);

    if (flag) {
        return flag.slice(flag.indexOf('=') + 1);
    }

    return undefined;
};

```
**File**: index.js (or whatever your main js file is)
**Description**: includes dotenv config dynamically based on a cli argument passed
```
const {parseCliFlagValue} = require('./utils/parse-cli-flags');
const environment = parseCliFlagValue('env');

require('dotenv').config({path: `src/environments/.env.${environment}`}); // amend the last part in case you have another config name format
```

**Now you can call any of these:**
`nodemon src/server.js --env=dev` // will include dev dotenv config. chiefly used in development mode
**or**
`node src/server.js --env=prod` // for production mode

**Comment by aistyler** [comment]
Yet another option is as follow:

```js
// server.js

process.env.NODE_ENV = process.env.NODE_ENV || "development";
require("dotenv").config({
  path: process.env.NODE_ENV === "production" ? ".env"
  : require("fs").existsSync(`.env.${process.env.NODE_ENV}.local`) 
  ? `.env.${process.env.NODE_ENV}.local` : `.env.${process.env.NODE_ENV}`
});
```
```sh
# .gitignore

.env
*.local
```
```sh
# run in development
node server.js

# run in test
jest 

# run in production
NODE_ENV=production node server.js
```

## Description
- .env (not shared) is used in production mode.
- .env.development(shared) and .env.development.local (not shared) is used in development mode.
- .env.test(shared) and .env.test.local (not shared) is used in test mode.

**Comment by tomerb** [comment]
All the solutions here do not provide an elegant way of avoiding duplicating common variables. e.g.:

common.env:

> COMMON_VAR1=foo
> COMMON_VAR2=bar

dev.env (includes variables from common.env, and extends with):
> DEV_VAR=dev_only

prod.env (includes variables from common.env, and extends with):
> PROD_VAR=prod_only

Anyone has a solution for this?

**Comment by jasonkarns** [comment]
It's been a long time since I've messed with many of the dotenv ports for node. But I have to say I generally consider any package to be deficient if it doesn't support the multiple files per the original rubygem.

https://github.com/bkeepers/dotenv

Iirc, the dotenv port used by CRA does.

**Comment by motdotla** [comment]
@tomerb and @jasonkarns what's your thoughts on using https://github.com/dotenv-org/dotenv-vault on solving this issue?

**Comment by nibblesnbits** [comment]
As a random note, I tend to use [dotenv-flow](https://github.com/kerimdzhanov/dotenv-flow) for this type of scenario.  I do a `dotenv-vault pull [environment_name] .env.[environment_name]` type of command for each env I need, have NODE_ENV set for each environment, and dotenv-flow does the slightly messy bit of loading the correct .env file for me.

**Comment by motdotla** [comment]
The best way to do this now (version 16.1 and greater) is to use a `.env.vault` file.

Here is an example using supertest:

https://github.com/dotenv-org/examples/tree/master/dotenv-supertest

cc @christopher-francisco

**Comment by andremarcondesteixeira** [comment]
@motdotla Allow me to differ. This approach is overly complex for those who don't want to store encrypted environment variables.
