### ISSUE TITLE
How it will work in production.

### ISSUE THREAD

**Issue by venkat-waran** [motdotla/dotenv#277]
I have added the .env in gitignore, Then how it will work in production?

**Comment by maxbeatty** [comment]
That really depends on your production environment 😸 if you are deploying to a managed service ZEIT Now, Apex Up, AWS Elastic Beanstalk, or Heroku, use their built-in environment variable management features. If you're running a VPS, create a `.env` file there. As long as `process.env` is populated, your code will run as expected! 🎉
