### ISSUE TITLE
Multi-line variables with double quotes?

### ISSUE THREAD

**Issue by randallb** [motdotla/dotenv#28]
Is there interest in a PR to support multiple lines when a variable is delimited by quotes?

**Comment by arcseldon** [comment]
Any update on this?

This issue was mysteriously closed - https://github.com/motdotla/dotenv/issues/196
This workaround is definitely not ideal for certs etc 
https://github.com/motdotla/dotenv/blob/v4.0.0/test/.env#L10

Is there a technical impediment preventing its introduction?

**Comment by george-norris-salesforce** [comment]
Wish there was a better solution for this. The \n workaround is not great/

**Comment by markbirbeck** [comment]
Another use case is SQL queries passed in via environment variables. It would be nice to be able to lay them out neatly, too.

**Comment by jorgeorpinel** [comment]
Hi. I this is definitely needed to match Ruby's dotenv standard (https://github.com/bkeepers/dotenv#multi-line-values).

And for me, the `\n` workaround doesn't even work, `\n` is being sent as part of the value... I'm using the latest version, 7.0.0
