### ISSUE TITLE
Add support to .json files

### ISSUE THREAD

**Issue by ErickWendel** [motdotla/dotenv#280]
Add support to .json environment files to use in Lambda Functions, Azure Functions, etc to test local.

**Comment by maxbeatty** [comment]
Sounds like this might be what you're looking for https://github.com/maxbeatty/dotenv-json

**Comment by roydukkey** [comment]
> Sounds like this might be what you're looking for https://github.com/maxbeatty/dotenv-json

@maxbeatty This project is archived.

**Comment by maxbeatty** [comment]
Sure is! If Node or dotenv break, someone can fork it and I'll transfer the npm module (that is [still published](https://www.npmjs.com/package/dotenv-json)).
