### ISSUE TITLE
Drop support for node version 4 and start using ES6 syntax

### ISSUE THREAD

**Issue by zenflow** [motdotla/dotenv#282]
Node version 4 reaches End-Of-Life on 2018-04-30 [(reference)](https://github.com/nodejs/Release#release-schedule)

What about stopping supporting node version 4 when it reaches EOL?

Related to #281

**Comment by maxbeatty** [comment]
Is anyone interested in submitting a PR for this to 🚢 next week? Should only need to adjust `package.json` and CI configs
