### ISSUE TITLE
One confusing sentence in readme

### ISSUE THREAD

**Issue by ZYinMD** [motdotla/dotenv#289]
In your readme (as well as the npm page), it says "Create a .env file in the root directory of your project", this is very misleading. It should have been "Create a .env file in the save directory as your js file". I have sub folders and scripts inside those folders can't access the .env

**Comment by maxbeatty** [comment]
The npm page is populated by the README.md here so any changes will be reflected there with a new release.

Can you expand on your file structure? By default, the module looks for the .env file in the current working directory ([src](https://github.com/motdotla/dotenv/blob/v5.0.1/lib/main.js#L49)). For anyone using npm (or yarn) scripts, this is the root directory of their project (alongside package.json)

**Comment by ZYinMD** [comment]
So for instance, I have .env in my root, inside .env I have `FOO=1`
I also have root/app/app.js, inside app.js I have 
`
require('dotenv').config(); console.log(process.env.FOO);
`
This won't work, unless I move .env into root/app. Am I missing something?

**Comment by maxbeatty** [comment]
Are you running `node app/app.js` or `cd app && node app.js`? Former should work

**Comment by ZYinMD** [comment]
Ah, I see. I was doing the latter. 
I mean eventually in production I'll only run the js file in the root and export js files in the sub folders, but now I'm in development and often run those js files in directly in subfolders for test purposes.

**Comment by ZYinMD** [comment]
By the way, `node app/app.js` is a really bad thing to do, because it'll mess up the relative paths. For instance if I have `var config = require('./config/config.json')` in my app.js, it won't work anymore.

**Comment by maxbeatty** [comment]
`require` does not depend on the process current working directory so it’ll resolve exactly as you expect 😃

**Comment by ZYinMD** [comment]
Yes my bad. require isn't affected, but fs is. These things are so confusing.
