### ISSUE TITLE
dotenv not working

### ISSUE THREAD

**Issue by ngankt2** [motdotla/dotenv#290]
i have 2 file:
file 1: ./bin/www => and i require dotenv in this file
```
    require('dotenv').config();
    console.log('LOGXXX:'+process.env.DB_HOST);//<= it working and value is localhost
    console.log(process.env);// ít working and value is object with multi key, value
    var app = require('../server.bundle.js');
   ......
```

and file 2: ./server.bundle.js 

```
require('dotenv').config();
console.log('LOGXXX:'+process.env.DB_HOST);//<= value is: undefined
console.log(process.env);// value is: {}
```

**Comment by Shaun2D2** [comment]
I might be missing something so please correct me if i'm misunderstanding your problem.

you should not need to require in twice, simply require it into your entry point once and run config and process.env should have your config across your app.

**Comment by ngankt2** [comment]
in file 2  ./server.bundle.js:
case 1:
```
require('dotenv').config();
console.log('LOGXXX:'+process.env.DB_HOST);//<= value is: undefined
console.log(process.env);// value is: {}
```
Case 2: 
```
//require('dotenv').config();
console.log('LOGXXX:'+process.env.DB_HOST);//<= value is: undefined
console.log(process.env);// value is: {}
```
Nothing changes

**Comment by jcblw** [comment]
We need to know more about the environment you are running in. I am very suspicious of the `.bundle` part of you file. I assume there is some static compilation of the these files which is causing these issues.  What are you using to create these `.bundle` files?

Also I think by the name of the file it implies that this is being ran on a server, but I want to reiterate just in case that is not the case that dotenv does not work on clients.

**Comment by maxbeatty** [comment]
This appears to be a local configuration issue and not an issue with dotenv itself. I would suggest inspecting any errors that [`config`](https://github.com/motdotla/dotenv/tree/v5.0.1#config) may be returning.
