### ISSUE TITLE
Environment File Setup

### ISSUE THREAD

**Issue by SheepDomination** [motdotla/dotenv#295]
This extension works on any Environment File (**ENV**), correct ?
If so what is meant by this;

> Dotenv is a zero-dependency module that loads environment variables from a .env file into process.env. Storing configuration in the environment separate from code is based on The Twelve-Factor App methodology.

**Comment by maxbeatty** [comment]
I would encourage you to look at [our examples](https://github.com/motdotla/dotenv/tree/master/examples) and [other projects using dotenv](https://github.com/maxbeatty/example-zeit-now-dotenv) to see how loading environment variables from a .env file works
