### ISSUE TITLE
Feature Request: Conditionals in .env config

### ISSUE THREAD

**Issue by thupi** [motdotla/dotenv#296]
Hi,

I am trying to define api urls based on the stage of the app('prod', 'test', 'dev') :-)

It would be greate to be able to define variables based on other variable. For that i need some way to define conditionals in the .env file. 

I thinks this would add great value for this very easy and standardized solution for environment variables :-)

**Comment by maxbeatty** [comment]
conditions and composition is best left to JavaScript
