### ISSUE TITLE
dotenv library breaks IE11?

### ISSUE THREAD

**Issue by thomastvedt** [motdotla/dotenv#300]
I have a project using create-react-app and typescript (react-scripts-ts). When adding dotenv I get an error in dev mode:
SCRIPT1003: Expected ':'
File: bunde.js, Line: 1558, Column: 65

<img width="758" alt="screen shot 2018-04-19 at 12 54 04" src="https://user-images.githubusercontent.com/4746639/38987642-c30aa5ca-43d0-11e8-8ab3-3ed80f58b3ef.png">

I think this might be because when you bundle dotenv, you probably use a Uglify plugin? 

See this related pull request:

https://github.com/wmonk/create-react-app-typescript/pull/297

**Comment by jcblw** [comment]
I do not think dotenv should be bundled with create-react-app. It was not built to be use on a web client, and for a number of security concerns we do not think all you're env variables should be on the client as well. 

I think the main issue is that this file is being compiled to run on client. dotenv is not planning on supporting browsers as seen in #233 #210 #172 ...

I would see why the `create-react-app-typescript` is including it in the browser. Im pretty sure the plain create-react-app is not doing this behavior.
