### ISSUE TITLE
Support `file://` URLs

### ISSUE THREAD

**Issue by ravinggenius** [motdotla/dotenv#301]
`__dirname` is not available in ES modules, but it can be computed from `import.meta.url`. `import.meta.url` returns a fully qualified URL, including the `file://` scheme. When specifying a custom `path` option, it would be nice to be able to pass the URL in addition to regular paths. This way `__dirname` and `import.meta.url` can both be used with minimal processing at the call site.

**Comment by maxbeatty** [comment]
I'm a bit confused by this request. What version of Node are you using? I'm still seeing [`__dirname` available as a global in newest v10](https://nodejs.org/dist/latest-v10.x/docs/api/globals.html#globals_dirname)

**Comment by ravinggenius** [comment]
Node 10, but the file has to be parsed as an ES module (`.mjs` instead of `.js`, `--experimental-modules` flag). Parsing as a module was supported in Node 9, but Node 10 added support for `import.meta`. When parsing as a module, Node doesn't inject the "magic" globals (`__dirname`, `__filename` et cetera).

SEE https://tc39.github.io/proposal-import-meta/

**Comment by ravinggenius** [comment]
> This way `__dirname` and `import.meta.url` can both be used with minimal processing at the call site.

Just to clarify: `__dirname` can only be used in `.js` files, and `import.meta.url` can only be used in `.mjs` files (with the `--experimental-modules` flag).

**Comment by maxbeatty** [comment]
What would you like changed exactly? Can you provide a reproducible test case?

**Comment by ravinggenius** [comment]
For anyone reading this in the future, I opened a similar issue with Node (https://github.com/nodejs/node/issues/20357). Ultimately it was closed without fixing, as supporting string "URLs" would be a breaking change to the `fs` module.
