### ISSUE TITLE
Trailing Comments are Coming into the Process Environemnt Variables.

### ISSUE THREAD

**Issue by CatGuardian** [motdotla/dotenv#305]
There is an issue with trailing comments.

I'm using Node.js 8.11.1
I'm using dotenv version 5.0.1

Here is my .env file:
```
PORT=3113 # The port to use for this API server
```

Here is my relevant ts code:
```
import * as dotenv from 'dotenv';
dotenv.config();

console.log(process.env.PORT); // Produces "3113 # The port to use for this API server" in the console
```

Problem is that `process.env.PORT` is getting the value `'3113 # The port to use for this API server'`

**Comment by CatGuardian** [comment]
I also switched to `import 'dotenv/config';` and the same thing is happenning.

**Comment by maxbeatty** [comment]
we don't support "inline" comments to cut down on bad parsing situations and stick closer to INI file format. you can use comments like this:

```
# The port to use for this API server
PORT=3113
```
