### ISSUE TITLE
Refer .env.template to check for the validity.

### ISSUE THREAD

**Issue by cytim** [motdotla/dotenv#308]
Hi,

I started to use `dotenv` recently and found that it's really great. I'm thinking if it's possible to integrate validity checking into the library so the application would be guaranteed to get the required environment variables in the desired format.

This will be actually a combination of [dotenv-parse-variables](https://www.npmjs.com/package/dotenv-parse-variables) and [dotenv-safe](https://www.npmjs.com/package/dotenv-safe).

Read the configuration from `.env.template`:

```
FOO=<STRING>
BAR=<BOOLEAN> !# The barry description.
BAZ=[NUMBER](30) !# The bazzy description.
```

Example `.env`:

```
FOO=Hello World
BAR=true
# BAZ is omitted.
```

Example `console.log(process.env)`:

```js
{
  FOO: 'Hello World',
  BAR: true,
  BAZ: 30
}
```

Note that `BAZ` is assigned with a default value.

Assume if `BAR` is missed, an error will be thrown:

```
The required environment variable "BAR" is missing: The barry description.
```

---

If we can agree with the proposal and come up the API, I can create the PR.

**Comment by maxbeatty** [comment]
That's an interesting proposal. Like the two modules you referenced, I would encourage you to build on what `dotenv` and others provide and carve out your own space. Good luck!
