### ISSUE TITLE
Lost (Closed) Issue (Low-Hanging Documentation Fruit)

### ISSUE THREAD

**Issue by machineghost** [motdotla/dotenv#310]
There is an issue which has a healthy amount of interest, but seems to be getting ignored, likely because it's a closed issue.  So, if you haven't already seen it, please re-visit:

https://github.com/motdotla/dotenv/issues/150#issuecomment-387409005

**Comment by maxbeatty** [comment]
Yes, I still get emails about a comment I made 635 days ago. If you have a constructive change to propose to our documentation, please submit a Pull Request. 

If it's more than a sentence or two, I would encourage you to write a blog post to fully express your thoughts.
