### ISSUE TITLE
ENOENT: no such file or directory, open '/<app_path>/.env'

### ISSUE THREAD

**Issue by kodayashi** [motdotla/dotenv#320]
Dotenv throws an error if the `.env` file isn't found. We're deploying via AWS Beanstalk in production and don't want to check in a production.env file to source. Instead, we set all environment variables in the Beanstalk Management Console.

My understanding is that dotenv shouldn't be throwing an error if the file isn't found. I tried the `dotenv.config({ silent: true })` option I found in another older issue but it appears that option is now gone (and is also gone from `@types/dotenv`. From here: https://github.com/motdotla/dotenv/issues/135

What's the recommended approach here? Is it no longer this: https://github.com/motdotla/dotenv/issues/110#issuecomment-160334313

Using `dotenv: 5.0.1`

**Comment by maxbeatty** [comment]
yes, we return the error for when the file is not found. if you're expecting this condition, you can check for it explicitly:

```js
const result = dotenv.config()

if (result.error) {
  if (process.env.NODE_ENV === "production" && result.error.code === "ENOENT") {
    console.info("expected this error because we are in production without a .env file")
  } else {
    throw result.error
  }
}
```
