### ISSUE TITLE
dotenv_config_path=/custom/path/to/your/env/vars via CLI doesn't work

### ISSUE THREAD

**Issue by kodayashi** [motdotla/dotenv#321]
Tried preloading dotenv with `dotenv_config_path=/absolute/path/to/development.env` and the values weren't picked up.

Does this option still work?

**Comment by maxbeatty** [comment]
It should. Can you provide a failing test case or example project that demonstrates it not working?

**Comment by kodayashi** [comment]
Don't have one that I can share ATM, but I was able to work around my issue and don't need this option. When I get some time I can circle back, thanks!

**Comment by lewisblackwood** [comment]
I've noticed this too today. I'll try to put together an example project later today.

**Comment by maxbeatty** [comment]
just tried to [improve the existing test](https://github.com/motdotla/dotenv/pull/325/files#diff-4564ba754e672af58eebf5252897cfa9R19) to make sure this is working. please let us know if there's a certain case that is not working
