### ISSUE TITLE
set NODE_ENV in .env file

### ISSUE THREAD

**Issue by HaoyangFan** [motdotla/dotenv#328]
I have read the previous issue here which mentions that the dotenv won't override the existing environmental variable

So this way to set NODE_ENV won't work:
`.env`

```
NODE_ENV=production
```

`app.js`

```
console.log(app.get('env')); // => development
```

So is there a way for us to set up the NODE_ENV via dotenv instead of explicitly specifying that in the command with `node`?

**Comment by maxbeatty** [comment]
as you know, dotenv will not override existing environment variables. if `NODE_ENV` is not set (default for `node`), you can use dotenv to set it. otherwise, you will need to find another way to set it yourself.

**Comment by joncursi** [comment]
I've gotten around this by unsetting `NODE_ENV` before using `dotenv`, e.g.:

```bash
unset NODE_ENV && dotenv -e .env.production node index.js
```

**Comment by diegocontreras2** [comment]
2023 si se puede

**Comment by motdotla** [comment]
for others coming across i recommend using [`dotenvx`](https://github.com/dotenvx/dotenvx) going forward. it will give you much better logging insight into this AND adds an overload flag. so even if NODE_ENV is set you will be able to override that and inject that into your framework/app's process at runtime.

## quick example:
```
dotenvx run --env-file=.env.production --overload -- node index.js
```

## full example:

```sh
$ export NODE_ENV=staging
$ echo $NODE_ENV
```
```ini
# .env.production
NODE_ENV="production"
HELLO="production"
```
```js
// index.js
console.log('Hello ' + process.env.HELLO)
console.log('NODE_ENV ' + process.env.NODE_ENV)
```

```sh
dotenvx run --env-file=.env.production --overload -- node index.js

[dotenvx@0.10.5] injecting env (2) from .env.production
Hello production
NODE_ENV production
```

with `--debug` flag

```
dotenvx run --env-file=.env.production --overload --debug -- node index.js
process command [node index.js]
options: {"envFile":[".env.production"],"overload":true}
loading env from /your/path/.env.production
{"NODE_ENV":"production","HELLO":"production"}
NODE_ENV set
NODE_ENV set to production
HELLO set
HELLO set to production
[dotenvx@0.10.5] injecting env (2) from .env.production
executing process command [node index.js]
Hello production
NODE_ENV production
```
