### ISSUE TITLE
How to load in start script properly?

### ISSUE THREAD

**Issue by arvi** [motdotla/dotenv#329]
Hello,

So far, I am using `dotenv` via code as one of the very first package to be declared. However, I recently encountered a package where I need to load it just before the `start` script is to be executed so my credentials will not be exposed in my git repository.

I tried to follow the documentation but it seems to not read the `.env`, which is at the root of the folder, same as my `package.json`.

```js
"start":
      "node -r dotenv/config DEBUG=dbg:* cross-env NODE_ENV=dev nodemon bin/dev | pino-cloudwatch --aws_access_key_id=${AWS_CW_AC_ID} --aws_secret_access_key=${AWS_CW_AC_KEY} --aws_region=${AWS_CW_REG} --group=${AWS_CW_LOG_GROUP}",
```

I also tried adding in the `dotenv_config_path` option but it is still not working.

Thanks for the advice.

**Comment by maxbeatty** [comment]
Are you expecting `dotenv` to populate `AWS_CW_AC_ID`, `AWS_CW_AC_KEY`, etc. in your following `pino-cloudwatch` command? If so, that's not going to happen. `dotenv` only populates `process.env` for the current node process which would be `nodemon bin/dev`. _But_ you should double-check that `nodemon` is passing all environment variables through (beyond the scope of this issue)
