### ISSUE TITLE
Using the result of a command to set a variable

### ISSUE THREAD

**Issue by dandv** [motdotla/dotenv#337]
Can we please add to the README an example of how to set a variable to the result of a command? The following work fine in bash, but when I use them in a `.env` file, I get the literal value:

**.env**
```
FOO=$(ls)
BAR=`ls`
```

**index.js**
```js
require('dotenv').config();
console.log(process.env.FOO);  // $ls
console.log(process.env.bar);  // `ls`
```

**Comment by maxbeatty** [comment]
this is the intended behavior. there might be a wrapper module that does interpolation (can't remember off hand). like you mentioned, `bash` is your friend here: `FOO=$(ls) node index.js`
