### ISSUE TITLE
[feat-req] Support for TypeScript Declaration File

### ISSUE THREAD

**Issue by miller-productions** [motdotla/dotenv#343]
### Summary 

Hi there, 

Just started using dotenv, and loving its elegant simplicity.

Was trying it out on a TypeScript-based project and noticed that the latest dotenv version is out of sync with the available @types declaration. 

dotenv currently on v6.1.0
@types/dotenv currently supports dotenv 4.0

Wondering if it is ok to raise a feature request here in the dotenv project to include support for TypeScript Declaration Files?

### Background and Context

- http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
- https://www.npmjs.com/~types
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dotenv

**Comment by maxbeatty** [comment]
Check out #345 It's my first real exploration into TypeScript. If all is good, I can publish v6.2.0 with these new declarations
