### ISSUE TITLE
Question: why are appveyor builds not running anymore?

### ISSUE THREAD

**Issue by amilajack** [motdotla/dotenv#346]
Was this intentional?

**Comment by maxbeatty** [comment]
They are running as of [4 days ago](https://ci.appveyor.com/project/motdotla/dotenv/builds/19796809/job/gchlhppu1j49n923). What made you think they weren't running?

Now that [Travis has a Windows environment](https://docs.travis-ci.com/user/reference/windows/), I'm curious if appveyor is still necessary

**Comment by amilajack** [comment]
Oh that makes sense. The repo badge in the readme is pointing to the wrong repo on appveyor
