### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/.../.env'

### ISSUE THREAD

**Issue by budarin** [motdotla/dotenv#353]
Try to run app with the code 
```js
    const dotenv = require('dotenv');
    const result = dotenv.config();

    if (result.error) {
        throw result.error;
    }
```
and  got the error while in the folder is present `.env.production` and `process.env.NODE_ENV = production`

**Comment by maxbeatty** [comment]
You must specify a custom path to `.env.production`. Defaults are not impacted by other environment variables. 

If you want to use different files based on environment variables, you can dynamically construct a custom path.

**Comment by budarin** [comment]
thanks!
