### ISSUE TITLE
The `debug` option

### ISSUE THREAD

**Issue by kerimdzhanov** [motdotla/dotenv#358]
Hi @motdotla, @marcoow and all the guys who made contributions to this project!

First of all, I would like to say thank you for your great job!

Regarding to the issue, I believe that the new functionality added in #339 (released in v6.2.0) named "`debug` option" is very helpful, but have not obvious name. I mean that "debug" is a lowest level of logging if we consider levels as "fatal", "error", "warning", "info" and the lowest "debug". But the functionality is about syntax checking and exactly "warn" if something is wrong.

And I also think that warnings like this should be enabled by default. The line parsing failures and variable overwritings are potentially cause further errors in our code that might be not obvious, and I would like to see such warnings as soon as possible.

So, summarizing the above, I would like to suggest to turn on the syntax checking and variable overwriting warnings by default and implement option like `silence` (which is `false` by default) that when truthy will muffle this warnings.

As for `debug` option, I expected that it will be something like the outputting some debug information like the full path of the `.env` file that is currently reading, outputting key/values that are successfully parsed and so on...

What do you guys think about this? I would like to send a PR on this if you agree.

**Comment by maxbeatty** [comment]
"debug" was chosen to be in line with the very popular [debug](https://www.npmjs.com/package/debug) package without introducing a dependency

We have received feedback over the years that output by default is not preferred (see the removal of "silent" and then "verbose" options in the changelog). dotenv should "just work" and the API is designed as such. When it doesn't, there are ways to learn more about why it isn't (i.e. inspect returned errors and turn on debugging).
