### ISSUE TITLE
The `debug` option doesn't work as expected

### ISSUE THREAD

**Issue by kerimdzhanov** [motdotla/dotenv#360]
Hi @maxbeatty,

I've found some issues while reading the #339's changes:

If we provide `debug` option as `false` it doesn't work as expected, because of `false != null` [line:78](https://github.com/motdotla/dotenv/pull/339/files#diff-16b7d75b70953cbf4755508170f2f24cR78), and the same for empty string when we use it as `$> DEBUG= node script.js` (unsetting the possibly set value).

And additionally, to be convenient with the "debug" package (as you mentioned in #358), the output should be turned on only when the `DEBUG` environment variable is set to wildcard (`DEBUG=*`) or to the name of the package (`DEBUG=dotenv`) isn't it?

I would like to send a PR for this issue if you agree.

**Comment by maxbeatty** [comment]
The current implementation seems to be meeting people's needs so I'm inclined to keep it as-is.
