### ISSUE TITLE
Can .env file extend another .env file ?

### ISSUE THREAD

**Issue by AndrewChen1982** [motdotla/dotenv#377]
like this:
in my src/tslint.json
{
  "extends": "base-tslint.json", //extends another one
  "no-any": true,
  "prefer-const": false,
}

**Comment by cjaoude** [comment]
actually, i'm curious as to why the answer to this **Should I have multiple .env files?** is **No**. It seems to go against common practice. As devs we need the flexibility of having `env.local`, `env.staging`, etc.

If anyone can elaborate on how else to go about it.

**Comment by zenflow** [comment]
@cjaoude It's in this page linked to from the README: https://12factor.net/config

**Comment by maxbeatty** [comment]
Because dotenv is just assigning keys that don’t already exist in `process.env`, you can just call `config` multiple times.

```js
const dotenv = require(“dotenv”)

[“.env”, “.env.whatever”].forEach(path => dotenv.config({ path }))
```

**Comment by strobox** [comment]
@maxbeatty smart idea. But as not that first files take precedence. My version:
```js
// withEnv.js
const dotenv = require('dotenv');
const fs = require('fs');
const path = require('path');

[ '.env.local','.env.development','.env']
    .forEach(name => fs.existsSync(path.resolve(__dirname,name)) && dotenv.config({ path: name }) );
```
And real usage in package.json:
```json
{
    "start": "node -r ./withEnv  ./node_modules/.bin/react-native start",
}
```
