### ISSUE TITLE
Working with WebPack in npm script

### ISSUE THREAD

**Issue by timbergus** [motdotla/dotenv#379]
Hi there. First of all, this is an amazing tool. Thank you and congrats.

Said that I have a tiny problem using it directly with WebPack. This is my initial script in the `package.json` and it works great:

```JSON
{
    "scripts": {
        "build": "webpack -r dotenv/config"
    }
}
```

But when I try to add a custom config file for a different environment `.env.pr_a`, it just does not work, because WebPack gets the `dotenv_config_path=./.env.pr_a` as the name of the output file :(

```JSON
{
    "scripts": {
        "build:pr_a": "webpack -r dotenv/config dotenv_config_path=./.env.pr_a"
    }
}
```

Is there any cleaner way of doing this? I really need to include the different files for the different environments in the NPM script.

Right now, my only output is a file with this name: `dotenv_config_path.128ea07a8f165bd8f67a.js`.

Thanks in advanced.

**Comment by maxbeatty** [comment]
You should be able to use a [preload environment variable](https://github.com/motdotla/dotenv/blob/v6.2.0/README.md#preload) such as `DOTENV_CONFIG_PATH`:

```bash
DOTENV_CONFIG_PATH=./.env.pr_a webpack -r dotenv/config
```

**Comment by timbergus** [comment]
Thanks a lot! Works great. Now I can have as many environments as I need 😁

```JSON
"build:pr_a": "DOTENV_CONFIG_PATH=./.env.pr_a webpack -r dotenv/config",
"build:pr_b": "DOTENV_CONFIG_PATH=./.env.pr_b webpack -r dotenv/config",
"build:pr_c": "DOTENV_CONFIG_PATH=./.env.pr_c webpack -r dotenv/config",
```
