### ISSUE TITLE
Read host system environment variables?

### ISSUE THREAD

**Issue by spkvn** [motdotla/dotenv#380]
Hi, just a question. 

I've got a situation in which I am running a node app inside a docker container, and the container has a set of environment variables. 

I need to pass the container's environment variables into my application's environment variables, and currently I'm using a small shell script which appends key-value pairs to .env then starts the application.

e.g

```
echo "KEY="$ENV_VALUE >> .env
node app.js
```

Is there a nicer way to do this using dotenv? This feels like a hack.

Thanks

**Comment by maxbeatty** [comment]
[`process.env`](https://nodejs.org/api/process.html#process_process_env) should be populated by your container's environment. 

For example, see [jsperf's Dockerfile](https://github.com/jsperf/jsperf.com/blob/f4643b84ee06bf69d3e06de7e29142771e217865/Dockerfile#L10) exposing `NODE_ENV="production"` which is then [validated in the `envSchema`](https://github.com/jsperf/jsperf.com/blob/261811d8000b4da6c5a26ab1b6d0f4c51bd39195/config.js#L12) before being [used to dictate plugin behavior](https://github.com/jsperf/jsperf.com/blob/261811d8000b4da6c5a26ab1b6d0f4c51bd39195/manifest.js#L38-L39). Sorry it's not easier to follow. If you open an interactive shell with Docker, you should be able to play with the node REPL and inspect `process.env` to verify your variables.

**Comment by spkvn** [comment]
Thanks Max, somehow made it all the way here without knowing that
