### ISSUE TITLE
Environment Not Available in Top Scope

### ISSUE THREAD

**Issue by lucasMontenegro** [motdotla/dotenv#383]
## Description

The environment properties in `process.env` are not loaded with the variables declared in the `.env` file.

This happens when:
1. `.env` is not in the top package folder
2. `dotenv` is being "required" in one file but the env properties are needed in the top scope of another file

## How To Reproduce This Issue

I made a simple example package: [dotenv-issue](https://github.com/lucasMontenegro/dotenv-issue).

#### Clone, install and test example package

``` bash
git clone https://github.com/lucasMontenegro/dotenv-issue.git
cd dotenv-issue
npm install
npm test
```

#### Test results

```
> dotenv-issue@1.0.0 test /tmp/dotenv-issue
> mocha



  Alien Message
    1) Should match


  0 passing (34ms)
  1 failing

  1) Alien Message
       Should match:
     AssertionError: top: expected 'klaatu barada nikto' to equal undefined
      at Context.<anonymous> (test/run-test.js:7:14)



npm ERR! Test failed.  See above for more details.
```

**Comment by maxbeatty** [comment]
Yes, you must require and configure dotenv as early as possible in your application to avoid this. Only then should you expect `process.env` to be populated.

**Comment by lucasMontenegro** [comment]
Found the solution. The problem was that mocha was running every ".js" file under "/test".

I updated my test command to run only files that end with ".test.js":
```
mocha --extension .test.js
```
