### ISSUE TITLE
 The env variables failed to load in debug

### ISSUE THREAD

**Issue by emclab** [motdotla/dotenv#384]
I use dotenv in my nodejs app and the env variables loads successfully with nodemon index.js. However when debug in VS code,, there is nothing loaded. Is it a bug or a problem with the VS code IDE?

**Comment by maxbeatty** [comment]
This sounds outside the scope of dotenv. If you can provide a failing test case, I'd be happy to investigate further.

**Comment by emclab** [comment]
I also posted on VS code to see if this is something related to the IDE. Here is what I did:

1. Click the Debug on Visual Studio Code 
2. Click green to Launch index.js (mine is index.js)

I use console.log to check the value of env variables.  Also you can use `node index.js` to check the env variable in normal development.

A simple nodejs project with index.js will do the test. My nodejs is 10.2.0. dotenv is 7.0.0.

**Comment by tvogel8570** [comment]
This [article ](https://www.freecodecamp.org/news/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a/) has suggestions on how to use .env in vscode debugging.
