### ISSUE TITLE
Clear variable that were set?

### ISSUE THREAD

**Issue by qodesmith** [motdotla/dotenv#388]
Do you think it would be worth adding a feature that can clear variables that were previously set by `dotenv`? If so, I can put together a PR.

**Comment by rodoabad** [comment]
@qodesmith can you give us a walkthrough or workflow how it's gonna know which one has been set by `dotenv`?

I'm thinking of this scenario.

`dotenv` sets NODE_ENV=foo
`cross-env` sets NODE_ENV=bar

**Comment by qodesmith** [comment]
The logic could go something like `dotenv` remembers what value it set, checks if that value is still the case at the time of unsetting, and if it's not it's safe to assume someone else changed it so we'd ignore restoring that value. Did I say that right?

**Comment by rodoabad** [comment]
@qodesmith correct! LGTM.

**Comment by maxbeatty** [comment]
Sounds like you want an enhanced or customized `config` implementation. I'd suggest leveraging our `parse` and developing this logic separately to extend `dotenv`.
