### ISSUE TITLE
Concat 2 variables, concat 1 string and 1 variable ? 

### ISSUE THREAD

**Issue by blyndusk** [motdotla/dotenv#389]
Hi all, 

I'm looking for a way to concat some variables in my `.env` file, for NodeJS use.

```bash
SRC_PATH='./src/'
# maybe like that
SCRIPTS_PATH=$SRC_PATH . 'scripts/'
# or like that
SCRIPTS_PATH=`${SRC_PATH}scripts/`
```

I looked on many github issues & stackoverflow questions, but I found nothing. 

Thanks !

**Comment by jcblw** [comment]
Is there a reason you can not concat the variables in your application?

```javascript
require('dotenv/config')
console.log(`${process.env.SRC_PATH}${process.env.SCRIPTS_DIR}`)
```

**Comment by maxbeatty** [comment]
I believe this is what we call "variable expansion" in the README and [dotenv-expand](https://www.npmjs.com/package/dotenv-expand) exists to solve this ([example](https://github.com/motdotla/dotenv-expand/blob/master/test/.env#L13))

**Comment by blyndusk** [comment]
exactly @maxbeatty , thanks a lot !
