### ISSUE TITLE
Loading multiple env files at once

### ISSUE THREAD

**Issue by mderrick** [motdotla/dotenv#390]
Is is possible/will it be possible to load multiple configs at once?

We *don't* have multiple configs per env but have one `sercets.env` and one `config.env` for various reasons and I need to load them both.

e.g `dotenv_config_path=./config.env,./secret.env`

**Comment by mderrick** [comment]
Note: I've solved this right now by doing the following:

`cat .config.env ./secret.env > ./combined.env && node -r dotenv/config ./index.js dotenv_config_path=./combined.env`

**Comment by maxbeatty** [comment]
This is easy in JavaScript:

```js
const dotenv = require('dotenv')

dotenv.config({ path: './config.env' })
dotenv.config({ path: './secret.env' })
```

If you're trying to do this with preloading, I'd suggest just writing your own preloading script which might just be...

```js
const dotenv = require('dotenv')

(function () {
    dotenv.config({ path: './config.env' })
    dotenv.config({ path: './secret.env' })
})
```

`node -r myConfig`

Making `dotenv_config_path` support a list is going to be more complicated than rolling your own solution (whether that's a bash one-liner or JS).
