### ISSUE TITLE
Please implement simple multi-line values

### ISSUE THREAD

**Issue by jorgeorpinel** [motdotla/dotenv#391]
I.e. reopen https://github.com/motdotla/dotenv/issues/28 please

Should match the Ruby functionality: https://github.com/bkeepers/dotenv#multi-line-values

Thanks

**Comment by maxbeatty** [comment]
Please do not open issues just to ask others to be reopened or reconsidered.

We have no intention of matching functionality (this has been the stance for a very, very long time).

`dotenv` is very stable. The use cases for this feature have not be stated well. Adding this feature would require substantial changes to `parse` which is high risk. High risk changes to stable code for poorly understood use cases is not a recipe for success.

**Comment by jorgeorpinel** [comment]
Boo
