### ISSUE TITLE
Cannot find module: 'dotenv' on linux

### ISSUE THREAD

**Issue by dhowe** [motdotla/dotenv#400]
We have a build that has worked on multiple linux and OS X platforms (netlify, heroku, local, raspberry pi linux, etc/) until we added dotenv. Now, on all platforms (except OS X) we get the following error:

> $ yarn build
> yarn run v1.16.0
> $ react-scripts build
> Creating an optimized production build...
> Failed to compile.
> 
> /home/user/git/spec/shared/user.js
> Cannot find module: 'dotenv'. Make sure this package is installed.
> 
> You can install this package by running: yarn add dotenv.
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by maxbeatty** [comment]
Did you add dotenv as a dependency with yarn?

Closing as this is not an issue with dotenv itself

**Comment by dhowe** [comment]
I did, and I also tried with only npm. We're using dozens of packages, and the only one to have this problem is dotenv, thus the report

**Comment by eufelipemateus** [comment]
Same erro here icn't run in server. i build my project when i put i serve is broken in same error.
