### ISSUE TITLE
Is it more preferable to use process.env.variable or env.parsed.variable?

### ISSUE THREAD

**Issue by dsomel21** [motdotla/dotenv#401]
I prefer writing my ENV variables like this: 

```javascript
var ENV = require('dotenv').config().parsed
console.log(ENV.SECRET_PASSWORD)
```

As opposed to how it is stated in the documentation and many other examples: 

```javascript
var ENV = require('dotenv').config()
console.log(process.env.SECRET_PASSWORD)
```

**Comment by maxbeatty** [comment]
The benefit of using `process.env` is that it is a global variable that can be referenced anywhere in your program/application. Calling dotenv's `config` method multiple times will be less performant but may not be in a measurable way for your application. Do what's best for your situation and preferences (and beware that [`parse` won't exist if an error occurs]( https://github.com/motdotla/dotenv/blob/v8.0.0/lib/main.js#L107)).
