### ISSUE TITLE
Add support for internal variables like ${<here-will-be-diffrent-env-variable>}

### ISSUE THREAD

**Issue by Code-Crash** [motdotla/dotenv#402]
Hello,

I tried to do google and try to find in the document but could not get what I needed, this support is available in `yenv`.

.env file:
`
PORT=8080
API_SERVER=http://127.0.0.1:${PORT}
`
In the above example, 

the API_SERVER should become  http://127.0.0.1:8080 while using process.env.API_SERVER in nodejs server.

I don't know if this feature is supported by `dotenv` package or not, if yes then how we can use this.

Thanks.

**Comment by maxbeatty** [comment]
https://github.com/motdotla/dotenv-expand should do what you're looking for. it's linked to in [our README](https://github.com/motdotla/dotenv/blob/v8.0.0/README.md#what-about-variable-expansion)

**Comment by Code-Crash** [comment]
@maxbeatty Thanks.
