### ISSUE TITLE
Env vars fall out of sync between team members

### ISSUE THREAD

**Issue by tuckerconnelly** [motdotla/dotenv#405]
Common problem: someone adds a new env var that the app depends on, pushes it up, app breaks for everyone else because the config isn't in `.env`.

Similarly, it's easy to forget to add new env vars into staging config (in a Terraform file or Kubernetes config), causing staging to break.

So, necessarily, every time I use `dotenv`, I need to write some kind of script that checks a `.env.example` and makes sure every env var in that in the environment has a value.

Would you consider baking this functionality into dotenv? Or fixing this problem some other way? Happy to submit a PR, or make a blessed ancillary package that solves this.

**Comment by maxbeatty** [comment]
[dotenv-safe](https://www.npmjs.com/package/dotenv-safe) does this and uses dotenv under the hood. there may be others with similar or more advanced functionality. this module is really good at parsing a file, populating `process.env`, and designed to be extended 👍

**Comment by tuckerconnelly** [comment]
Wasn't aware, thank you!
