### ISSUE TITLE
When assigning a var: ReferenceError: Left side of assignment is not a reference.

### ISSUE THREAD

**Issue by orkenstein** [motdotla/dotenv#406]
Whenever I try to assign a var:
```
// Config / .env
require('dotenv').config()
...
process.env.NODE_ENV = 'test';
```
I get:
`ReferenceError: Left side of assignment is not a reference.`
<img width="1093" alt="Screen Shot 2019-06-27 at 19 22 22" src="https://user-images.githubusercontent.com/1461936/60283013-ed396980-9910-11e9-89e1-3bfec6185df8.png">

**Comment by maxbeatty** [comment]
This isn’t an issue with dotenv. My suspicion is that this has something to do with deleting then assigning in your screenshot.

**Comment by orkenstein** [comment]
@maxbeatty yeah, that's `react` issue.
