### ISSUE TITLE
How to use .yml files?

### ISSUE THREAD

**Issue by Syy0n** [motdotla/dotenv#408]
Hey guys, is it possible to use .yml files instead of just .env files? For example:

```
aws:
  any-service:
    ...

azure:
  any-service:
    ...
```

And if yes, is it possible to load/configure only specific blocks from this .yml file, for example based on a provider-name? Maybe only the aws-properties in this case, like:

`dotenv.config(".env.yml.#aws)`

Any help is appreciated, thanks. Maybe this could also be a feature request, if it is not supported at the moment?

I think the dotenv-framework for ruby is capable of doing such things ---> https://github.com/bkeepers/dotenv

**Comment by maxbeatty** [comment]
This module does not support parsing YAML. If you’d like that, I’d suggest building a separate module as a majority of this one wouldn’t be useful (mostly INI parsing logic).
