### ISSUE TITLE
Only get .env value from cmd

### ISSUE THREAD

**Issue by dfsRony** [motdotla/dotenv#410]
I dont understand why but I cant get value from .env file in my root path project using "process.env". It returns:

{NODE_ENV: "development", PUBLIC_URL: ""}

but it works if I set the env value using cmd like this

set "REACT_APP_NOT_SECRET_CODE=abcdef" && yarn start

then when I debug the "process.env" it will return

{NODE_ENV: "development", PUBLIC_URL: "", REACT_APP_NOT_SECRET_CODE: "abcdef"}

it seems like my project not read the .env files, what should I do?

**Comment by maxbeatty** [comment]
I would suggest posting this question to some place like StackOverflow with more details about the setup of your project. Hopefully, it's just a simple configuration issue.
