### ISSUE TITLE
Electron app - windows .exe gives error "Upexpected token" in package.json

### ISSUE THREAD

**Issue by vaishnavravi33** [motdotla/dotenv#411]
I build the package of electron + angular 5 application using electron-builder for windows(.exe). After installation the .exe on windows os and execute it, then throws different - different error each time when we build and install. errors are as below:-

resources\app.asar\node_modules\dotenv\package.json: Unexpected token U in JSON at position 0
resources\app.asar\node_modules\dotenv\package.json: Unexpected token r in JSON at position 0
resources\app.asar\node_modules\dotenv\package.json: Unexpected token e in JSON at position 0
resources\app.asar\node_modules\dotenv\package.json: Unexpected token * in JSON at position 8

But when we run the electron app using "npm start" it is running well. What is the problem after the building of .exe? Is there any solution.

**Comment by maxbeatty** [comment]
I'm unfamiliar with building Electron apps for Windows. This doesn't appear to be an issue with dotenv since `package.json` has to be valid to publish to npm. Perhaps you'd have better luck posting to some place like StackOverflow 😃
