### ISSUE TITLE
How to store "America/El_Salvador" in dotenv?

### ISSUE THREAD

**Issue by fenixsolorzano** [motdotla/dotenv#420]
I've had a bad time figuring out how to store `America/El_Salvador` string into a dotenv variable, your lib needs more documentation on how to store different string formats.

**Comment by maxbeatty** [comment]
There's nothing problematic about that string.

```ini
COUNTRY=America/El_Salvador
```

```js
const dotenv = require("dotenv")

const { parsed, error } = dotenv.config()

console.log(parsed.COUNTRY, process.env.COUNTRY)
```

https://repl.it/@maxbeatty/dotenvissues420
