### ISSUE TITLE
process.env.variable1 is returning undefined

### ISSUE THREAD

**Issue by irtazavolvocars** [motdotla/dotenv#422]
.env file is on  the project root and it contains variable1 with a text
(Total of 3 variables in the file)
to access that variable - we used https://+process.env.variable1+<exampleurl>"

the result gives:
undefined<exampleurl>

**Comment by maxbeatty** [comment]
StackOverflow is a better place to post a question like this. You should start by inspecting the returned error and enabling debugging.
