### ISSUE TITLE
DOTENV_CONFIG_PATH  ignored

### ISSUE THREAD

**Issue by ajmas** [motdotla/dotenv#423]
Support for the `DOTENV_CONFIG_PATH` is provided in `lib/env-options`, but this file is never loaded (validated by placing a console.log in the file). While issue #361 does provide a work around, it seems inconsistent with functionality that appears was intended when looking at the code.

Is `lib/env-options` meant to be used? 

I also notice the entry point, per `package.json`, is `lib/main.js` as opposed to `config.js`, making me wonder what the latter is intended for?

**Comment by ajmas** [comment]
Following up, wondering whether this would be the right 'fix':

 - Add `const envOptions = require('./env-options');` to `lib/main.js`
 - In the `config` function in `lib/main.js` add:

```js
  options = Object.assign(envOptions, options);
```

**Comment by maxbeatty** [comment]
Can you describe how you're using dotenv? Configuration via environment variables is only supported when using `dotenv/config` (usually via preloading). If you're including dotenv in your program, you can explicitly configure via environment variables:

```js
require("dotenv").config({ path: process.env.DOTENV_CONFIG_PATH })
```

**Comment by ajmas** [comment]
I have done as you have suggested fir now, but that leaves  the question as to whether lib/env-options.js is dead code or something that was intended to be used?

**Comment by maxbeatty** [comment]
It's used for `dotenv/config` ([src](https://github.com/motdotla/dotenv/blob/349ff7bbbfafa9b920b0bd174ed03747fd3c8338/config.js#L7))

**Comment by quantuminformation** [comment]
I tried this

`dotenv_config_path=/Users/nikos/WebstormProjects/mentorcv/nikos_admin/.env.staging   node -r dotenv/config --inspect --require ts-node/register src/emailALLUsers.ts `

I can confirm that the `.env.staging` is ignored, and `.env` data. is loaded in my app like this:

![image](https://user-images.githubusercontent.com/216566/98932692-f44e2100-24df-11eb-9f28-fa6b05b3ef41.png)

**Comment by Noitidart** [comment]
> ts-node/register

Did you figure this out? My issue is the ts-node/register is not transpiling. I get:

> SyntaxError: Cannot use import statement outside a module
