### ISSUE TITLE
dotenv and nuxt vue-meta head

### ISSUE THREAD

**Issue by amdp** [motdotla/dotenv#427]
I am using dotenv in a nuxt project where I have to load a paypal script using a dotenv variable:

```
head: {
    title: 'Join or Login',
    script: [
      {
        src:
          'https://www.paypal.com/sdk/js?client-id=' +
          process.env.PAYPALID +
          '&vault=true&currency=EUR&debug=false'
      },
```

the variable has no special chars, just dashes, double dashes ( '--' ) and underscores.
I keep having undefined as per process.env.PAYPALID IN the first call of the script. If I reload the page, the PAYPALID loads correctly. It is the only variable not working in the whole project.
Adding the debug option doesn't seem to report anything, the process.env.DEBUG variable is undefined. Maybe I am not using the debugger correctly. dotenv is loaded in the nuxt.config.js script that has variables in it so it loads correctly, and this is confirmed by the fact the variable PAYPALID is loaded correctly after the reload.
I don't understand what is making the PAYPALID variable undefined, could you auggest me a possible explanation?

**Comment by maxbeatty** [comment]
This is a better question for StackOverflow where there are more nuxt experts. 

process.env.DEBUG does not enable debugging for dotenv and will not be set by us. You need to pass in the debug option (which can be controlled with environment variables). 

Lastly, this client id is not a secret (or sensitive) so you may be better off hard-coding and choosing based on some variable like NODE_ENV or hostname

**Comment by amdp** [comment]
thanks
