### ISSUE TITLE
enable using a function "file" to read file content directly on .env file

### ISSUE THREAD

**Issue by jjangga0214** [motdotla/dotenv#429]
It has been inconvenient specifying very long value which originally should be contained in a file (e.g. private/public keys). There also have been requests for easier multiline use (e.g. #196). 

Therefore I suggest a built-in function, `file`.

```
FOO=foo
BAR=bar
PRIVATE_KEY=file(path/to/file)
```
This would read file content from the given path (argument). 

No more manually making a multiline value to single line, and replacing `\\n` to `\n`.

Maybe we can generalize the idea to enable other functions if desired. For example, special characters indicating a function like `#function#` or `$function$`.

**Comment by maxbeatty** [comment]
Yes, I agree it makes more sense to store (very) long values in separate files instead of manually altering them to a single line in `.env` files. Instead of creating new syntax to be interpreted by dotenv, you could just use Node.js. 

```ini
PRIVATE_KEY_PATH=path/to/file
```

```js
require("dotenv").config()

process.env.PRIVATE_KEY = require("fs").readFileSync(process.env.PRIVATE_KEY_PATH)
```
