### ISSUE TITLE
Typescript issue after upgrading

### ISSUE THREAD

**Issue by iamchathu** [motdotla/dotenv#431]
After updating to `dotenv` 8.2 to new version typescript build getting failed.

```
error TS4090: Conflicting definitions for 'node' found at '/Users/Workspace/porject/@types/node/ts3.2/index.d.ts' and '/Users/Workspace/project/node_modules/@types/express-serve-static-core/node_modules/@types/node/ts3.2/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

2 /// <reference types="node" />
```

**Comment by maxbeatty** [comment]
The types were taken from `@types/dotenv` so there shouldn't have been any behavior changes. 

The paths in your error message don't mention dotenv specifically. Can you reproduce this with another project?

**Comment by iamchathu** [comment]
I tried removing dependency and installing. But still I get same issue

**Comment by motdotla** [comment]
@iamchathu we haven't seen anyone else report this so I am going to close this issue. If you are still having this issue can you let me know and I will investigate further. Maybe you have more information at this point.
