### ISSUE TITLE
Dotenv cut's string with special chars

### ISSUE THREAD

**Issue by carstenbaumhoegger** [motdotla/dotenv#434]
We're using dotenv for some time now and stumbled across the following problem today:

`.env`
```
PASSWORD_HASH=$2y$10$fbdLV2U3Y98LrFYDbn2Fx.d33ubCz.zB6pvhYGKqZcq3HiDOt3USe
```

`process.env.PASSWORD_HASH`
```
.d33ubCz.zB6pvhYGKqZcq3HiDOt3USe
```

Everything that's inside the hashes and appears before the first special char is omitted.

We can only reproduce this problem on our development machines which run macOS. On the servers which run Ubuntu, everything seems to work fine.

We're using dotenv `8.1.0` and node `12.11.0`.

**Comment by aaronbach** [comment]
```
PASSWORD_HASH="$2y$10$fbdLV2U3Y98LrFYDbn2Fx.d33ubCz.zB6pvhYGKqZcq3HiDOt3USe"
PASSWORD_HASH='$2y$10$fbdLV2U3Y98LrFYDbn2Fx.d33ubCz.zB6pvhYGKqZcq3HiDOt3USe'
```

is'nt working either.

**Comment by maxbeatty** [comment]
please reopen if you're able to share a reproduction https://repl.it/@maxbeatty/dotenvissues434

**Comment by aaronbach** [comment]
Here is a reproduction: https://repl.it/repls/ExtralargeHiddenQuadrant

It seems, like the Problem occurs with `require('dotenv').config();`
On MacOS non of the 3 examples passes.

**Comment by carstenbaumhoegger** [comment]
@maxbeatty For some reason I can't reopen this issue.

Please take a look at the reproduction, doesn't work for me either.

**Comment by maxbeatty** [comment]
I've updated [my repl](https://repl.it/@maxbeatty/dotenvissues434) to read a file from disk and see when the value is not wrapped in single quotes that it's being interpreted unexpectedly. My guess is that `$2` there and on your machines is being evaluated by the process/shell. Wrapping your hash values in single quotes looks to fix the problem.

**Comment by carstenbaumhoegger** [comment]
@maxbeatty I just found the issue on our end.

We used `dotenv-cli` and started our dev-backend like this: `dotenv -- nodemon -e ts,graphql -x ts-node src/index.ts`
If you omit `dotenv --`, the hashes get parsed correctly again.

Seems like this messed up the `.env` somehow.

Thanks for your effort!

**Comment by giuliano-december** [comment]
For all of those who are having trouble with this I recommend using [env-cmd](https://www.npmjs.com/package/env-cmd)
