### ISSUE TITLE
How to use with webpack?

### ISSUE THREAD

**Issue by samayo** [motdotla/dotenv#435]
Hello.

I have a very basic webpack setup with just typescript + react support. For now, I have 
```
.env
app.tsx
webpack.config.js
```

The `.env` just contains `GITHUB_URL=https://github.com/samayo`
`app.tsx` is just a simple react "hello world" which outputs `process.env.GITHUB_URL` via console.log
`webpack.config.js` contains the `require('dotenv').config()` code

but, somehow the variable is null. Am I missing some configuration?

**Comment by maxbeatty** [comment]
You'll likely want to use [webpack's `DefinePlugin`](https://webpack.js.org/plugins/environment-plugin/) instead of dotenv

**Comment by 2DSharp** [comment]
@samayo I know it's late but there's https://www.npmjs.com/package/dotenv-webpack that works smoothly with webpack but doesn't seem to have the ability to parse variables from within the file using `${var}` like https://github.com/vlucas/phpdotenv.
