### ISSUE TITLE
Escape of shell special characters does not work properly

### ISSUE THREAD

**Issue by sassman** [motdotla/dotenv#439]
*Given*
```sh
cat .env
FOO=Dollar\$Sign
```
*when*
```sh
source .env
```
*then*
```sh
echo $FOO
Dollar$Sign
```

when you do the same with dotenv then this behaves different:

```javascript
const { config } = require('dotenv');
let vars = config({path: './.env'});
console.log(vars);
{ parsed: { FOO: 'Dollar\\$Sign' } }
```
as you can see `\$` is kept, so the escaping of `$` is not recognised correctly. 
That makes working with passwords quite tricky.

**Comment by Gaetan-LeGac** [comment]
I'm having the same issue

**Comment by motdotla** [comment]
conversation moved here: https://github.com/motdotla/dotenv/issues/521
