### ISSUE TITLE
Order of dotenv loading files / file inheritance

### ISSUE THREAD

**Issue by ggb88** [motdotla/dotenv#442]
Hi,

I use the following line to load a specific app config

`const dotenv = require('dotenv').config({ debug: true, path: path.resolve("${process.cwd()}/config/exports/\", '.env')});`

I had an issue today where an inadvertent file copy/paste went wrong and another completely separate .env file got dropped into the root of my project folder.   My app then failed to run properly.  What I found was that dotenv was reading the .env from the project root _before_ trying to read the specific file in /config/exports.  Is this expected behaviour?

**Comment by motdotla** [comment]
This has been patched up since then. Apologies for the very very late reply, @ggb88.
