### ISSUE TITLE
fails with UTF-16 on windows

### ISSUE THREAD

**Issue by goleary** [motdotla/dotenv#445]
Windows 10 powershell default encoding for `>` (`Out-File`) command is UTF-16

this means if a user uses the following command:
`echo 'TOKEN=23hg523423' > .env`

To create their `.env` file they will end up with a file that is unusuable by this library and all variables in that file will resolve to undefined.

**Comment by AlexanderGranhof** [comment]
Does `dotenv.config({ encoding: "ucs2"})` work for you?

I was reading about nodejs supported encodings [here](https://stackoverflow.com/questions/10940273/how-can-i-read-a-file-encoded-in-utf-16-in-nodejs) and dotenv has a encoding option when its reading the file. `usc2` works for me when testing UTF-16.

**Comment by goleary** [comment]
works for me too
