### ISSUE TITLE
Passing string containing env variables

### ISSUE THREAD

**Issue by atulmy** [motdotla/dotenv#446]
Is it possible to pass a string to the `dotenv.config()` instead of file path for it to parse and give result?

For example:
```
const result = dotenv.config({ contents: 'KEY=VALUE\nPORT=3000' })
```

**Comment by jcblw** [comment]
Yep you will want to use the `parse` method. See the example on the [README](https://github.com/motdotla/dotenv#parse). It does not add it to your `process.env` but should populate the result variable you have.

```javascript
const dotenv = require('dotenv')
const buf = Buffer.from('KEY=VALUE\nPORT=3000')
const config = dotenv.parse(buf) // will return an object
console.log(typeof config, config) // object { KEY: 'VALUE', PORT: '3000'}
````
