### ISSUE TITLE
TypeScript - Dependency Injection Type

### ISSUE THREAD

**Issue by PizzaPokerGuy** [motdotla/dotenv#448]
**Objective**: have a type for the full dotenv package when being used during dependency injection. Example is from a nestjs/node project.

Current Workaround:

`
constructor(private dotenvModule: typeof dotenv = dotenv) {}
`

Preferred: 
`consructor(private dotenvModule: dotenv) {}`

**Comment by jcblw** [comment]
Open to a PR for this, seems like it would only be making a interface for the dotenv that includes: load, config, and parse function types.  Here is the [type definitions](https://github.com/motdotla/dotenv/blob/master/types/index.d.ts)

**Comment by motdotla** [comment]
We will come back to this soon. Moved here: https://github.com/motdotla/dotenv/issues/518
