### ISSUE TITLE
default .env file not loaded on Windows platform (with node-windows)

### ISSUE THREAD

**Issue by DanielRuf** [motdotla/dotenv#451]
In our case we use [`node-windows`](https://www.npmjs.com/package/node-windows) to run a backend service as Windows service which uses the following command under the hood:

```shell
Starting C:\Program Files\nodejs\node.exe  --harmony C:\Users\Administrator\Desktop\node_modules\node-windows\lib\wrapper.js --file 
```

But the values are always `undefined` so it seems it is not correctly loaded.

Related: https://github.com/motdotla/dotenv/issues/367

**Comment by DanielRuf** [comment]
Seems node-windows is the problem. We will probably migrate to pm2.

**Comment by d4nish1234** [comment]
For those who are using [dotenv](https://www.npmjs.com/package/dotenv) package and running into .env not being picked up by the app:

- Ensure you run the service creation script from the root (I don't know if this makes a difference)
- But the main thing is to simply **restart the server or machine** for .env to be picked up.

**Comment by motdotla** [comment]
you can also use dotenvx going forward. it works well anywhere - including windows. 

https://github.com/dotenvx/dotenvx
