### ISSUE TITLE
Tests failing on node 12.16.1

### ISSUE THREAD

**Issue by baob** [motdotla/dotenv#453]
Observed at commit 6e17670d 
MacOs 10.13.6

Tests pass at node 12.14.1, but fail on switching to node 12.16.1
```
Suites:   1 failed, 4 passed, 5 of 5 completed
Asserts:  3 failed, 48 passed, of 51
```

**Comment by motdotla** [comment]
thanks for raising this @baob. PR fix coming here: https://github.com/motdotla/dotenv/pull/515
