### ISSUE TITLE
Q: Is there a way for VS Code Intellisense / JSDoc to know .env variables?

### ISSUE THREAD

**Issue by JL102** [motdotla/dotenv#456]
I have been using .env for some configuration variables, and it helps tremendously. But it's really unfortunate to not have auto-suggestions pop up for these variables that I set. I could have a typo, for example, which goes unnoticed and causes my authentication system to go out of whack.
Is there a way for me to get VS Code's [Intellisense ](https://code.visualstudio.com/docs/editor/intellisense)to be aware of these variable names (And maybe even their values?); so that they can autocomplete, and so I can "intelligently" rename them if/when necessary? (Note; Intellisense uses [JSDoc](https://jsdoc.app/about-configuring-jsdoc.html), but I don't know anything about configuring it.) 

Snippet from `.env` with the variables I wish to show up in IntelliSense
```conf
# Permission tiers
# Standard viewer. Can read reports and upcoming pages.
ACCESS_VIEWER=0
# Team scouter. Can access scouting-related pages.
ACCESS_SCOUTER=1
# Manager of scouters. Can manage pairs, scouting audit, set present, set event, set "current" event, reset passwords, create users, and possibly more.
ACCESS_TEAM_ADMIN=2
# Global Scoutradioz administrator. Not exactly sure what pages will be necessary, but this will involve managing multiple teams and such.
ACCESS_GLOBAL_ADMIN=3
```
Screenshot of Intellisense/JSDoc autocomplete
![Code_2020-03-05_15-07-36](https://user-images.githubusercontent.com/11487870/76021310-132cfa00-5ef3-11ea-9a19-7500e96d2fbd.png)

**Comment by motdotla** [comment]
That would be handy, but I do not think there is a mechanism at the moment. Going ahead and closing.
