### ISSUE TITLE
ENV variables are not considered as string

### ISSUE THREAD

**Issue by Mert1980** [motdotla/dotenv#459]
![Screenshot from 2020-03-18 23-47-58](https://user-images.githubusercontent.com/55088530/77015905-7cdae880-6976-11ea-8521-9e83e3c53404.png)
Shouldn't the default behaviour of node.js is that process.envvariables are always stored and accessed as strings? As seen on the picture, it is not consired as String and I couldn't figure out how to convert it to String. Would u please advise me on that issue?

**Comment by techbless** [comment]
`uri` seems to be `undefined` because an `.env` file is not loaded.   

Have you written `require('dotenv').config()`?   
If you haven't, Add it as early as possible in your code such as a top line of codes.   
   
Check out [here](https://github.com/motdotla/dotenv#config)

**Comment by Mert1980** [comment]
I have written require('dotenv').config() in index.js file, but not in mongoose.js. Should I write in every js  file where I am using a .env variable?

**Comment by techbless** [comment]
No, you don't have to.

Just be sure that `require('dotenv').config()` comes before requiring your `mongoose.js` so that your `.env` is loaded before using `process.env.ATLAS_URI` in your `mongoose.js`.

Give it a try and let me know.

**Comment by Mert1980** [comment]
Yes, it solved the problem! Thank you very much for your kind support
