### ISSUE TITLE
Feature request: detect Windows (CRLF) newlines

### ISSUE THREAD

**Issue by aetonsi** [motdotla/dotenv#461]
#### Problem & how to reproduce
`.env` files created on Windows usually have CRLF (`\r\n`) line endings.
If a file with such line endings is parsed with the debug option set to true, the parser warns about not matching key-value pairs on every **even** line.
This also includes additional non existing lines, because the file is interpreted as having twice the newlines. This means that a "real" warning will have the incorrect line number.

For a practical example, the following file:
```ini
A=1
B=2
C=3
D=
```
gives the following warnings:
```log
[dotenv][DEBUG] did not match key and value when parsing line 2:
[dotenv][DEBUG] did not match key and value when parsing line 4:
[dotenv][DEBUG] did not match key and value when parsing line 6:
[dotenv][DEBUG] did not match key and value when parsing line 7: D
```
because it is interpreted as follows:
```ini
A=1

B=2

C=3

D
```

This doesn't **seem** to create any problem with the parsing, but it's misleading and confusing when trying to debug.

#### Feature requested
Automatically check the line endings before parsing the file.
Another option would be to add a config() option to specify the line endings, but that would be unpractical imho...

<hr>

Have a nice day.

**Comment by aetonsi** [comment]
I forgot to add a consideration:
yes, it would be pretty easy to manually change line endings (if using the proper tools) of the `.env` file, but there might be scenarios where this would be unwanted or not possible (for example, someone might have the git `core.autocrlf` option turned on).

**Comment by paramsiddharth** [comment]
> I forgot to add a consideration:
> yes, it would be pretty easy to manually change line endings (if using the proper tools) of the `.env` file, but there might be scenarios where this would be unwanted or not possible (for example, someone might have the git `core.autocrlf` option turned on).

I agree with you and this is very much needed. Also, even if the support is not agreed upon to be added, I think `dotenv` should at least display a warning for Windows users, making it easier to debug what is wrong. It took me weeks to figure out why it was not working on my system.

**Comment by motdotla** [comment]
Thank you for catching this.

> dotenv should at least display a warning for Windows users, making it easier to debug what is wrong. It took me weeks to figure out why it was not working on my system.

I agree. The last thing we want is dotenv wasting developers' precious time. We want it to speed up your time.

I'm looking into this.

**Comment by motdotla** [comment]
ok, @paramsiddharth and @aetonsi this should be the fix: https://github.com/motdotla/dotenv/pull/523

would you mind testing it on your machines by installing the specific reference to that branch? [1]

[1] https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm#39732501

**Comment by motdotla** [comment]
closing this issue and let's move conversation to the PR https://github.com/motdotla/dotenv/pull/523
