### ISSUE TITLE
Preload (-r command line option )

### ISSUE THREAD

**Issue by raziEiL** [motdotla/dotenv#465]
* **Node.js Version**:v12.16.1
* **OS**:win10
* **Node command line**: `node -r dotenv/config --unhandled-rejections=strict index.js` 

I got UnhandledPromiseRejectionWarning but I want to terminate the node process on unhandled promise rejection. If I remove `-r` option:  `node --unhandled-rejections=strict index.js` everything works as it should. So, how to use `-r` and `--unhandled-rejections` options  together?

**Comment by motdotla** [comment]
@raziEiL could you post a small subset of what you index.js script is doing? Can you post that code?
