### ISSUE TITLE
How I join two variables?

### ISSUE THREAD

**Issue by alexalannunes** [motdotla/dotenv#466]
Example:

`HOST=127.0.0.1`
`PORT=9090`

I tried
`URL=${HOST}:${PORT}`

but 
```javascript
console.log(process.env)
// {URL: "${HOST}:${PORT}"}
```

**Comment by Zjarr** [comment]
Think of a .env file as a plain text file. You cannot do logic with environment variables.

on your JS/TS file:

```js
const { HOST, PORT } = process.env;

console.log(`${HOST}:${PORT}`)
```

That would do the trick.

**Comment by alexalannunes** [comment]
I think this is the only way :( @Zjarr

**Comment by netojose** [comment]
Nice feature, I would like do this.
I used PHP a lot of time, and on the official dotenv PHP package, [this is possible](https://github.com/vlucas/phpdotenv#nesting-variables)

**Comment by zenflow** [comment]
This package doesn't provide many features, so there's a large ecosystem of packages that add features. 

I believe [dotenv-expand](https://github.com/motdotla/dotenv-expand) does what y'all want. 

Thankfully I'm using [dotenv-cli](https://github.com/entropitor/dotenv-cli) which includes it by default, so I don't need to install the extra package and set it up to get this feature.
