### ISSUE TITLE
Process cannot find .env variables

### ISSUE THREAD

**Issue by chiq2045** [motdotla/dotenv#467]
dotenv is not discovering any env variables in my running processes. Here is an application that I am having trouble with:
```javascript
require('dotenv').config();

const Koa = require('koa');
const mount = require('koa-mount');
const logger = require('koa-logger');

const api = new Koa();
const paint = require('./apps/paint.js');
const { PORT } = process.env;

api.use(logger());

api.use(mount('/paint', paint));

api.listen(PORT, () => {
  console.log(`Listening at port ${PORT}\nCan be found externally at https://example.com/api`);
});
```
The application above gives the following response, and does not listen to the set port:
```
Listening at port undefined
Can be found externally at https://example.com/api
```
However, when i manually give `PORT` a value, i.e. `5000`, it gives the wanted response, and listens to the port:
```
Listening at port 5000
Can be found externally at https://example.com/api
```
Here are the relevant parts of my package.json:
```javascript
  "dependencies": {
    "@koa/cors": "^3.0.0",
    "@koa/multer": "^2.0.2",
    "@koa/router": "^8.0.8",
    "@tadashi/koa-jwt-authz": "^1.0.0",
    "dotenv": "^8.2.0",
    "jwks-rsa": "^1.8.0",
    "koa": "^2.11.0",
    "koa-body": "^4.1.1",
    "koa-jwt": "^3.6.0",
    "koa-logger": "^3.2.1",
    "koa-mount": "^4.0.0",
    "koa-static": "^5.0.0",
    "multer": "^1.4.2"
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-config-koa": "^2.0.2",
    "eslint-config-standard": "^14.1.1",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1"
  }
```

**Comment by alexalannunes** [comment]
how is your .env file?

**Comment by chiq2045** [comment]
My .env file is in the application root directory. Following are the relevant lines from the file:
```javascript
NODE_ENV=development
PORT=5000
...
```

**Comment by alexalannunes** [comment]
really... is correct.
could you share with me your repository for me to test here on my machine?

**Comment by chiq2045** [comment]
https://github.com/chiq2045/api

**Comment by joaoliveirajs** [comment]
I am getting this same problem.

Error: 

src/index.ts:3:23 - error TS2532: Object is possibly 'undefined'.
const port: number = +process.env.PORT || 3333;

**Comment by jcblw** [comment]
@chiq2045 you will want you `.env` file to be at the root of the process you are running if you want it to automatically parse the file. [process.cwd](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L78) is what we use to find the `.env` file. 

If you need to use the file in your API directory you will need to [configure the path](https://github.com/motdotla/dotenv#path) the the `.env` file.

Let me know if this helps.

**Comment by chiq2045** [comment]
I'm not sure what has changed over the last few days, but now it is working. I have not made any changes on my end. @joaoliveirajs are things working for you now?

Also, @jcblw, api directory is the root directory, and that is also what `process.cwd` returns.

**Comment by alexalannunes** [comment]
@chiq2045 

Great! :smile: 

Here it works too
---------
![image](https://user-images.githubusercontent.com/16847836/80293431-bbae4c00-8735-11ea-83fb-0c5e1c19a89a.png)

**Comment by gnorbsl** [comment]
I have the same issue:

```
├── app.js
├── bin
│   └── www
├── .env
├── package.json
├── package-lock.json
└── routes
    ├── index.js
    └── users.js
```
```
{
  "name": "testproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "dotenv": "^8.2.0",
    "express": "~4.16.1"
  }
}
```
```
$ cat .env 
PORT=3000
```

```
const dotenv = require('dotenv').config()

console.log('process.env.PORT is ' + process.env.PORT)
```


`process.env.PORT` is undefined

**Comment by jcblw** [comment]
awesome great to hear! @joaoliveirajs let me know if you are still having issues. Closing for now.

**Comment by chiq2045** [comment]
I just wanted to add an addendum. It seems that the problem that I am experiencing is related to #229.
