### ISSUE TITLE
Correct way to use inside CI environment

### ISSUE THREAD

**Issue by xerosanyam** [motdotla/dotenv#469]
Hi, I read a lot of comments saying that one should not commit `.env` files.
That is understandable. But what is the correct way to load them inside the CI environment? (Say Github actions)
Any pointers would be highly appreciated, thanks!

**Comment by jcblw** [comment]
Hey there @xerosanyam sorry for the late reply. `dotenv` helps you emulate environment variables, and when you are able to set them directly for a specific environment that is recommended. This way you do not need to store those secrets inside your codebase. 

For Github actions, you are able to [set those values directly](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables). Closing the issue for now but feel free to reply with more questions.
