### ISSUE TITLE
.env and .env.environment both required?

### ISSUE THREAD

**Issue by danawoodman** [motdotla/dotenv#47]
Why are both a `.env` and a `.env.ENVIRONMENT` required? Shouldn't just a `.env` file be necessary?

Also, this isn't clear in the README that this is the behavior and threw me for a loop.

To me, this should be a `||` not a `&&`: https://github.com/motdotla/dotenv/blob/master/lib/main.js#L101

**Comment by jcblw** [comment]
hmm I see the issue, I think you are correct.

**Comment by jcblw** [comment]
@motdotla @maxbeatty  we probably should fix this soon, I can get at it after work. It probably is stopping projects from loading proper vars.

**Comment by maxbeatty** [comment]
Absolutely agree you should not be required to have a `.env.ENVIRONMENT` file

If we change that to "or", is it acceptable that the `.env` file could have not been read but `.env.ENVIRONMENT` has been read? I want to fix this without backing out the intent of #43

**Comment by jcblw** [comment]
@danawoodman if you install the new patch it should not require the environment file

**Comment by heitortsergent** [comment]
:+1:

**Comment by danawoodman** [comment]
Awesome! Thanks for the quick work on this! :+1:
