### ISSUE TITLE
Cannot access variables using syntax process.env.VAR_NAME. React Native / Jest.

### ISSUE THREAD

**Issue by curiousdustin** [motdotla/dotenv#471]
What would cause the inability to access variables using the syntax `process.env.VAR_NAME`?

I can see that the keys are indeed being created in process.env, I just cannot access them like this.

Here is some code to illustrate my issue:

```js
const dotenv = require('dotenv');
const result = dotenv.config();
if (result.error) {
  throw result.error;
}

const varName = 'VAR_NAME';
console.log(`VAR_NAME: ${process.env[varName]}`);
console.log(`VAR_NAME: ${process.env.VAR_NAME}`);
/**
 * VAR_NAME: valueFromENVFile
 * VAR_NAME: undefined
 */
```

I am using this in a React Native project Jest setup file.

```
"dotenv": "^8.2.0"

node -v
v13.12.0
```

**Comment by jcblw** [comment]
Hey there @curiousdustin 

I just tested this locally, and everything works as expected.

```js
// test.js
const name = 'VAR_NAME'
console.log(`Hello ${process.env.VAR_NAME}, and ${process.env[name]}!`)
```
then running this equals.
```sh
$ node -r dotenv/config test.js                                                                                               
Hello foo, and foo!
```

I assume this may be another library within your toolchain that is causing this issue. I assume there is some build process that is injecting these values into your application. Let me know if you find out anything that may be doing this.

**Comment by curiousdustin** [comment]
I have inherited this project so I am figuring it out as I go.

Does this snippet from my package.json provide any clues?

```json
"jest": {
    "preset": "react-native",
    "globalSetup": "./testing/jestSetup.js",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|react-navigation-tabs)"
    ],
    "setupFilesAfterEnv": [
      "jest-extended"
    ]
  },
```

**Comment by curiousdustin** [comment]
My `jestSetup.js` has a bunch more in it, but these are the first few lines:

```js
#!/usr/bin/env node
const dotenv = require('dotenv');
const result = dotenv.config();
if (result.error) {
  throw result.error;
}

const name = 'VAR_NAME';
console.log(`Hello ${process.env.VAR_NAME}, and ${process.env[name]}!`);
```

Which logs:
```
Hello undefined, and foo!
```

**Comment by jcblw** [comment]
Hey there, not sure if this is resolved or not but it does seem like this is something that is happening outside of this library. Feel free to still comment on the ticket but I am going to close this ticket.

**Comment by curiousdustin** [comment]
I'm not entirely sure why, but if I remove this line the process.env properties starts working as expected.

```json
"transform": {
  "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
},
```
