### ISSUE TITLE
environment variables not loaded when pm2 cluster mode

### ISSUE THREAD

**Issue by adriano-di-giovanni** [motdotla/dotenv#472]
Environment variables aren't loaded when the app is started in cluster mode using pm2 and the .env file is located elsewhere.

The `DOTENV_CONFIG_DEBUG` and `DOTENV_CONFIG_PATH` variables are correctly loaded into each worker's `process.env`.

Everything works fine in cluster mode when the .env file lives in its canonical location.

```javascript
module.exports = {
  apps: [
    {
      // relevant attributes only
      exec_mode: 'cluster',
      node_args: '--require dotenv/config',
      script: './index.js',
      env: {
        NODE_ENV: 'development',
      },
      env_development: {
        DOTENV_CONFIG_DEBUG: true,
        DOTENV_CONFIG_PATH: '/path/to/.env',
      }
    }
  ],
  deploy: {
    development: {
      // relevant attributes only
      'post-deploy': 'npm install && pm2 startOrRestart ecosystem.config.js --env development,
    },
  }
}
```

pm2 4.4.0
dotenv 8.2.0

**Comment by sukanta-manna** [comment]
I could successfully load environment variables when PM2 in cluster mode, keeping .env in root as well as in different path using 
const r = require('dotenv');
r.config({path: __dirname + '/config/.env'});

**Comment by wujingquan** [comment]
We have the same problem.

**Comment by motdotla** [comment]
@wujingquan and @adriano-di-giovanni what sort of feedback do you get from having DEBUG turned on? Are you getting any feedback at all - if not, I wonder if somehow the `DOTENV_CONFIG_PATH` is not being respected.

**Comment by motdotla** [comment]
I haven't been able to duplicate this. The `debug` option is now more verbose. Try with that.
