### ISSUE TITLE
Does not work on WSL Ubuntu 16 

### ISSUE THREAD

**Issue by mvpatel2000** [motdotla/dotenv#479]
I am working on a project that uses dotenv to control environment variables for nodejs. In general, it works fantastic but for some reason process.env.VARNAME is always undefined when running under Windows Subsystem Linux Ubuntu 16. Is there anything I can look for why dotenv wouldn't work under these conditions? I can provide more environment information too -- I wasn't able to find a report template.

**Comment by motdotla** [comment]
can you provide more details? what does your code look like, etc? I'll close the issue for now, but re-open when you get some time to send that over.
