### ISSUE TITLE
Incorrect main file?

### ISSUE THREAD

**Issue by four43** [motdotla/dotenv#482]
It seems the main is set incorrectly: https://github.com/motdotla/dotenv/blob/master/package.json#L5 (should be `./config.js` ?)

This doesn't allow config options to be set via env vars like `DOTENV_CONFIG_PATH`.

I was running something like:
```
import * as dotenv from 'dotenv';

const dotenvConfigLoadRes = dotenv.config();
if (dotenvConfigLoadRes.error) {
    throw dotenvConfigLoadRes.error
}
```
In a typescript file which is another layer of mess, understandably. 

I could also just be doing this terribly wrong. 

Thanks

**Comment by motdotla** [comment]
We're you able to get this going @four43? the lib/main.js is definitely the entry point for the library.
