### ISSUE TITLE
Provide a global binary which can load .env into the current shell environment.

### ISSUE THREAD

**Issue by liudonghua123** [motdotla/dotenv#488]
I want to load the environment variables from a `.env` file into the current shell. From the docs, I could not find how can I achieve it. If this package could provide a global binary like `dotenv` then I can execute it like `dotenv --dotenv_config_path=.env`.

**Comment by zenflow** [comment]
https://github.com/entropitor/dotenv-cli

**Comment by liudonghua123** [comment]
@zenflow Maybe this feature would be impossible to implement. The closest way to achieve this feature would create a new child process, and pass the envs into it. 

You can also execute `source .env` directly in Unix/Linux or generate a temp bat file which contains a batch of set command, invoke it If you are using Windows cmd.

See more details in the following references.
- https://unix.stackexchange.com/questions/372627/is-it-possible-to-pass-environment-variables-from-child-to-parent-in-user-space.
- https://github.com/dkundel/node-env-run/issues/19

**Comment by motdotla** [comment]
Thanks for the thoughts here @liudonghua123. I'm going to go ahead and close this. If others take an interest in this beyond dotenv-cli, then it will be something we consider.
