### ISSUE TITLE
Feature: Extending .env files

### ISSUE THREAD

**Issue by shellscape** [motdotla/dotenv#489]
## Proposal

I'd like to propose a method by which `.env` files can "extend" or "inherit" from a base `.env` file located on the filesystem. This is a pattern found often in tooling such as [TypeScript's `tsconfig`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases), [ESLint](https://eslint.org/docs/developer-guide/shareable-configs#using-a-shareable-config), and even `TSLint` [in this repo](https://github.com/motdotla/dotenv/blob/75986d3d8bdaf6bd92bf34efae08ae5db936a748/types/tslint.json#L2).

### Semantics

```bash
# extends: .env.base

SOME_VALUE=batman
```

## Use Case

Code-duplication is one of the battles that maintainers and contributors to large monorepos are constantly waging. In monorepos for microservices or other forms of apps, it's very common to see the following in a directory tree:

```
.env
.env.dev
.env.local
.env.stage
```

Where each file contains roughly the same information, somethings with minor modifications. This is especially prevalent with microservice monorepos leveraging `serverless` and `serverless-offline`. In most cases, the repeated set of data contains things like keys and tokens, and baseline or default data that'll be pulled from external sources like SSM, Redis, etc one deployed. It's common to see deploy-target-specific `.env` files as well.

This proposal is centered around allowing for a single source-of-truth at a root filesystem location (e.g. a monorepo root) containing _most_ default data needed. 

## Behavior

Consider this "base" file: _`.env.base`_

```bash
AUTH0_TOKEN=robin
OKTA_TOKEN=batman
SSM_PREFIX=joker
```

And this local _`.env.local`_ file, which extends `.env.base`

```bash
# extends: .env.base

DEPLOY_FRIDAY=true
```

At this point, `process.env` would contain; AUTH0_TOKEN, OKTA_TOKEN, SSM_PREFIX, and DEPLOY_FRIDAY. Say we needed a file for a staging environment that needed a slight modification to the default values, _`env.stage`_:

```bash
# extends: .env.base

SSM_PREFIX=stage
```

And `process.env` would contain all values from `.env.base`, but with `SSM_PREFIX` equal to `stage`, overriding the default value of `joker`.

### Calling Multiple Times
As @maxbeatty pointed out in https://github.com/motdotla/dotenv/issues/377#issuecomment-464411650, one could author a utility method to be shared in the environment that calls multiple times:

```js
const dotenv = require(“dotenv”);

[“.env”, “.env.whatever”].forEach(path => dotenv.config({ path }));
```

This is certainly valid for small projects.

### Pitfall

The pitfall with this approach are projects which leverage `dotenv` to automatically load and spin up a particular environment, such as [`serverless-plugin-dotenv`](https://www.serverless.com/plugins/serverless-dotenv-plugin) ([npm link](https://www.npmjs.com/package/serverless-dotenv-plugin)). Any consumer of `dotenv` that is prepackaged would need to modify their behavior to take advantage of extending other .env files. That would create fragmentation in the expected use from one environment to another.

## Argument For

I suggest that the value that this proposal would give to the community and userbase at large outweighs the code footprint and maintenance burden incurred by its addition. While small projects may not need this functionality, larger projects and specifically monorepos, are becoming more and more commonplace with companies such as Microsoft operating within monorepos almost exclusively. This would greatly reduce code duplication and be a large, further improvement to the developer experience.

**Comment by wesleygrimes** [comment]
I like this idea a lot at first glance. Need to dig in further but thumbs up!

**Comment by jamonholmgren** [comment]
I’d be on board. 👍

**Comment by Vanuan** [comment]
Coming from `create-react-app`, I'm surprised this is not implemented:
https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used

Is there any overlap between `react-scripts` and `dotenv` whatsoever?

**Comment by ypicard** [comment]
This feature would be fantastic. Are there any interesting updates the community should be aware of?

**Comment by motdotla** [comment]
Thank you for the thoughtful issue here. A lot of it makes sense but we are not going to do it as core functionality to dotenv. We strive to keep this repo very simple to use.

Instead, we're hoping to extend this functionality into expansion modules. In the meantime, you can also check out https://github.com/dotenv-org/cli which will eventually add a feature to quickly switch between environments locally.

**Comment by shellscape** [comment]
lol my dude when we passed an entire year without comment from a single maintainer we gave up any hope and moved on from the project.   a 502 day delay in issue response is hilariously poor response time, even for a popular project.

**Comment by motdotla** [comment]
@shellscape sincere apologies for that. I totally understand.

For anyone who comes across this thread in the future, you can now your the `@dotenv/cli` https://github.com/dotenv-org/cli to store and pull specific environments. Example:

```
$ dotenv-cli pull staging
$ dotenv-cli pull production .env
```
