### ISSUE TITLE
error: Error: ENOENT: no such file or directory, open '../.env'

### ISSUE THREAD

**Issue by akashgp09** [motdotla/dotenv#491]
### My working Directory :
<img src="https://i.imgur.com/QVWWyIb.png" height=300px width=250px>

- **In server.js file:**

```
require("dotenv").config({ path: "../.env" });
console.log(process.env.DB_MONGO_URI); // undefined
```
dotenv is unable to locate my `.env`  file.
@maxbeatty What am i doing wrong ?

**Comment by jehincastic** [comment]
@akashgp09 The path you have set is a Relative path to the ENV file. Dotenv uses fs to read the file from the path. So according to node [documentation ](https://nodejs.org/api/fs.html#fs_file_paths)**Relative paths will be resolved relative to the current working directory as determined by calling process.cwd()**. So your code should be

**require("dotenv").config({ path: "./.env" });**
