### ISSUE TITLE
Error with Mongoose: "uri parameter to openUri() must be a string"

### ISSUE THREAD

**Issue by oxk4r01** [motdotla/dotenv#500]
![image](https://user-images.githubusercontent.com/1032224/103151587-9750b680-477f-11eb-86fe-fca54c94cacf.png)

![image](https://user-images.githubusercontent.com/1032224/103151538-26a99a00-477f-11eb-8ea2-6d5d2ce28ec3.png)

I goth this error:
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

Moreover, I cant see dotenv in my package.json. I don't know if that's normal or not.
![image](https://user-images.githubusercontent.com/1032224/103151620-ee568b80-477f-11eb-9e84-376e97bcbb73.png)

**Comment by phamleduy04** [comment]
`dotenv` should be config() 

Refer to the docs:
```js
require('dotenv').config()
```

**Comment by motdotla** [comment]
hi @oxk4r01 were you able to get this solved? this looks like probably a configuration bug on your project side rather than dotenv.

**Comment by akshatkumawat** [comment]
This is still a problem.
i can access env variables in app.js
but not in other class that have database config. there vars are undefined.
