### ISSUE TITLE
Dotenv is not loading! 

### ISSUE THREAD

**Issue by fast-and-curious-1910** [motdotla/dotenv#501]
So basically I am in a code jam , and our .env file just stopped working. It was working last night and now it just stopped.

I am also using create-react-app.

code is the following 

```js
import { config } from 'dotenv'
config()
var authToken = process.env.AUTH_TOKEN
```

While my dotenv ``.env`` looks like
```
AUTH_TOKEN=MYTOKEN
````

**Comment by RA80533** [comment]
Turn on debug mode via `config({ debug: true })` and see if anything is printed out.

That being said, I believe create-react-app handles environment variables a little bit differently. There should be built-in support for them but you have to prefix your would-be environment variables with `REACT_APP_` in order to access them in your application.

**Comment by binarymist** [comment]
How do you do this using the preload technique?
`node -r dotenv/config app.js`

**Comment by RA80533** [comment]
Pass along the `DEBUG` environment variable like so:

```console
$ DEBUG=true node -r dotenv/config app.js
[…]
```

**Comment by binarymist** [comment]
Yeah, got that sorted (my failure to RTFM). To turn debug on, details [here](https://github.com/motdotla/dotenv#preload):

```
node -r dotenv/config app.js dotenv_config_debug=true
```

Turns out dotenv can't override env vars that already exist (using the preload technique), which is exactly what we were trying to to, so dotenv won't work for us.

**Comment by motdotla** [comment]
@binarymist yes, that is correct. we will reconsider the ability to override variables. for now you could add this into your script but I realize it's not ideal:

https://github.com/motdotla/dotenv#what-happens-to-environment-variables-that-were-already-set
