### ISSUE TITLE
What is the default path for node -r dotenv/config xx.js

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [motdotla/dotenv#502]
I'm moving from require in code to node -r dotenv/config but I don't know what's happen on my project.

OS: `Mac OS`

config/
-- | dev.env
-- | prod.env
src/
-- | app.js

when I run with

```ENVIRONMENT=prod node -r dotenv/config src/app.js```

It' work!!! (loaded prod.env)

and

```ENVIRONMENT=dev node -r dotenv/config src/app.js```

It's also work!!! (loaded dev.env)

So amazing.
Is it a magic?

**Comment by Cyl3el2Cleal2** [comment]
New problem with same folder stucture.

On Windows Server.

above structure doesn't work.

I must move and rename setting file to .env at root project directory like this.

config/
-- | dev.env
-- | prod.env
src/
-- | app.js
.env

**Comment by binarymist** [comment]
We're getting the same, but on Linux. `dotenv/config` simply isn't working.

**Comment by motdotla** [comment]
have you tried passing the full path to `-r`?

so something like: `node -r /Users/yourUser/code/yourRepo/path/config src/app.js`

**Comment by motdotla** [comment]
@binarymist what node version are you running?

(marking this closed to start clearing out some issues, but i will re-open based on response)

**Comment by binarymist** [comment]
From memory this was a failure on my part [to RTFM](https://github.com/motdotla/dotenv/issues/501). Have now moved on, dotenv doesn't support our use case.

Thanks.
