### ISSUE TITLE
On a Windows machine, creating an .env parameter named USERNAME will leave the machine environment name set.

### ISSUE THREAD

**Issue by tubone24** [motdotla/dotenv#505]
I was using dotenv, which is a standard feature of [Next.js](https://nextjs.org/), but when I set the following parameters in the .env file, the correct values were not loaded.

.env file
```
USERNAME="tubone24"
```

```javascript
console.log(process.env.USERNAME)
// meita
```

I think this behavior is correct. I think this behavior is correct, because it is not allowed to destroy the environment of the Windows machine itself by setting environment variables at local runtime.
However, I think there are a few people who might have trouble with the same problem, so it would be better to describe the restrictions on the environment variables that can be set in the README or documentation, or to output WARNING when the machine's environment variables are set.

If we get your approval, we would like to create a system that will issue a warning when such a parameter is set.

**Comment by RA80533** [comment]
What happens if you run your application with `dotenv.config({ debug: true })`?

**Comment by tubone24** [comment]
You're absolutely right.
Next.js didn't have the ability to specify the `dotenv.config({ debug: true })` option, so I'll request it.

**Comment by motdotla** [comment]
This issue also goes back to this: https://github.com/motdotla/dotenv/issues/517

In the principle of 'least surprise' the current behavior is very surprising. We will track and improve this at issue 517. Your idea of a warning could also be useful here.
