### ISSUE TITLE
Comma is not parsed correctly

### ISSUE THREAD

**Issue by neelip** [motdotla/dotenv#508]
If the input is as following:
`test = "123", 
testb = "456"`
We are seeing something like this: 
`{ test: "123"," , testb: "456"}`

The comma and the right double quote are not removed from the value after parsing. 
Is there a fix for this?

**Comment by motdotla** [comment]
that is the correct behavior. for formatting `.env` files make sure each new variable is on a new line. it is a little different than json in that regard. so you can rewrite to:

```
test="123"
testb="456"
```

and things will work as you expect. good luck! and let me know if you run into the issue again.
