### ISSUE TITLE
ES6 imports: dotenv.config() only called after imports, so ENV variables not available

### ISSUE THREAD

**Issue by dancherb** [motdotla/dotenv#509]
In index.js, we call dotenv.config()

```
import dotenv from 'dotenv'
dotenv.config()
import logic from './logic'
```

In logic.js we refer to `process.env.X` - however, `process.env.X` is `undefined`, when actually we have defined it in `.env`. It seems like the script is being run so that all of the imports occur first, before `dotenv.config()` is called. This has the result that `.env` is not available in any imported files, and `dotenv.config()` may have to be called in every relevant file.

**Comment by dancherb** [comment]
Solution seems to be `import 'dotenv/config'` - we should get this up in the documentation.

**Comment by glen-84** [comment]
https://github.com/motdotla/dotenv/blob/master/README.md#how-do-i-use-dotenv-with-import

**Comment by motdotla** [comment]
Happy you were able to come to the solution. That said, this is not straightforward at all. It requires a deep read of the README. I have a mental note to improve this.
