### ISSUE TITLE
Feature: Permit previously-set process.env overrides

### ISSUE THREAD

**Issue by motdotla** [motdotla/dotenv#517]
Consolidating all these requests into one issue. We are going to get this added to the library soon. Likely we'll borrow or fork off one of the below pull requests. Thank you everyone for your suggestions and help on this!

* https://github.com/motdotla/dotenv/issues/436
* https://github.com/motdotla/dotenv/pull/487
* https://github.com/motdotla/dotenv/pull/493
* https://github.com/motdotla/dotenv/issues/436

would require a major version bump

**Comment by NaitYoussef** [comment]
This feature can really be helpful, Can't wait to use it !

**Comment by HartS** [comment]
Can an option be added to override values which are set but empty, while preserving values which are set with some value?

**Comment by motdotla** [comment]
> Can an option be added to override values which are set but empty, while preserving values which are set with some value?

Good thought. Not initially but in a later release. Can you elaborate on your use case for that?

**Comment by motdotla** [comment]
This is now available in v14.1.0 and above 🎉: https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1410-2022-01-17

Docs: https://github.com/motdotla/dotenv#override

**Comment by HartS** [comment]
> > Can an option be added to override values which are set but empty, while preserving values which are set with some value?
> 
> Good thought. Not initially but in a later release. Can you elaborate on your use case for that?

I don't remember now (posted this ~6 months ago), but if I had to guess, it relates to running a program that uses dotenv from a script which runs with `errexit` and `nounset` option, and sets variables explicity which may be empty.

For example, a pattern I use: `export SOME_VAR=${SOME_VAR:-}` (defaults to empty string if not set in environment).

`SOME_VAR` can then safely be used in the script, but this pattern at the top indicates that setting it is optional. If set, we want it to be respected by the node script called, but if empty and set in dotenv, we want to use that instead

**Comment by motdotla** [comment]
@HartS thank you. would [dotenv-expand](https://github.com/motdotla/dotenv-expand) actually solve that problem for you?

**Comment by HartS** [comment]
Actually yes! In fact, this would also probably take care of this issue altogether :P

**Comment by motdotla** [comment]
> Actually yes! In fact, this would also probably take care of this issue altogether :P

Ok great. 💛. If it doesn't just open up another issue. Best of luck.
