### ISSUE TITLE
Feature: Move dotenv toward bash-like behavior

### ISSUE THREAD

**Issue by motdotla** [motdotla/dotenv#521]
Dotenv currently varies its behavior vs bash's behavior when sourcing .env files.

Consider moving toward behavior that will match bash.

Other discussions:

* https://github.com/motdotla/dotenv/pull/440
* https://github.com/motdotla/dotenv/issues/496

should require a major version bump

**Comment by xzyfer** [comment]
Would "bash's behavior when sourcing .env files" also include supporting `export`ed values (#112, #213)?

**Comment by devon-whil** [comment]
Is there any work around currently that allows the use of a dollar sign character?

**Comment by martin-braun** [comment]
@devon-whil `KEY='asd$asd'` works for me. It plays [nice with single quotes](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L31), but I lack to find the piece of code that will not evaluate variables this way, but in my tests, this seem to work.

**Comment by phoenixeliot** [comment]
For anyone else having trouble with this: For an env variable that had to be JSON with interpolated string values, I had to do this non-bash-standard syntax:
```
SOME_VAR='["$INTERPOLATED_VAR","$OTHER_VAR"]'
```

This was in Next.js v12, which I _think_ uses this package now. I know at some point they used their own custom thing, so not 100% sure about that.

**Comment by motdotla** [comment]
this effort will move into https://github.com/dotenvx/dotenvx (where a standard for `.env` file parsing is being developed across all languages and platforms)
