### ISSUE TITLE
Feature: Support inline comments

### ISSUE THREAD

**Issue by motdotla** [motdotla/dotenv#524]
Adding comments to a .env file would be very helpful and improve developer UX.

* https://github.com/motdotla/dotenv/issues/156
* https://github.com/motdotla/dotenv/issues/484
* https://github.com/bkeepers/dotenv#comments

should require a major version bump

**Comment by brelian** [comment]
Hi @motdotla, how is it going on this feature? Does anyone take it yet? If nobody, I would like to try to address it.
