### ISSUE TITLE
Feature: Support to parse path along with home directory ~

### ISSUE THREAD

**Issue by brelian** [motdotla/dotenv#527]
Currently, we don't support parsing an env path with a home director character `~`. e.g.

![Snipaste_2021-05-06_20-02-45](https://user-images.githubusercontent.com/23089063/117295223-285e3980-aea6-11eb-994f-8c750eb366b1.png)

**Comment by motdotla** [comment]
An alternative and immediate solution to this is to do:

```
require('dotenv').config({ path: path.join(os.homedir(), '/.env') })
```

We'll discuss your PR separately as possibly being a useful convenience but for the purpose of this issue the above code example should solves things for your immediate needs.
