### ISSUE TITLE
Incorrect tag created for v9.0.1

### ISSUE THREAD

**Issue by agarzola** [motdotla/dotenv#529]
I was reviewing the differences between v9.0.0 and v9.0.1 and noticed a typo:
![image](https://user-images.githubusercontent.com/439649/117691845-571c2e80-b18a-11eb-8276-82ac9a8feee5.png)

What should be `v9.0.1` was instead tagged as `v0.9.1`.

**Comment by motdotla** [comment]
good catch @agarzola! thank you. fixed up. https://github.com/motdotla/dotenv/tree/v9.0.1
