### ISSUE TITLE
Typings: add generic support to parse function

### ISSUE THREAD

**Issue by ericmorand** [motdotla/dotenv#530]
Currently, `parse` is declared as returning `DotenvParseOutput`. This forces people wanting to have typed environmental configuration to typehint the result of parse as `any`:

```ts
type Configuration = {
    FOO: string
};

const configuration: Configuration = parse(readFileSync('.env')) as any;
```

This looks not very elegant and could be solved easily by having `parse` function being generic:

```ts
type Configuration = {
    FOO: string
};

const configuration= parse<Configuration>(readFileSync('.env'));
```

**Comment by motdotla** [comment]
Thanks again for this @ericmorand. Going out as part of `10.0.0`
