### ISSUE TITLE
Definitely don't use this library

### ISSUE THREAD

**Issue by synedra** [motdotla/dotenv#532]
A couple of days ago dotenv worked with my environment, and then they put out a new version with breaking changes.  I can no longer edit values.  Do not use this library.

**Comment by motdotla** [comment]
@synedra can you describe in more detail and maybe I can help you debug?

dotenv doesn't actually prevent you from editing values. You can just edit the file. It simply just loads the values into your environment.

**Comment by motdotla** [comment]
i'll close this for now since there have been no other reports of this after the multiple releases. as you leave comments I can help you debug and re-open the ticket at that point.
