### ISSUE TITLE
The changelog entry for v9.0.0 seems to have content from other versions

### ISSUE THREAD

**Issue by julienw** [motdotla/dotenv#535]
Hey,
I was reviewing the changes when upgrading dotenv in my project, and this looks familiar.
Indeed most (or all?) of the content in the [CHANGELOG](https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md) file for v9.0.0 comes from previous releases. I would think this was a mistake :-)

**Comment by motdotla** [comment]
Good eye for detail, Julien. Updated to compare against 8.6.0.

**Comment by julienw** [comment]
> Good eye for detail, Julien. Updated to compare against 8.6.0.

Maybe I wasn't clear enough :-) I was talking about the _content_, not the link (the link itself I admit I missed it :D). I guess this was all the same mistake at the start.

![image](https://user-images.githubusercontent.com/454175/118832397-e29b6b00-b8c0-11eb-9b1b-5d81ec3fd34d.png)

This seems to contain everything from 8.1.0.

**Comment by motdotla** [comment]
ah yes. I see. At the time I was thinking to roll everything from 8.0 to 9.0 in. Thanks for the catch. Updated.
