### ISSUE TITLE
not installing on M1 chip

### ISSUE THREAD

**Issue by VadneyK** [motdotla/dotenv#540]
Hello I am working on a repo and I want to use dotenv so I do `npm i dotenv` but I get the error below. I've also tried with `yarn` but I have the same issue.

Perhaps this may be an incompatibility with the M1 chip?

config:
MacOS BigSur 11.2.3 M1 chip
yarn: 1.22.10
<img width="521" alt="Screen Shot 2021-05-31 at 11 10 12 AM" src="https://user-images.githubusercontent.com/57117207/120228833-c670c580-c200-11eb-982e-a326ea140af3.png">

kentarovadney@Kentaros-MacBook-Air discord-faucet-dusty % npm i dotenv
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/kentarovadney/Desktop/code/discord-faucet-dusty/node_modules/node
npm ERR! command failed
npm ERR! command sh -c node installArchSpecificPackage
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/kentarovadney/Desktop/code/discord-faucet-dusty/node_modules/node/node_modules/node-darwin-arm64
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node installArchSpecificPackage
npm ERR! npm ERR! node:internal/modules/cjs/loader:944
npm ERR! npm ERR!   throw err;
npm ERR! npm ERR!   ^
npm ERR! npm ERR! 
npm ERR! npm ERR! Error: Cannot find module '/Users/kentarovadney/Desktop/code/discord-faucet-dusty/node_modules/node/node_modules/node-darwin-arm64/installArchSpecificPackage'
npm ERR! npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
npm ERR! npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:774:27)
npm ERR! npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR! npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR! npm ERR!   requireStack: []
npm ERR! npm ERR! }
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/kentarovadney/.npm/_logs/2021-05-31T17_58_58_573Z-debug.log
npm ERR! node:internal/modules/cjs/loader:944
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'node-darwin-arm64/package.json'
npm ERR! Require stack:
npm ERR! - /Users/kentarovadney/Desktop/code/discord-faucet-dusty/node_modules/node/installArchSpecificPackage.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:99:19)
npm ERR!     at ChildProcess.<anonymous> (/Users/kentarovadney/Desktop/code/discord-faucet-dusty/node_modules/node-bin-setup/index.js:18:27)
npm ERR!     at ChildProcess.emit (node:events:365:28)
npm ERR!     at maybeClose (node:internal/child_process:1067:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/kentarovadney/Desktop/code/discord-faucet-dusty/node_modules/node/installArchSpecificPackage.js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kentarovadney/.npm/_logs/2021-05-31T17_58_59_224Z-debug.log
kentarovadney@Kentaros-MacBook-Air discord-faucet-dusty %

**Comment by motdotla** [comment]
can you try installing an older version of dotenv and see if that still fails?

```
npm install dotenv@8.0.0
```

**Comment by VadneyK** [comment]
thanks! just tried it and am having the same issue:

kentarovadney@Kentaros-MacBook-Air plasm_discord_faucet % yarn add dotenv@8.0.0
yarn add v1.22.10
warning ../../../package.json: No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
error /Users/kentarovadney/Desktop/code/plasm_discord_faucet/node_modules/node: Command failed.
Exit code: 1
Command: node installArchSpecificPackage
Arguments: 
Directory: /Users/kentarovadney/Desktop/code/plasm_discord_faucet/node_modules/node
Output:
npm ERR! code 1
npm ERR! path /Users/kentarovadney/Desktop/code/plasm_discord_faucet/node_modules/node/node_modules/node-darwin-arm64
npm ERR! command failed
npm ERR! command sh -c node installArchSpecificPackage
npm ERR! node:internal/modules/cjs/loader:944
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/Users/kentarovadney/Desktop/code/plasm_discord_faucet/node_modules/node/node_modules/node-darwin-arm64/installArchSpecificPackage'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:774:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kentarovadney/.npm/_logs/2021-06-01T22_39_33_155Z-debug.log
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'node-darwin-arm64/package.json'
Require stack:
- /Users/kentarovadney/Desktop/code/plasm_discord_faucet/node_modules/node/installArchSpecificPackage.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at ChildProcess.<anonymous> (/Users/kentarovadney/Desktop/code/plasm_discord_faucet/node_modules/node-bin-setup/index.js:18:27)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kentarovadney/Desktop/code/plasm_discord_faucet/node_modules/node/installArchSpecificPackage.js'
  ]
}
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
kentarovadney@Kentaros-MacBook-Air plasm_discord_faucet %

**Comment by VadneyK** [comment]
it seems like this may be an npm issue:

**Comment by motdotla** [comment]
Possibly. Are you able to install any node modules via yarn or npm on that machine?

**Comment by VadneyK** [comment]
Yes, I can install many other libraries. very odd.

**Comment by VadneyK** [comment]
small example of libraries that load

![Screen Shot 2021-06-03 at 11 31 52 AM](https://user-images.githubusercontent.com/57117207/120694631-4f853800-c45f-11eb-8397-be031cb1dad7.png)

**Comment by VadneyK** [comment]
I just had to remove `"dotenv": "^8.0.0"` from `package.json` because it seems like installing node via npm executes a [deprecated code base here](https://www.npmjs.com/package/node-bin-setup) which is the dependency for [`node-darwin-arm64`](https://www.npmjs.com/package/node-darwin-arm64#download). They really need to remove this dependency or something because I've spent countless hours trying to figure this out! ;{

<img width="304" alt="Screen Shot 2021-06-03 at 7 37 53 PM" src="https://user-images.githubusercontent.com/57117207/120737585-32725880-c4a3-11eb-88d8-01c8863fc6c5.png">

**Comment by VadneyK** [comment]
above issue caused this
