### ISSUE TITLE
Semver compliancy

### ISSUE THREAD

**Issue by medikoo** [motdotla/dotenv#541]
Does this package follow semver?

If so, what were the breaking changes introduced with v10?

Changelog is silent on that

**Comment by motdotla** [comment]
We follow as closely as possible but sometimes we get it wrong.

This time we chose to upgrade because of the added `~` home path feature. That was the major change for v10.

**Comment by medikoo** [comment]
> This time we chose to upgrade because of the added ~ home path feature. That was the major change for v10.

Ok, so per semver rules it technically should go as another `9.x` release (as there was nothing breaking introduced)

It'll be good to outline in CHANGELOG that v10 comes with no breaking changes, otherwise it's really confusing.

**Comment by dscalzi** [comment]
I agree, this issue saved me spending a ton of time trying to find the breaking changes. The reason for a semver-major increment should be noted clearly on the changelog.

**Comment by actuallymentor** [comment]
Please actually use semver. This is a great package, but not respecting semver gives a lot of "oh shit there are breaking changes" anxiety.

@motdotla adding `~` as an option is not a major change, it is a minor change according to semver.

From semver.org:

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```
