### ISSUE TITLE
Issue with variable value containing the word "process"

### ISSUE THREAD

**Issue by thomanimation** [motdotla/dotenv#542]
If a variable defined in .env contains the word "process" the project cannot be built.

For example, if in .env we define the variable:

MY_URL = http://my-process.example.com

terser throws the following error: SyntaxError: Unexpected token name «env», expected punc «,»

After removing the variable containing the word "process" : the project is built successfully.

Is there a workaround to use variables whose values contain the word "process" with dotenv ?

**Comment by motdotla** [comment]
I have been unable to repeat this issue.

Is it possible your code is using another plugin on top of dotenv? Possibly dotenv-expand?
