### ISSUE TITLE
Dotenv config preload is choking on husky pre-commit hook

### ISSUE THREAD

**Issue by FJancsi** [motdotla/dotenv#547]
Having a monolith repo with the following structure:
- root (package.json)
script: "cd app1/folder && npm run test"
 -- app1 (package.json)
 script: "test": "c8 mocha -r dotenv/config --recursive 'tests/**/*.spec.mjs'",
 -- app2 (package.json)
 -- app3 (package.json)
 
 cause infinite loop.

**Comment by motdotla** [comment]
I haven't been able to duplicate this. If anyone comes across this can you please add a comment.
