### ISSUE TITLE
Dotenv running on debug mode for any non-undefined debug option

### ISSUE THREAD

**Issue by n8eloy** [motdotla/dotenv#548]
Hey all! We have noticed that passing any defined values in the `debug` option in `config` function will turn on debug mode.

e.g. all those will activate debug logs:
```ts
dotenv.config({ debug: true })
dotenv.config({ debug: false })
dotenv.config({ debug: 'foo' })
dotenv.config({ debug: 0 })
dotenv.config({ debug: {} })
```

The [documentation](https://github.com/motdotla/dotenv/blob/master/README.md#debug) mentions that `debug` defaults as false, but I didn't expect that passing false explicitly wouldn't make it work the same way.

What I'm exactly trying to accomplish is programmatically activate debug mode for a certain environment variable:

```ts
dotenv.config({ debug: process.env.NODE_ENV === 'development' })
```

The only way I've made it work was by passing an undefined or null value:

```ts
dotenv.config({ debug: process.env.NODE_ENV === 'development' ? true : undefined })
```

I do think this happens because `options.debug` is checked against `null`, but not against falsy values. Is this expected behavior?

https://github.com/motdotla/dotenv/blob/27dfd3f034ce00b1daa72effbd91dd7788aced48/lib/main.js#L83-L97

I'm using Dotenv version `8.6.0`

**Comment by nifr** [comment]
This issue is still present in `10.0.0`. 

@motdotla  - Can I help somehow to get #550 merged and a new release tagged?
