### ISSUE TITLE
correctly load environemnt variables on github actions

### ISSUE THREAD

**Issue by raza2022** [motdotla/dotenv#549]
I don't know am I using it right but I have a use case where I need to load GitHub secrets with dotenv file so here is my use case
I am using migrate-mongo in next js which is working fine locally within nestJS application however as I am using migration within isolated JS file, so I have to load env variables separately too, like 

`mongodb+srv://${secrets.DATABASE_USER}:${process.env.DATABASE_PASSWORD}`
so locally I just added the required dotenv module with local file path on top of migrate-mongo config file and it's working fine

`require('dotenv').config({ path: '.env.development.local' })`

however I couldn't able to find a solution for github action pipelines as I know in .yml file secrets can be accessed as `{{ secrets.DATABASE_USER }}` so I tried these ways in migrate-mongo config

`require('dotenv').config()`
`require('dotenv').config({ path: 'secrets' })`

but nothing works any help will be greatly appreciated

**Comment by guiuser** [comment]
@marcoow @motdotla @af @jessefulton any suggestion/guidance about this use case?

**Comment by raza2022** [comment]
@marcoow @motdotla @af @jessefulton any suggestion/guidance about this use case?

**Comment by motdotla** [comment]
For GitHub actions we recommend using https://sync.dotenv.org. That will then sync your ENVs directly to your GitHub actions.
