### ISSUE TITLE
new feature proposal: default value if var is not defined

### ISSUE THREAD

**Issue by stefanocudini** [motdotla/dotenv#552]
how can I make sure that if an environment variable is not defined(inside .env file) I can have a default value?
example:
assuming that the PORT variable is not specified in my .env file
but I want to have a default value anyway:
```javascript
require('dotenv').config({
  defaults: {
    PORT: 8080
  }
})
```

**Comment by paramsiddharth** [comment]
Looks good! If approved, I would like to work on the issue.

**Comment by tawfiek** [comment]
Looking cool 👌🏻

**Comment by motdotla** [comment]
@stefanocudini, @paramsiddharth, @tawfiek can you elaborate on the use case for this?

Why not just make sure the ENV is set in the `.env` file? Why have to go to 2 places to figure out where a value is being injected?

**Comment by tawfiek** [comment]
@motdotla in my case we ignore the .env file from remote repos, adding these default values in the code itself might make the developers start the service in there development machine without having the hassle to share the .env file with each other, or making out form .env.example or something like this.

And making the .env file specific to override the default values in the remote environments, specifically for these tiny service that doesn't contain these much secrets.

it might makes the onboarding a little bit easier, just clone, serve and you good to go.

**Comment by motdotla** [comment]
> without having the hassle to share the .env file with each other, or making out form .env.example

@tawfiek would [Dotenv Sync](https://sync.dotenv.org/) solve that for you?

**Comment by tawfiek** [comment]
@motdotla yea, looks promising actually. 🧐
Interesting to get more details about how it's working.

> > without having the hassle to share the .env file with each other, or making out form .env.example
> 
> @tawfiek would [Dotenv Sync](https://sync.dotenv.org/) solve that for you?

**Comment by motdotla** [comment]
@tawfiek These docs can get you started quickly: https://docs.dotenv.org/#guides

And then we also have quite a few video guides here: https://vimeo.com/dotenv

**Comment by motdotla** [comment]
@tawfiek I think your team will like it. It makes it very easy to securely sync you `.env` files across your team's many machines. So far everyone using it so far is really enjoying it. They say it is like using `git` - one of the first things they now reach for with their team.
