### ISSUE TITLE
Beginner Friendly Docs

### ISSUE THREAD

**Issue by nimit2801** [motdotla/dotenv#556]
1. Please make the docs beginner-friendly, it was hard for me to figure how to use dotenv with ESM
2. We can also make a static website for the package since it's been used by the vast majority of people, this would help a lot of new beginners to get acquainted with the package.

**Comment by UltiRequiem** [comment]
For anyone who wants to use esm, you have to:

```javascript
import dotenv from 'dotenv';
import process from 'node:process';

dotenv.config();
```

**Comment by motdotla** [comment]
@nimit2801 

1. Yes, this is a good idea. We will add soon to https://docs.dotenv.org/
2. https://docs.dotenv.org is becoming that (in addition to the larger dotenv ecosystem)

**Comment by motdotla** [comment]
@UltiRequiem can you confirm if line 2 of your code example is still required?

This example here is functional without importing process: https://github.com/dotenv-org/examples/tree/master/dotenv-esm

**Comment by UltiRequiem** [comment]
Line 2 was never required but is a recommendation from the Node.js team.

https://nodejs.org/api/process.html#process
