### ISSUE TITLE
Escape of shell special characters does not work properly

### ISSUE THREAD

**Issue by AlexPalaz** [motdotla/dotenv#559]
I'm using "dotenv-webpack": "^1.8.0"
My .env:
`API_CALL='https://api.call?\$language=en'`

In the local environment it works correctly. Output:

`https://api.call?$language=en`

but when I build with webpack the result is:

` https://api.call?\$language=en `

What could be?

my webpack:

```
      new Dotenv({
          path: `./.env.${env.production ? 'production' : 'development'}`
      }),
      new webpack.DefinePlugin({
          "process.env.PRODUCTION": env.production || !env.development,
          "process.env.NAME": JSON.stringify(require("./package.json").name),
          "process.env.VERSION": JSON.stringify(require("./package.json").version),
      }),
```

**Comment by motdotla** [comment]
Closing this as I believe it was webpack related and they've since fixed up.
