### ISSUE TITLE
performance impact of reading process.env.X

### ISSUE THREAD

**Issue by didiercolens** [motdotla/dotenv#562]
reading environment variables from process.env is expensive and slow according to:

- https://github.com/nodejs/node/issues/3104
- https://www.reddit.com/r/node/comments/7thtlv/performance_penalty_of_accessing_env_variables/
- https://expressjs.com/en/advanced/best-practice-performance.html

it looks like the behaviour is still the same in recent nodejs, should user prefer using dotenv.config().parsed.X over process.env.X in highly use code paths ?

**Comment by yauri-io** [comment]
@didiercolens one solution is convert all of your .env content into a single .js file.


For example
`.env`
```
SERVER_HOST=0.0.0.0
SERVER_PORT=3000
SECRET=ANY_SECRET_STRING
```

`config.js`
```
module.exports = {
    server: {
        host: process.env.SERVER_HOST,
        port: process.env.SERVER_PORT
    },
    secret: process.env.SECRET
}
```

Then require the `config.js` in any place you want to use

**Comment by motdotla** [comment]
Thank you for posting this. It is interesting. I've decided it is beyond the scope of this module though. We are trying to keep things as simple as possible.

We'd recommend to still use process.env since that works across environments.
