### ISSUE TITLE
import for "dotenv/config" does not work on typescript

### ISSUE THREAD

**Issue by aganglada** [motdotla/dotenv#565]
#### Background

After the `v10.0.0` release, it's possible to import `config` from `dotenv/config`.

#### Issue

When trying to import `config` from `dotenv/config` using `typescript`, it complains it doesn't exist.

Steps to reproduce:

Import `dotenv/config` in the following way in a typescript project
```
import config from 'dotenv/config'
                      ^^^^^^^^^^
```

You will see the IDE complains, this path doesn't exist.

**Comment by kumold** [comment]
My guess is your import should be like this:
```
import { config } from "dotenv"
```

**Comment by motdotla** [comment]
Yes, see docs here: https://github.com/motdotla/dotenv#2-as-early-as-possible-in-your-application-import-and-configure-dotenv

You can also now view examples here: https://github.com/motdotla/dotenv#examples
