### ISSUE TITLE
Improve readme in regards to the ES6 import pitfall

### ISSUE THREAD

**Issue by CherryDT** [motdotla/dotenv#573]
Currently, the readme makes an attempt to raise awareness of how the ES6 import module evaluation order makes `import dotenv from 'dotenv'; dotenv.config()` not work as expected. However, I think the main gotcha isn't brought across from the example. Currently, the example goes like this:

> You must run `dotenv.config()` before referencing any environment variables. Here's an example of problematic code:
> 
> `errorReporter.js`:
> 
> ```js
> import { Client } from 'best-error-reporting-service'
> 
> export const client = new Client(process.env.BEST_API_KEY)
> ```
> 
> `index.js`:
> 
> ```js
> import dotenv from 'dotenv'
> import errorReporter from './errorReporter'
> 
> dotenv.config()
> errorReporter.client.report(new Error('faq example'))
> ```
> 
> `client` will not be configured correctly because it was constructed before `dotenv.config()` was executed.

Now, a reader accustomed to how things used to behave with CommonJS would think: "Of course this can't work, because `dotenv.config()` is called _after_ `errorReporter` is imported, duh." But the main issue is actually that **even if you write `dotenv.config()` before any other imports, those imports will still be evaluated first**. I feel this point isn't brought across well enough.

I suggest changing the code example so that `dotenv.config()` already _is_ below the import of `errorReporter`:

```javascript
import dotenv from 'dotenv'
dotenv.config()

import errorReporter from './errorReporter'
errorReporter.client.report(new Error('faq example'))
```

Also, the sentence "You must run `dotenv.config()` before referencing any environment variables." is confusing for the same reason, because one might think that's already what's happening in the case I showed now. I suggest changing the sentence to "Any other modules imported by the module that itself runs `dotenv.config()` _won't_ see the updated environment variables, even if their `import` statements are below the `dotenv.config()` line, because JavaScript evaluates all the imports first before the file that imported them is evaluated itself." or something along those lines. I have to say I'm not entirely happy with this wording right now either, it can be improved for sure, but it's just what I came up with so far. Maybe it should _start_ with explaining how `import 'dotenv/config'` is the right solution...

**Comment by motdotla** [comment]
Hi @CherryDT what do you think of the newest updates to the README? Does that clarify better according to what you described here?

**Comment by motdotla** [comment]
It's right here at the top fold now: https://github.com/motdotla/dotenv#2-as-early-as-possible-in-your-application-import-and-configure-dotenv
