### ISSUE TITLE
Error: Cannot find module at {Path}/main.jsx

### ISSUE THREAD

**Issue by PazzeG** [motdotla/dotenv#575]
I'm building a web-site, and using Firebase to store data. So, the private keys are on a .env file. I'm trying to import them in a firebase config file. I'm using import in order to use modules. And by following the guide in the dotenv doc, I ran 'node -r dotenv/config main.jsx' on my terminal. But I got an error, and I don't understand what to do. 

### Folders' Architecture
![Capture d’écran (84)](https://user-images.githubusercontent.com/66828481/144412433-5395db98-2f97-41a0-bb9f-8f6c1e2abde4.png)

### Firebase.js
![Capture d’écran (86)](https://user-images.githubusercontent.com/66828481/144413333-5c0605f9-0f06-44ca-8587-1854ce2322f1.png)

### main.jsx
![Capture d’écran (88)](https://user-images.githubusercontent.com/66828481/144413516-bc3270a9-83d7-4a7c-8a95-9ba9e4ac911a.png)

**Comment by motdotla** [comment]
What was the error you received?

**Comment by motdotla** [comment]
Closing and if I hear back we will reopen.
