### ISSUE TITLE
Import environment variables from AWS Secret Manager

### ISSUE THREAD

**Issue by YonatanHanan** [motdotla/dotenv#576]
Hi!

First, thank you for this package I use it in almost  every project.

In the current company i'm working we use AWS Secret Manager.

And I had an idea, what if we could import the environment variables using a secret key.

If I would create a PR to do so, will it be merged?

**Comment by motdotla** [comment]
> First, thank you for this package I use it in almost every project.

❤️ Thank you for the kind words, @YonatanHanan.

And amazing idea!

It is something our community has actually built out under the extended Dotenv Sync: https://sync.dotenv.org

You can see the Amazon Secrets integration here: https://docs.dotenv.org/v1/guide/aws_secrets_integration

What do you think? Would that solve things for you.
