### ISSUE TITLE
Error: INVALID_TOKEN

### ISSUE THREAD

**Issue by GamingWithEPMninjaYT** [motdotla/dotenv#580]
I have tried everything from changing the capitalization, to adding parentheses and quotation marks, and it still gives me this error. I have the file titled **_.env_** inside of a folder titled **_src_**, and the token defined like **_token=_**

_If it is a simple syntax error, sorry-I am new to dotenv and NPM/Discord.JS_

**Comment by motdotla** [comment]
Hi @GamingWithEPMninjaYT, what framework are you using. Here's some basic examples of using dotenv correctly:

https://github.com/dotenv-org/examples

If you are using a different framework, let me know, and we will try to add an example for that one.
