### ISSUE TITLE
Example for multiline inconsistency

### ISSUE THREAD

**Issue by peterjwest** [motdotla/dotenv#59]
In the readme your explanation of multiline values says newlines are expanded in double quotes, but the example you give uses single quotes.

**Comment by motdotla** [comment]
Thanks @peterjwest . Want to make a pull request for that?

**Comment by motdotla** [comment]
https://github.com/motdotla/dotenv/pull/67

**Comment by motdotla** [comment]
Fixed up. Thanks again for making this known. Best.
