### ISSUE TITLE
Webpacking modules including 12.x dotenv trigger error: Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by ryanrd** [motdotla/dotenv#592]
`  "exports": {
    ".": {
      "require": "./lib/main.js",
      "default": "./lib/main.js",
      "types": "./lib/main.d.ts"
    },`

should be
`  "exports": {
    ".": {
      "require": "./lib/main.js",
      "types": "./lib/main.d.ts"
      "default": "./lib/main.js",
    },`

**Comment by motdotla** [comment]
Can you elaborate on this with some code examples, please? I am not able to duplicate this.

Here is the example I am running: https://github.com/dotenv-org/examples/tree/master/dotenv-webpack2

**Comment by ryanrd** [comment]
I'll try to adapt the example you linked to.  The project itself is a typescript project that uses dotenv and imports an esm module that uses dotenv also.  

I can confirm that 12.0.4 works without error in the project that we were seeing errors when using 12.0.3.

**Comment by motdotla** [comment]
> I can confirm that 12.0.4 works without error in the project that we were seeing errors when using 12.0.3.

Ok, that is good. That means order DID matter then. That surprises me so thank you for saving us time by finding the issue and solving it. 💛
