### ISSUE TITLE
Working dotenv.config().parsed Is this configuration okay?

### ISSUE THREAD

**Issue by elias-soykat** [motdotla/dotenv#598]
Hey.. 

Is there any problem will occurs if i am using this type of configuration? 

You did not mentioned also in your documentation. So am using it?

![IMG_20220120_004331_798](https://user-images.githubusercontent.com/76895393/150195313-1e4a1608-06b9-4bca-9633-c666752cc486.jpg)

**Comment by motdotla** [comment]
That is fine... except that you should load dotenv first. So adjust your top 4 lines to this:

```
// initialize app
const env = dotenv.config().parsed;
const PORT = env.port
const app = express();
```

and you'll be good to go 💪
