### ISSUE TITLE
Multiline to be released soon

### ISSUE THREAD

**Issue by kaname-png** [motdotla/dotenv#599]
I saw that the multiline option was added, but when I install the package in its latest version I don't see that change, the typescript types also don't have that change.

I tried to delete the file yarn.lock, node_modules and delete the yarn cache but always the same thing happens, that change is not reflected when I install the latest version, I do not know if this only happens with me.

**Comment by motdotla** [comment]
Multiline has not been released just yet. It is still sitting in master.

I believe it will be released tomorrow.

**Comment by motdotla** [comment]
Until then you can install it with: 

```
npm install motdotla/dotenv#838e89e --save
```

**Comment by bewest** [comment]
FWIW, the multiline option seems to perform as expected in my testing.  Looking forward to release.
This matches what happens in bash when manually doing `(. tests/.env-multiline.env && echo $MULTI_SINGLE_QUOTED)` and similar.  Also, FWIW, this makes it suitably matched for the behavior of https://github.com/substack/node-shell-quote et al to quote variable contents correctly.

**Comment by motdotla** [comment]
Released. https://www.npmjs.com/package/dotenv/v/14.3.0

Thank you for waiting the few days and for going the length of installing from the commit. 💛
