### ISSUE TITLE
Preload help needed

### ISSUE THREAD

**Issue by nouman91** [motdotla/dotenv#602]
Hello, everyone looking for help on the issue I am running into when I am trying to use it as preload config.

I have a small back-end service bootstrap with nestJs. I want to preload the environment variables and then start my server. My setup is as follows

```
{
"start:dev" : "node -r dotenv/config && npm run start:local",
"start:local": "nest start --watch"
}
```

With this setup, it gets into node REPEL and can't seem to execute the next  `npm run start:local` command. I have  .env file at the root of the project directory. 

What am I missing?

**Comment by motdotla** [comment]
@nouman91 we just added a nestjs example here: https://github.com/motdotla/dotenv#examples

It looks like the best practice is to follow these steps here rather than use the preload mechanism: https://docs.nestjs.com/techniques/configuration

**Comment by nouman91** [comment]
Thank you for getting back to me and quickly setting up the example.  Actually, I wanted to follow recommend the practice of 1) not loading the env variables in code 2) having one env file. For that I was asking how preload option would work in nestjs. I asked around in the nestjs community. This is the preload solution that worked for me:

`nest start --watch -e \"node -r dotenv/config\"`
