### ISSUE TITLE
`Named export 'parse' not found` since `14.3.0`

### ISSUE THREAD

**Issue by adriaanmeuris** [motdotla/dotenv#604]
Importing the parse method in an ESM environment worked fine in `14.2.0`:
```js
import { parse as parseDotEnv } from 'dotenv';
```

Since `14.3.0` this results in error `Named export 'parse' not found.`

**Comment by motdotla** [comment]
Investigating this.

**Comment by JeromeFitz** [comment]
> Investigating this.

@motdotla I shared some investigation in #605 and a potential patch in #606

Thanks for sharing and providing details @adriaanmeuris

**Comment by motdotla** [comment]
Fixed in `14.3.1`. https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1431-2022-01-25

thanks goes to @JeromeFitz. Thanks again!
