### ISSUE TITLE
Codekit & dotenv

### ISSUE THREAD

**Issue by iamdangavin** [motdotla/dotenv#607]
Starting here, but happy to move this over to the Codekit issues if needed.

I see the README has listed to use: `import 'dotenv/config` when running an ES6 so I was attempting to use that however when doing that during my compiling I am getting these warnings:

```
Bundled and transpiled successfully, but with warnings: No name was provided for external module 'fs' in output.globals – guessing 'require$$0'
No name was provided for external module 'path' in output.globals – guessing 'require$$1'
No name was provided for external module 'os' in output.globals – guessing 'require$$2'
Creating a browser bundle that depends on Node.js built-in modules ("path" and "os"). You might need to include https://github.com/snowpackjs/rollup-plugin-polyfill-node
```

In the browser I am getting `Can't find variable: process`

Now my setup is probably not the most optimum and edge case. The agency I work with uses Codekit & Mamp Pro for development and local server setup. So not sure if that is what's truly going on here.

Any direction on where to start here would be great. If you need more information let me know.

**Comment by motdotla** [comment]
Hi @iamdangavin, thanks for raising this. I haven't used Codekit. I will download it and give it a try and then work on debugging the issue.

**Comment by motdotla** [comment]
@iamdangavin are you using the build process here to build your project? https://codekitapp.com/help/build/

And if so, what kind of project are you writing - a frontend js project or a back-end nodejs project?
