### ISSUE TITLE
Support multiline with single AND double quotes in value

### ISSUE THREAD

**Issue by ksathyanm** [motdotla/dotenv#611]
I have a multiline JSON value which contains both single and double quotes. I tried to wrap the value with backtick(`) and it didn't work.

```ini
ENV_KEY=`{
  "foo": "it's not working"
}`
```

I have tried below changes in local and it works for me but I am no expert in regex so asking your help.

```js
const LINE = /(?:^|^)\s*(?:export\s+)?([\w.-]+)(?:\s*=\s*?|:\s+?)(\s*'(?:\\'|[^'])*'|\s*"(?:\\"|[^"])*"|\s*`(?:\\`|[^`])*`|[^#\r\n]+)?\s*(?:#.*)?(?:$|$)/mg

value = value.replace(/^(['"`])([\s\S]+)\1$/mg, '$2')
```

**Comment by motdotla** [comment]
This is wonderful @ksathyanm. Backticks should be a feature of dotenv. It's intuitive. PR coming shortly to support this.

**Comment by motdotla** [comment]
Released 🎉 https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1600-2022-02-02

**Comment by iambumblehead** [comment]
I just found this feature and love it -- thank you @ksathyanm
