### ISSUE TITLE
Empty strings parsed as \"\"

### ISSUE THREAD

**Issue by dackmin** [motdotla/dotenv#612]
Hi,

Starting with v15 empty strings seem to be wrongly parsed:
https://runkit.com/dackmin/dotenv-issue

v14 -> ''
v15 -> '""'

Is this normal and not reflected in the changelog? or not?

Thanks

**Comment by motdotla** [comment]
All these many years and we never had a test for that scenario. Apologies for this regression, and thank you for catching!

PR is here and will go out as `v15.0.1` shorty. https://github.com/motdotla/dotenv/pull/614

**Comment by dackmin** [comment]
I had the unfortunate chance to witness it in production lmao. But at least that helped catch it and I added a test on my side too 😄 
thanks for the fix!

**Comment by motdotla** [comment]
Ah, so sorry! It's released: https://www.npmjs.com/package/dotenv/v/15.0.1 `v15.0.1`
