### ISSUE TITLE
Loading .env from different environments

### ISSUE THREAD

**Issue by erikas-tranauskas** [motdotla/dotenv#613]
I have an issue using dotenv package when I need to load different .env files.

So I have a main .env file and different staging and production config's: .env.staging and .env.prod.

Now .env file loads fine but there is a problem when I run on my production build. There is different variables set on .env.prod than on .env. How do I load the .env.prod properly for only those variables that exist in .env.prod?

I use Symfony Encore and my webpack.config.js looks like this:

```
Encore 
    .configureDefinePlugin(options => {
        const dotenvOptions = {};
        const envConfigPath = `.env.${process.env.NODE_ENV}`;

        if (fs.existsSync(envConfigPath)) dotenvOptions.path = envConfigPath;

        const env = dotenv.config(dotenvOptions);

        if (env.error) {
            throw env.error;
        }

        options['process.env'].TEST_VARIABLE = JSON.stringify(env.parsed.TEST_VARIABLE);
    })
;
```
I could load .env first at any environment I run and after that load another .env file if environment is staging/prod and take the values of needed variables (in this case TEST_VARIABLE), but it looks like it's too much going on here. I think I'm missing something.

Any ideas?

**Comment by erikas-tranauskas** [comment]
This looks like a proper way out: https://www.npmjs.com/package/dotenv-flow

**Comment by motdotla** [comment]
You can also consider using https://github.com/dotenv-org/cli#dotenv-cli-pull-environment-filename to manage this.
