### ISSUE TITLE
The `debuglog` function is not working when dotenv is included

### ISSUE THREAD

**Issue by greguz** [motdotla/dotenv#619]
This is the [snipped](https://nodejs.org/api/util.html#utildebuglogsection-callback):
```javascript
console.log(process.env.NODE_DEBUG)

const util = require('util')
const debuglog = util.debuglog('foo')

debuglog('hello from foo [%d]', 123)
```
When the snipped is fired directly, everything seems to work. (The log is printed)

Using this `.env` file, and requiring `dotenv`, the variable seems to be included, but the log will not work.
```
NODE_DEBUG=foo
```
```sh
node -r dotenv/config debug.cjs
```

Am I missing something?

**Comment by jeffslofish** [comment]
From looking at the node internal code here: https://github.com/nodejs/node/blob/19a909902aec2cb9af13bf901db720b0b9472294/lib/internal/util/debuglog.js#L21 it appears util.debuglog() uses the initial value of process.env.NODE_DEBUG before any user code is run, so if dotenv is writing  to this value it will be ignored for the purposes of util.debuglog().
