### ISSUE TITLE
dotenv not loading variables

### ISSUE THREAD

**Issue by KrishGarg** [motdotla/dotenv#620]
I have `require("dotenv").config()` at the top of my file, and have a `.env` file with variables in the format below:
```
SENDGRID_API_KEY=mykey
```
but if I run `node index.js`, it returns `process.env.SENDGRID_API_KEY` as undefined.

**Comment by motdotla** [comment]
Hi, Krish, I see you closed this. I'm assuming you were able to solve for it.

For anyone else that comes across this, usually the issue is that the `.env` file is not in the root directory. You can turn on debug mode to get more information regarding that.
