### ISSUE TITLE
Please consider slowing down the number of breaking changes to this project

### ISSUE THREAD

**Issue by ryanblock** [motdotla/dotenv#622]
Hi there! This project is wonderful, and I, like many, appreciate the work y'all put into it.

I assume that others, like myself, would also appreciate your considering slowing down the number of breaking changes you issue to `dotenv`. Every time you bump a major, per semver, your users are compelled to take some time out of their days to figure out whether they'll be broken, and need to make time for unplanned work to implement changes to continue to make use of `dotenv`.

By my count, thus far this project has issued five breaking changes in this year alone, and we only just started February. To be clear: I don't think there's anything wrong with breaking changes. They are necessary! But perhaps consider batching them and making them less frequently to reduce the impact on `dotenv` consumers.

Thanks for your consideration!

**Comment by motdotla** [comment]
Thank you @ryanblock and thank you for the kind words. Apologies for the many breaking changes.

Yes, I agree. Others have created and commented on another issue describing the same thing. Thank you for giving added perspective. 

> perhaps consider batching them

Great idea. We'll start to do that.

**Comment by ryanblock** [comment]
Just noticed https://github.com/motdotla/dotenv/issues/616, sorry I hadn't spotted that earlier. 🙏
