### ISSUE TITLE
adding PORT in .env does not work

### ISSUE THREAD

**Issue by duke7able** [motdotla/dotenv#623]
so 2 bugs :
Out of box when there is no .env it does not work properly
 second issue is if i create a .env and add PORT, then it does not work, so i have to install dotenv npm package and configure it in www file as imports to make it work

**Comment by motdotla** [comment]
Hi @duke7able, yes all that is correct.

Dotenv definitely depends on a `.env` file - otherwise it will not work. This is by design.

And yes, you will have to install dotenv otherwise that PORT value will not be set.
