### ISSUE TITLE
Error: Cannot find module 'dotenv' / When running with ubuntu shell script

### ISSUE THREAD

**Issue by soroushBgm** [motdotla/dotenv#624]
I have a shell script, which installs my node app in a Ubuntu system

```
git clone https://github.com/{MyRepoAddress};
cd project;
cat <<EOF >.env
dbCleared=false
mongoDbDatabase="project-db"
mongoDbUsername="$2"
mongoDbPassword="$3"
port=$1
EOF
npm update;
npm i pm2 -g;
npx kill-port $1
pm2 start app.js;
pm2 save;
```

It clones the repo, and then runs `npm update`. So all modules in package.json should be installed (dontenv exists in package.json). But I get the error `Error: Cannot find module 'dotenv'` in runtime.
All modules are installed except this one. I have to run `npm i dotenv` myself to solve the issue.

**Comment by eufelipemateus** [comment]
Same error here.
