### ISSUE TITLE
change readme example

### ISSUE THREAD

**Issue by jimmywarting** [motdotla/dotenv#627]
Here is a example of a `require()` call in your readme

```js
require('dotenv').config()
console.log(process.env) // remove this after you've confirmed it working
```

I consider this as an anti pattern to chain `require()` calls like this... it is just a footgun that only makes it harder to refactor code to esm at a later stage...
could you recommend that ppl instead write things like this instead:

```js
const dotenv = require('dotenv')
const { config } = require('dotenv')
require('dotenv/config.js')
```

you would be surprised of how many just copy and paste things around by following readme examples

**Comment by motdotla** [comment]
Hi @jimmywarting, thank you for the thoughts here. I somewhat agree and we had considered that at one point. But the ease of getting started here with the single line is a very good experience for beginners. We are going to leave it as is.
