### ISSUE TITLE
env override

### ISSUE THREAD

**Issue by fundon** [motdotla/dotenv#63]
Below my env files:

```
├── .env
├── .env.test
```

The `.env` is by default.
The `.env.test` will override the `ENV`.

First load `.env` then load `.env.test`.

I think that maybe need an option for `override` env.

https://github.com/motdotla/dotenv/blob/master/lib/main.js#L32-L34

```js
Object.keys(parsedObj).forEach(function (key) {
        process.env[key] = override ? (parsedObj[key] || process.env[key]) : (process.env[key] || parsedObj[key])
})
```

**Comment by maxbeatty** [comment]
@fundon since releasing v1, we no longer support multiple .env files. You can accomplish the same behavior by calling `config` twice but it's best to use a single .env file per environment.

```
# .env
ANIMAL=cat
```

```
# .env.test
ANIMAL=dog
TEST=true
```

```js
assert = require('assert')
dotenv = require('dotenv')

dotenv.config({path: '.env.test'})
dotenv.config()

assert.equal(process.env.ANIMAL, 'dog')
assert(process.env.TEST)
```

**Comment by fundon** [comment]
Nice! Fix my issue.

**Comment by whytekieran** [comment]
@maxbeatty How is this a solution to removing multiple .env file capabilities? Lets Imagine that ANIMAL in your example is actually PORT and I want my local dev and tests to run on different PORTS how is loading to files both with PORT going to help? I can only see this causing conflicts.
