### ISSUE TITLE
# inside quotes still treated as inline comment

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [motdotla/dotenv#631]
This is very similar to https://github.com/motdotla/dotenv/issues/601 because I am still seeing this issue in v16

I have a .env file that looks like this 
```
KEY1="~`! @#$%^&*()_-+={[}]|\:;"'<,>.?/"
KEY2='~`! @#$%^&*()_-+={[}]|\:;"'<,>.?/'
KEY3=`~`! @#$%^&*()_-+={[}]|\:;"'<,>.?/`
```

When I run this code
```
const dotenv = require('dotenv');
console.log(JSON.stringify(dotenv.config()));
```
 the output I get is 
 
```
{"parsed":{"KEY1":"\"~`! @","KEY2":"'~`! @","KEY3":"`~`! @"}}
```

**Comment by jeffslofish** [comment]
Each of the three strings has the string delimiter for that line somewhere in the middle of the string. For example, the " character is nine characters from the end of the first line. If you remove the " character from that line (and the extra ' from the second line and the extra ` from the third line), then the output will be as expected. 

It is odd that these extra characters are causing it to treat everything after # as a comment.

Also, it doesn't seem like there is a way to have an environment variable with all three string delimiters in it.

**Comment by motdotla** [comment]
thanks @jeffslofish. yes, @rmclaughlin-nelnet the additional `"`, `'`, and ` must be escaped.

here's a working example: https://github.com/dotenv-org/examples/blob/master/usage/dotenv-nodejs-inline-comments/.env

```
KEY1="~`! @#$%^&*()_-+={[}]|\:;\"'<,>.?/"
KEY2='~`! @#$%^&*()_-+={[}]|\:;"\'<,>.?/'
KEY3=`~\`! @#$%^&*()_-+={[}]|\:;"'<,>.?/`
```

<img width="935" alt="Screenshot 2024-02-05 at 3 41 18 PM" src="https://github.com/motdotla/dotenv/assets/3848/78d3a030-d324-4fed-90f4-99c0264dfb8d">

caveat: the ` is not escapable inside of itself. this is one edge case of using `. it is so rare that we are not fixing. so if using backticks wrap the value in double quotes or single quotes. best practice is to only use backticks for multiline strings.
