### ISSUE TITLE
Confused by the behavior of \

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [motdotla/dotenv#632]
I have a .env file with the following keys
```
KEY1="This is a \` string \' with \" in it"
KEY2='This is a \` string \' with \" in it'
KEY3=`This is a \` string \' with \" in it`
```

after running this code
```
const dotenv = require('dotenv');
console.log(dotenv.config());
```

I get the following results
```
KEY1: 'This is a \\` string \\\' with \\" in it',
KEY2: 'This is a \\` string \\\' with \\" in it',
KEY3: 'This is a \\` string \\\' with \\" in it',
```

It looks like \' gets two \ added, but \` and \" only gets one \. Is this intentional? Also the extra \ are not removed when added to the env. Am I suppose to be handling those myself?

**Comment by cameronmitchellapps** [comment]
Which version of node and dotenv are you using? I wasn't able to replicate this issue using Nodejs v16.9.0 and dotenv 16.0.0. The example .env file you provided resulted in the below output for me:
```
This is a \` string \' with \" in it
This is a \` string \' with \" in it
This is a \` string \' with \" in it
```

**Comment by rmclaughlin-nelnet** [comment]
Node 12, dotenv 16

**Comment by motdotla** [comment]
I see your point @rmclaughlin-nelnet. This has been the behavior with this library for a long time.

Here's an example:

```
const dotenv = require('dotenv');
console.log(dotenv.config());

console.log(process.env.KEY1)
console.log(process.env.KEY2)
console.log(process.env.KEY3)
```

Result:

```
{
  parsed: {
    KEY1: 'This is a \\` string \\\' with \\" in it',
    KEY2: 'This is a \\` string \\\' with \\" in it',
    KEY3: '`This is a \\` string \\\' with \\" in it`'
  }
}
This is a \` string \' with \" in it
This is a \` string \' with \" in it
`This is a \` string \' with \" in it`
```

This issue goes into it a bit: https://github.com/motdotla/dotenv/issues/496 and this issue is tracking it: https://github.com/motdotla/dotenv/issues/521

[1] https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#620---2018-12-03
