### ISSUE TITLE
back tick should provide output of command

### ISSUE THREAD

**Issue by mschwartz** [motdotla/dotenv#635]
in my .env, I really want to do:

```
HOST_UID=`id -u`
```

It should run the id command with -u argument and substitute the output.  For example, if id -u prints 1000, then the above should be equivalent to

```
HOST_UID=1000
```

There are many reasons to support back tick this way, instead of using it to quote.  

Instead of the current back tick implementation, you might consider using 'single quote\'s' (backslash to escape quotes).

**Comment by Toilal** [comment]
You can run the following command 

```bash
HOST_UID=$(id -u) node -r dotenv/config your_script.js
```

Most of the time, user id is already available in shell as `UID` environment variable, so you can use dotenv-expand to set HOST_UID.

```
HOST_UID=${UID}
```

**Comment by motdotla** [comment]
@mschwartz you bring up a good point and we discussed this internally for a while. We ended up settling on:

1. Use https://github.com/motdotla/dotenv-eval for command substitution
2. Use https://github.com/motdotla/dotenv-expand for variable expansion
3. In this repo backticks will continue to be used as a quoting mechanism
