### ISSUE TITLE
dotenv retrieves .env file from different project in same workspace

### ISSUE THREAD

**Issue by LeopoldHock** [motdotla/dotenv#641]
Hi. In my setup, dotenv appears to retrieve the .env file not from the project where it was installed via `npm install dotenv --save`, but instead from another project in the same workspace. Removing projects from my workspace appears to help with the behavior.

VS Code Workspace looks like this:
- project-a
- my-node-project
- project-c

When running `my-node-project`, dotenv outpots this:
`'ENOENT: no such file or directory, open 'd:\\...\\projects\\project-a\\.env''`

My setup is VS Code on Windows 10. Any ideas?

**Comment by ckcr4lyf** [comment]
Its usually the current working directory which is checked (i.e. where you run `node blahblah.js` from, irrsepective of where `blahblah.js` is

**Comment by motdotla** [comment]
Yes, @ckcr4lyf described it well. 

Glad you were able to otherwise figure it out @LeopoldHock by using the path option.
