### ISSUE TITLE
File URL support in `DotenvConfigOptions.path`

### ISSUE THREAD

**Issue by kyranet** [motdotla/dotenv#648]
Most of Node.js's FS methods now accept an `URL` instance pointing to a file, including [`fsPromises.readFile`](https://nodejs.org/dist/latest-v17.x/docs/api/fs.html#fspromisesreadfilepath-options), such overload is useful for ESM users as it skips several steps when dealing with paths relative to a module's.

Right now, if we are using ESM, and we need to load a file based on the module's path, we need to use [`url.fileURLToPath`](https://nodejs.org/dist/latest-v17.x/docs/api/url.html#urlfileurltopathurl), which results on the following code:

```typescript
config({ path: fileURLToPath(new URL('../.env', import.meta.url)) });
```

However, it would be very convenient to support URL under the hood, just like the `fs` module does. With the changes, the code above would be refactored to simply:

```typescript
config({ path: new URL('../.env', import.meta.url) });
```

This change would likely not require a Node.js version bump, as [`fs.readFileSync`](https://nodejs.org/dist/latest-v17.x/docs/api/fs.html#fsreadfilesyncpath-options) supports `URL` since `v7.6.0`, and if [`url.fileURLToPath`](https://nodejs.org/dist/latest-v17.x/docs/api/url.html#urlfileurltopathurl) is needed, it was added in `v10.12.0`. Which makes both functions available under the [library's required engine version](https://github.com/motdotla/dotenv/blob/578574c6a7ee5c662d27c26df82b30fd11a2a647/package.json#L53) in `package.json`.

**Comment by motdotla** [comment]
This is released in `dotenv@16.1.0-rc2`

Try it out and let us know if works for you.

It will be officially part of 16.1.0 later this month.
