### ISSUE TITLE
Supporting Multiple env files

### ISSUE THREAD

**Issue by hitmands** [motdotla/dotenv#649]
Hi, 
I would love to request for a feature enhancement whereas `dotenv/config` would be able to load multiple env files.

```shell
node -r dotenv/config .env .local.env index.js
```

Would this be possible?

**Comment by apurvak-perpetualny** [comment]
Hello
I'm also waiting the same enhancement?

It will really help to solve multiple instance issue while deploying on multiple instances.

**Comment by joshmeads** [comment]
Take a look at [Dotenv Flow](https://github.com/kerimdzhanov/dotenv-flow)

**Comment by hitmands** [comment]
Nice advise @joshmeads , 
Happy to close this issue as there wasn't any real follow up!

**Comment by motdotla** [comment]
Also take a look at https://github.com/dotenv-org/dotenv-vault

I used to use flow but found it can get a bit confusing. That led to us building out dotenv-vault - among other things.

**Comment by joshmeads** [comment]
> Also take a look at [dotenv-org/dotenv-vault](https://github.com/dotenv-org/dotenv-vault)
> 
> I used to use flow but found it can get a bit confusing. That led to us building out dotenv-vault - among other things.

@motdotla I found dotenv-vault a few days after posting on this issue, I'd agree @hitmands  it's the better solution. Both should hopefully solve the issue though 👍🏻
