### ISSUE TITLE
'silent' option not documented

### ISSUE THREAD

**Issue by harriha** [motdotla/dotenv#65]
The #62 brought support for the 'silent' option, but seems that the documentation for it was forgotten from the README.

**Comment by jcblw** [comment]
@harriha thanks for the ping. We need to get this in there.

**Comment by motdotla** [comment]
Thanks for brining this up @harriha. PR opened: https://github.com/motdotla/dotenv/pull/66

**Comment by harriha** [comment]
Thanks for the quick fix :+1:
