### ISSUE TITLE
DotenvParseOutput declares that all environment variables are defined

### ISSUE THREAD

**Issue by kf6kjg** [motdotla/dotenv#650]
As the code currently exists the type system can't help the user realize that the values coming from the parse might not exist.

Example:
```ts
import FS from "fs";
import * as DotEnv from "dotenv";

const envVals = DotEnv.parse(FS.readFileSync("myvars.env"));

console.log(`MY_ENV_VAR type: ${typeof envVals.MY_ENV_VAR}`);
// Typescript says the type of envVals.MY_ENV_VAR is "string", but what is it really?
```

Save the above into `test.ts`, execute as follows:
```sh
touch myvars.env
$(npm bin)/ts-node-script test.ts
```

My result:
```text
MY_ENV_VAR type: undefined
```

Thus there's a disparity between what actually happens and the type system, causing the developer to not be aware of an undefined value until runtime.

Yes I know I could just load into process.env using the `config()` method and get the signature I'm looking for - but my current use case calls for loading the vars without placing them into process.env hence the use of `parse`.

**Comment by motdotla** [comment]
If you don't define the environment variable in myvars.env then that will happen.

**Comment by kf6kjg** [comment]
Wait wat? That' my predicate yes.
Am I correct in understanding that you are saying that something that at runtime CAN be `undefined` SHOULD not declare it in the type at compile time?

All I'm asking here is that `DotEnv.parse()` return the same type signature as `process.env` for all the same reasons that `process.env` is defined the way it is.

**Comment by motdotla** [comment]
There are real world cases (though I can't recollect them right now but remember coming across them with users) where an environment variable is undefined, but the code should still run. This would take that ability away, correct?

I'm hesitant to change that since that has always been the behavior.

Can you point me to the process.env type signature and elaborate more on why typescript developers would really want and need this?

**Comment by motdotla** [comment]
related: https://github.com/motdotla/dotenv/pull/651

**Comment by kf6kjg** [comment]
It would actually help prevent code that would fail at run time if the env var was not defined in the file. E.g. currently `DotEnv.parse("").asdf.length` will not give a TypeScript error, but would throw at runtime in Javascript. My suggested change would cause that to fail to compile because `asdf` could be undefined. This would help clue the developer that they need to write safer code. 

As to the TypeScript definition, see: 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/process.d.ts#L552

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/process.d.ts#L112

Which resolved to `Dict<string>`.

**Comment by wackbyte** [comment]
Currently, TypeScript assumes that *every* environment variable in `DotenvParseOutput` will always be present, which is not true at runtime. Fixing this would help developers avoid bugs where they assume an environment variable was defined when it was actually not.

**Comment by motdotla** [comment]
i don't think dotenv should implement this. maybe i will change my mind in the future. 

until then use something like https://github.com/LeoBakerHytch/ts-dotenv
