### ISSUE TITLE
Suggestion: Support for Referenced Variables

### ISSUE THREAD

**Issue by sinclairzx81** [motdotla/dotenv#656]
Hi,

Was wondering if `dotenv` could support some form of key referencing to help mitigate duplicate configurations. Such a feature could look something like the following where the `&` is interpreted as a `ref`. 

```bash
A = "Hello"   # A = "Hello"
B = &A        # B = "Hello"
```

I note that there is some prior art in this space with YAML which is able to create referenceable anchors (denoted with `&`) and dereferenced with `*`. So as a possible alternate to the above, perhaps the following might be worth considering (keeping inline with YAML convention)

```bash
&A = "Hello"   # Denotes a referenceable variable but does not write to process.env
B  = *A        # Dereference A
```
Interested to know if this might be something worth considering
Many Thanks
S

**Comment by JaLe29** [comment]
+1

**Comment by motdotla** [comment]
@sinclairzx81 @JaLe29 does dotenv-expand do you what you need? https://github.com/motdotla/dotenv-expand

**Comment by JaLe29** [comment]
@motdotla oh, perfect. Thank you!

**Comment by sinclairzx81** [comment]
@motdotla Apologies for the delay in reply. Actually `dotenv-expand` does look like it provides a solution here. I did actually come across this when looking up variable references, but I guess I didn't parse the syntax it uses vs what I had imagined in my head for this feature :D The library does look good though.

Will close off this issue.
Many Thanks
S
