### ISSUE TITLE
Does not raise an error when parsing a wrong encoding (nodejs)

### ISSUE THREAD

**Issue by StroginA** [motdotla/dotenv#657]
I have created an .env file in utf16-LE and was unaware of it. When trying to parse it (using the default encoding option of utf8), dotenv did not raise any errors neither in `require('dotenv').config().error`, not when using `{ debug: true }`. Instead, `require('dotenv').config().parsed` was simply empty. This was frustratingly difficult to track down.

**Comment by anthonyshibitov** [comment]
I'll take a stab at this.
