### ISSUE TITLE
Unable to find environment variables when they are stored outside of the "start" context

### ISSUE THREAD

**Issue by womjdmg** [motdotla/dotenv#659]
file structure 

package.json
.env
packages/
--project1/
----package.json 
----start.js  (this is where we call `dotenv.config()`)

cannot find the .env file if the start command is run from the package.json in project1.

If we use a start command `node packages/project1/start.js` in the outer directory the environment variables are loaded fine.

**Comment by JR33D** [comment]
You need to provide the path to the .env in the config method documentation here: https://github.com/motdotla/dotenv#path

code example:
`require('dotenv').config({ path: '/custom/path/to/.env' })`

**Comment by shellscape** [comment]
It would be a pretty simple add for the package to use something like https://www.npmjs.com/package/find-up

**Comment by shellscape** [comment]
@motdotla I think at this point you should amend the readme that dotenv is considered stable and has entered maintenance. I haven't seen you welcome a significant change in some time. It would be disingenuous to accept feature issues/requests when most, if not all, will be rejected with a similar response as made above

**Comment by shellscape** [comment]
@womjdmg @JR33D and anyone else who may need this functionality; a while back I created https://github.com/shellscape/dot/tree/master/packages/env which combined several dotenv packages along with find-up to resolve the shortcomings of this package. You may find it useful.

**Comment by motdotla** [comment]
dotenv has been stable since the year 2015. We've certainly added many features since then but rejected many more.
