### ISSUE TITLE
Multiline broken @16

### ISSUE THREAD

**Issue by vple** [motdotla/dotenv#664]
Hello, just wanted to report that multiline support seems to have been broken in v16.

With one of the sample values:

```
PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----
...
HkVN9...
...
-----END DSA PRIVATE KEY-----"
```

it seemed like only the first line was being parsed. `PRIVATE_KEY` was parsed to be `"-----BEGIN RSA PRIVATE KEY-----`.

Downgrading to v15 fixes the issue.

**Comment by melkir** [comment]
Reading https://github.com/motdotla/dotenv/compare/v15.0.1...v16.0.0 it looks like the [nodejs (multiline on)](https://github.com/dotenv-org/examples/tree/master/dotenv-nodejs-multiline) has been removed from the README. However it's still present at [tests/.env-multiline](https://github.com/motdotla/dotenv/blob/master/tests/.env-multiline).
Have you tried using backticks instead?

**Comment by fknop** [comment]
> The [regex](https://github.com/motdotla/dotenv/compare/v15.0.1...v16.0.0#diff-7934bf411fea192ad8cd69e0a12911648a2842cb0f2409a8fb67b41b7069d757R5) for detecting a line has been changed. Have you tried using backticks instead?

Same issue here, I've tried single quote, double quotes and backtick, nothing seems to work

**Comment by tonyxiao** [comment]
Maybe related, multi-line string inside `json` encoding is broken. So 
```
JSON=`{
      "url": "http://USxkrn19jZhcEqYhoRY7u1nc:c8863538-30c3-47dd-8eb0-bc1110d861a2@tntjwgn6wiu.SANDBOX.verygoodproxy.com:8080",
      "cert": "-----BEGIN CERTIFICATE-----\nMIID2..."
}`
```

Will turn into
```
JSON=`{
      "url": "http://USxkrn19jZhcEqYhoRY7u1nc:c8863538-30c3-47dd-8eb0-bc1110d861a2@tntjwgn6wiu.SANDBOX.verygoodproxy.com:8080",
      "cert": "-----BEGIN CERTIFICATE-----
MIID2..."
}`
```

Thus breaking the JSON

**Comment by motdotla** [comment]
i think many people have just been line wrapping. frustrating, i agree. working on the fix for this very soon. sorry it has been so long everyone.

**Comment by motdotla** [comment]
actually, multiline appears to be working correctly. tested [here](https://github.com/dotenv-org/examples/blob/master/usage/dotenv-nodejs-multiline/index.js) and [here](https://github.com/motdotla/dotenv/pull/803/files)

looking into

> multi-line string inside json encoding is broken

**Comment by motdotla** [comment]
JSON multiline encoding also looks good 👍

https://github.com/dotenv-org/examples/tree/master/usage/dotenv-nodejs-json

for others coming across this issue, possibly you are experiencing the issue with Docker. use [`dotenvx`](https://github.com/dotenvx/dotenvx) if you run into that problem.
