### ISSUE TITLE
.env variable parsed differently than shell exported variable

### ISSUE THREAD

**Issue by andreafspeziale** [motdotla/dotenv#666]
Hello and thanks for your hard work!

I jumped into a strange case in which using `NestJS` and specifically `ConfigModule` along with `Joi` an env variable is parsed differently if set in the `.env` file or is exported like it would be in a remote deployed env (`export MY_ENV=<value>`).

The `NestJS` founders suggested me to report here the issue https://github.com/nestjs/config/issues/1029.

By the way I created a sample repo in order to make it easy to debug.

https://github.com/andreafspeziale/env-issue-sample

**Comment by motdotla** [comment]
Interesting. For my future notes to address: https://github.com/andreafspeziale/env-issue-sample/blob/main/env/.env.test

**Comment by motdotla** [comment]
there are differences in other dotenv implementations across other frameworks and languages as well. we started going down the rabbit hole of trying to support all this and it is a task out of our hands. instead, we recommend using [`dotenvx`](https://github.com/dotenvx/dotenvx). it works everywhere and you will get the guaranteed same experience of nodejs' dotenv everywhere.
