### ISSUE TITLE
Unable to import module, CDN option?

### ISSUE THREAD

**Issue by msantamaria86** [motdotla/dotenv#669]
I have spend a lot of time trying a simple import of dotenv into my project and always getting 
`Uncaught TypeError: Failed to resolve module specifier "dotenv/config". Relative references must start with either "/", "./", or "../".`

Followed all the syntax styles shared here for it seems there is something wrong with configuration of my project, since I am only able to use relative paths.
I have 2 more modules (its a very simple project) with the same issue, I was only able to import them using the URL CDN path. What CDN command should I use for dotenv? I was able to locate "https://www.jsdelivr.com/package/npm/dotenv" but not sure how to import it this way. Since I dont have a lot experience with it.

**Comment by humanfriend22** [comment]
There seems to be no CDN option since the source code uses the native `require` function. Can you specify exactly _how_ you're `import`ing the library?

**Comment by cheng-alvin** [comment]
Hey there!
Try to import it like this if you are using ES6:

```js
import { config } from "dotenv";
// ...
```

**Comment by cheng-alvin** [comment]
Hope that helped!
