### ISSUE TITLE
override property does not exist in typing nor work

### ISSUE THREAD

**Issue by YungTosti** [motdotla/dotenv#677]
The documentation specifies to do the following for overriding environment variables:

`dotenv.config({ override: true });`

However looking at the typing this is not possible, and it also does not seem to work.... Help would be appreciated.

![image](https://user-images.githubusercontent.com/25297659/191008733-0f10898a-26cb-4622-a739-ffb176a35b63.png)

**Comment by rcolcleasue-eb** [comment]
I, too, am finding this to be an issue.

The docs mention `config({ override: true })` but the `config` method has no knowledge of an `override` method and simply reverts to simply logging a warning when a value exists.

![image](https://user-images.githubusercontent.com/113715524/191811362-b4b8a58a-2795-49fd-acfa-3c255a6c4b1c.png)

**Comment by motdotla** [comment]
The latest version(s) override here: https://github.com/motdotla/dotenv/blob/v16.0.3/lib/main.js#L81
