### ISSUE TITLE
Feature request: add method to serialize a .dotenv file

### ISSUE THREAD

**Issue by NPellet** [motdotla/dotenv#678]
For the first time I am faced with the simple issue of having to write down a .env file from a javascript object.
I can't find any library that does it, and to my surprise, including dotenv.

I can't imagine this would be very difficult, but I assume rules around multilines and escaping can be a bit annoying.

Hence my feature request.

If I have some time in the coming days I can take a crack at an implementation

**Comment by corvec** [comment]
Hi @NPellet, it looks like https://github.com/SpaceK33z/dotenv-filter-cli does what you want.

**Comment by motdotla** [comment]
Thanks for the suggestion @corvec.

You could also use this: https://jsontoenvironmentconverter.azurewebsites.net/ (don't use for sensitive values!) or this `jq` https://stackoverflow.com/questions/69129762/how-can-i-convert-json-to-an-environment-variable-file-format
