### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by titoworlddev** [motdotla/dotenv#679]
I don't know what the problem is, but I tried to set dotenv and my environment variables, but when I run my project, I get this error saying "require is not defined"

This is how I have it configured, as the README says:
![code](https://user-images.githubusercontent.com/70041483/191489974-caf50ff0-46d0-4278-ba57-e6c3de380075.png)

This is my env file
![env](https://user-images.githubusercontent.com/70041483/191490740-6cda0a59-d4ef-4e8c-a328-8c775de22fde.png)

I have already checked that my package.json is not using modules.
So I don't understand what is happening, nor why in all the videos and pages it is always configured the same but it doesn't work for me...

If someone could help me I would really appreciate it

**Comment by AroLeaf** [comment]
the code on the top looks to be browser code, which can't import code from your `node_modules` folder directly

**Comment by titoworlddev** [comment]
> the code on the top looks to be browser code, which can't import code from your `node_modules` folder directly

How could I import it then? It's just that I'm pretty new to web development and there are a lot of things I don't know how to do.

**Comment by AroLeaf** [comment]
not, you should use dotenv in your server code if any, not your browser code
