### ISSUE TITLE
Dotenv doesn't work when .env is missing?

### ISSUE THREAD

**Issue by danawoodman** [motdotla/dotenv#68]
For some reason the behavior of `dotenv` seems to have changed to require a `.env` file to exist, which breaks code in environments like Heroku. I'm getting the following when pushing a new Heroku app:

```
Error: Cannot find module 'dotenv'
```

Only way around it as far as I can tell it to wrap it in a conditional to only load on development.

Seems to me `dotenv` should silently fail if no `.env` exists. Thoughts?

**Comment by maxbeatty** [comment]
@danawoodman if you pass the [silent option](https://github.com/motdotla/dotenv#silent) that [error will not be logged](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L37-L42)

**Comment by jcblw** [comment]
@danawoodman do you have `dotenv` in a devDependecy that error you getting is that its not installed. This can happen if your `NODE_ENV` is set to `production`.

**Comment by danawoodman** [comment]
@jcblw that was it! Had it as a devDependency without realizing it. Thanks! :+1: 

@maxbeatty thanks for the heads up about output!
