### ISSUE TITLE
How to integrate with npx usage and node's --require?

### ISSUE THREAD

**Issue by herodriguez7** [motdotla/dotenv#681]
Hello,

Am trying to get dotenv's ENV vars to work when using npx to launch Playwright e2e tests but am not having any luck!

`SET "DEBUG=pw:api" && npx -c "-r dotenv/config DOTENV_CONFIG_PATH=STAGE.env DOTENV_CONFIG_DEBUG=true" playwright test ./apps/organization-e2e/tests "--config=./apps/organization-e2e/playwright.config.ts"`

Any ideas? I know your docs talk specifically about using node to launch the app.

In advance, thank you!

**Comment by CanRau** [comment]
was just looking for integrating with npx as well 🙌

**Comment by herodriguez7** [comment]
I'm no NodeJS developer by any stretch of the imagination but I was reading up the docs on npx and the --call commandline switch caught my eye but I've not been able to get it to work correctly.

I'm hoping it's possible.

I'm trying to figure out a way to get my playwright tests to use a diff't env file w/o having to actually modify the code and just pass it in or override it via the Window's commandline. Maybe this'll work better or easier on Mac OS X or even linux for that matter.

I get the feeling that dotenv is not Windows friendly. Maybe that's the issue?

**Comment by CanRau** [comment]
As an alternative maybe you'll be able to use https://stackoverflow.com/a/54812256/3484824
That's what I do now 💁🏻‍♂️

**Comment by herodriguez7** [comment]
Gracias @CanRau!

**Comment by CanRau** [comment]
Un placer espero que te sirvió 🙌

**Comment by herodriguez7** [comment]
Hey @CanRau I came around to this eventually. I got this to work without adding an npm run script by doing it this way:

`SET "DOTENV_CONFIG_PATH=\path\to\env\file" && node -r dotenv/config node_modules\playwright-core\lib\cli\cli test -c path\to\playwright.config.ts path/to/tests/*.spec.ts --headed` if that's of any use to you.

The paths are all relative to the CWD from whence you are calling the command so you may need to make them absolute paths but I did not. I prefer the relative path approach.
