### ISSUE TITLE
\r added to value parsed

### ISSUE THREAD

**Issue by gaetan-hexadog** [motdotla/dotenv#683]
All my `.env` value has `\r` added at the end of the line.

I tried to convert endline to LF / CRLF / LF ... but nothing change. There is always a \r added to the end of the environment value when parsing.
Because of this my application (smart contract using hardhat) does not recognize values passed.

How can I fix that? I'm using dotenv v16.0.3

Workaround I found is to call `trim()` on `process.env` value.

Example:
```js
process.env.NETWORK_MAINNET_PRIVATE_KEY?.trim()
```

**Comment by motdotla** [comment]
This means you have a hidden \r in your `.env` file. Try creating a new one from scratch or removing the hidden character from that file.
