### ISSUE TITLE
Is there anyway to customize the configFilePath for env files to something other than project.root?

### ISSUE THREAD

**Issue by kjhangiani** [motdotla/dotenv#69]
var configFilePath = path.join(project.root, '.env');

In my environment, I'd like to customize this path to something besides project root.  Any plans to include this, or reasons that this is a bad idea?

**Comment by jcblw** [comment]
we already have this https://github.com/motdotla/dotenv#path

```javascript
require('dotenv').config({
  path: project.root 
});
```
