### ISSUE TITLE
composite variables don't work 

### ISSUE THREAD

**Issue by davidsielert** [motdotla/dotenv#70]
seems like according to the docs that something like this 
BASE_DIR=/var/www/modular_api
APP_SRC_DIR=${BASE_DIR}/src
APP_DIST_DIR=$BASE_DIR/dist/

should work however both both of the last 2 vars are blank ..

**Comment by jcblw** [comment]
In the README there are no composite variables.

We had tried to add these feature before #52 but there was a lot of edge cases that kept happening. I know ultimately it was pulled. I think the consensus was that this feature was not essential enough to have to maintain all these edge cases. @motdotla  or @maxbeatty can probably expand upon this.

**Comment by maxbeatty** [comment]
composing variables are best left to JavaScript (or some other language) and _really_ expand the scope of this module. Given the example variables you're trying to construct, you could do something like:

```
BASE_DIR=/var/www/modular_api
SRC_DIR=/src
DIST_DIR=/dist/
```

```js
require('dotenv').config()

process.env.APP_SRC_DIR = process.env.BASE_DIR + process.env.SRC_DIR
process.env.APP_DIST_DIR = process.env.BASE_DIR + process.env.DIST_DIR
```

Existing languages like JavaScript and Bash are really, really good at composing variables. dotenv is fairly good at reading a file and assigning environment variables based on its content. Combing the two should allow you to do just about anything.

**Comment by motdotla** [comment]
@jcblw and @maxbeatty say it well. Closing this.

**Comment by NickTomlin** [comment]
I understand the complexity here (and the desire to avoid edge cases) but I wonder if it would be worth approaching this again?

The ruby and PHP dotenv libraries both provide this functionality:

https://github.com/bkeepers/dotenv#usage
https://github.com/vlucas/phpdotenv#nesting-variables

**Comment by maxbeatty** [comment]
@NickTomlin you're welcome to open a PR with the added functionality. New test cases are especially helpful. My biggest concern is that the implementation needs to be safe for people not using nested variables.

One major scenario I haven't been able to wrap my head around is distinguishing between `$(whoami)` or `${BASE_DIR}` as a variable versus a plain value. I've used dotenv a lot for API keys which are typically random strings I can't control. Those random values run the risk of matching a RegExp that could be interpreted as a nested variable. I'm open to ideas on how to solve that problem.

**Comment by NickTomlin** [comment]
@maxbeatty Thanks for the response!  I understand that this would require excellent test coverage; it would be awful to break it for folks just wanting the simple implementation. 

The nesting does get a little mind-bending. I don't have any great solutions of the top of my head but I was intending to start by blatantly ripping off the ruby implementation (since that one is very battle-tested).

I will add this to my stack of projects which will hopefully free up in a few weeks :)
