### ISSUE TITLE
Can't `import 'dotenv/config'` be used?!

### ISSUE THREAD

**Issue by aradalvand** [motdotla/dotenv#704]
In [this commit](https://github.com/motdotla/dotenv/commit/228c7b449dd9adfa93447ba74c8bf894db3068e5), the following line in the READM.md file:
```js
import 'dotenv/config';
```
Was changed to:
```js
import * as dotenv 'dotenv';
dotenv.config();
```
I was curious why? No explanation was provided in that commit. The first approach seems to work just as well and it's also much more concise. What was wrong with it?

Thanks.

**Comment by aradalvand** [comment]
I would appreciate a little hint here. Thanks.

**Comment by rbrtmrtn** [comment]
+1, though I would expect this to be `import dotenv from 'dotenv'`, more canonically.

**Comment by codelover2k** [comment]
you can also do 
```js
import { config } from 'dotenv';

config();
```

**Comment by stefan0001** [comment]
Hi, 

for me the "valid" example from https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import is not working anymore.
I guess it was working because `import 'dotenv/config';` is doing the `config()` directly while loading the module. 
So for me 
```
// errorReporter.mjs
import { Client } from 'best-error-reporting-service'

export default new Client(process.env.API_KEY)

// index.mjs
import * as dotenv from 'dotenv'
dotenv.config()

import errorReporter from './errorReporter.mjs'
errorReporter.report(new Error('documented example'))
```
while `config()` is called after importing `'best-error-reporting-service'`

**Comment by motdotla** [comment]
This has been patched here: https://github.com/motdotla/dotenv/commit/d2f166ae080859bccc02eee291c622b3a37cd315

**Comment by elizatlawy** [comment]
None of these methods works for me, using node `v14.18.3`

**Comment by motdotla** [comment]
Security support for node 14 end 3 months ago. Are you able to upgrade your node version @elizatlawy ?

ref: https://endoflife.date/nodejs
