### ISSUE TITLE
dotenv import error handling seems not ideal

### ISSUE THREAD

**Issue by andymel123** [motdotla/dotenv#705]
I had the problem, that after adding dotenv-expand importing of env variables did not work anymore when starting in a linux docker image (in my windows dev environment it still worked). 

I changed the `import 'dotenv/config';` to `import dotenv from 'dotenv';` to later use `dotenv` for the expand call.

Full code after change
```
import dotenv from 'dotenv';
import dotenvExpand from 'dotenv-expand';
dotenvExpand.expand(dotenv.config());
```

After some hours (it worked in my dev environment so the feedback cycles were longer) I found [this comment](https://github.com/motdotla/dotenv/issues/361#issuecomment-469187488)

So **with `import 'dotenv/config` the dotenv library reads the env variable `DOTENV_CONFIG_PATH` but with `dotenv.config()` it does not**.

When you **log the returned value of dotenv.config()** you get the info that would have saved me some hours `{"error":{"errno":-2,"syscall":"open","code":"ENOENT","path":"/app/.env"}}`. 

I did not know I have to read out this value to recognize problems with dotenv loading, also **'error' is not part of the types**. I do it like this now to recognize problems in the future

```
if ((dotenvConfig as any)["error"] != null) {
  throw new Error(`dotenv states an error: ${JSON.stringify(dotenvConfig)}`);
}
```

I think **this could be improved to get better feedback**.

**Comment by motdotla** [comment]
Thanks for bringing this up. We'll try and clarify that edge case soon.
