### ISSUE TITLE
dotenv/safe as replacement for dotenv-safe

### ISSUE THREAD

**Issue by karlhorky** [motdotla/dotenv#709]
Hi @motdotla, first of all, thanks so much for creating and maintaining `dotenv`! 🙌 It's a great tool, and our students get a lot of value from it.

I wanted to test the waters with how open you would be to absorbing the functionality of [`dotenv-safe`](https://www.npmjs.com/package/dotenv-safe) (to verify that all keys from `.env.example` have matching keys in the `.env` file) under a separate, opt-in import path, eg:

```ts
require('dotenv/safe').config()
// or
import * as dotenv from 'dotenv/safe'
```

`dotenv-safe` is no longer maintained (last publish 3 years ago) and [depends on a very old version of `dotenv`](https://github.com/rolodato/dotenv-safe/issues/128).

It seems like most of the functionality of `dotenv-safe` is [here](https://github.com/rolodato/dotenv-safe/blob/1ab395c2045bc8a2737da1a683cb6d56605a08f4/index.js#L21-L48).

It seems like a good number of `dotenv` users are using this `.env.example` paradigm in the wild:

- https://github.com/motdotla/dotenv/issues/437

This would enable those users to also verify that their `.env` file configures all of the environment variables from `.env.example` file that is committed to version control. This can prevent things like an unconfigured environment variable causing a production runtime error. I know there are alternatives to using `.env.example` including eg. sharing encrypted secrets, but the `.env.example` pattern is simple, relies more on existing tools and workflows, and is widely used.

**Comment by chav-aniket** [comment]
+1 to this absolutely would love this feature in dotenv

**Comment by tenlisboa** [comment]
@karlhorky I forked the [`dotenv-safe`](https://github.com/rolodato/dotenv-safest) and created a separated package with the updated dependencies, so we can maintain this package, until it's not a part of dotenv core module.

Check it out: [dotenv-safest](https://www.npmjs.com/package/dotenv-safest)

**Comment by motdotla** [comment]
Awesome. Thank you @tenlisboa!

**Comment by karlhorky** [comment]
@motdotla are you open to bringing this into `dotenv` core too at some point?

**Comment by motdotla** [comment]
Yes definitely but not prioritizing just yet. There are many upvotes for it as well.

**Comment by tenlisboa** [comment]
@motdotla If you don't mind, I can incorporate that feature, and you can only review, validate and merge. What do you say?

**Comment by motdotla** [comment]
i reached out to the founder @rolodato over email to see if i could take over maintenance. that would be preferable.

**Comment by karlhorky** [comment]
@motdotla Does it make sense to close this now?

Specifically now that @rolodato has [returned to maintaining `dotenv-safe` and made `dotenv` a peer dependency](https://github.com/rolodato/dotenv-safe/issues/128#issuecomment-1930553844)?

> `dotenv-safe` 9.0.0 is now published to npm and has `dotenv` as a peer dependency. Closing, thanks all for the input!
