### ISSUE TITLE
Uncaught ReferenceError: process is not defined  when i am using .env file that time i am facing this issue

### ISSUE THREAD

**Issue by ajshilshatech** [motdotla/dotenv#710]
REACT_APP_BASE_URL =hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
this my .env file

"scripts": {
    "dev": " env-cmd -f .env vite",
    "build": " env-cmd -f .env vite build",
    "preview": "vite preview"
  },

this is my package.json

 console.log(process.env.REACT_APP_BASE_URL,'env file ')
I am accessing other components
that time show me react-dom.development.js:26923 Uncaught ReferenceError: process is not defined

**Comment by sumeetadur** [comment]
@ajshilshatech Vite exposes the env variables with `import.meta.env` instead of `process.env`, and the variables need to start with `VITE_` instead of `REACT_APP_`, unless you're using a plugin like [vite-plugin-env-compatible](https://github.com/IndexXuan/vite-plugin-env-compatible)

**Comment by egomezbpedro** [comment]
This Issue seems that can be safely close.
