### ISSUE TITLE
Supporting Escape Sequences

### ISSUE THREAD

**Issue by bd82** [motdotla/dotenv#711]
Hello @motdotla  and thank you for creating dotenv nodejs library 👍 

## Feature Request

Could dotenv nodejs library support escape sequences (e.g `\" \t`) ?

At the minimum can it be aligned with the Ruby dotenv library?
- [version 2.8.0](https://github.com/bkeepers/dotenv/releases/tag/v2.8.0) added https://github.com/bkeepers/dotenv/pull/421

**Would a PR which aligns with the Ruby library be welcome?**

## Context
I've noticed some implementations of dotenv support character escapes and some do not.
Also there does not seem to be an official specification anywhere for dotenv.
This is causing issues when we need to use the same `.env` files in multiple runtimes.

Is the Ruby library the **original** implementation and thus also used as the **pseudo specification**?

### [Ruby Library](https://github.com/bkeepers/dotenv)
- Supports escaping anything other than `$`
- Only interpret values of `\n` and `\r` and only in double quoted strings.
- [Relevant Source Code](https://github.com/bkeepers/dotenv/blob/0974810e909076cc34d5579ac119c9422e5f64b1/lib/dotenv/parser.rb#L74-L94)

### [Elixir Library escaping specs](https://hexdocs.pm/dotenvy/dotenv-file-format.html#escape-sequences)
- Seems to allow expanding of more special sequences versus the Ruby library, e.g: `\t` and `\f`
- Does not seem to distinguish (at the spec level at least) between single or double quotes escape values.

### [Python Library](https://github.com/theskumar/python-dotenv#file-format)
- ```
     Allowed escape sequences:

    in single-quoted values: \\, \'
    in double-quoted values: \\, \', \", \a, \b, \f, \n, \r, \t, \v
  ```

**Comment by ritschwumm** [comment]
interestingly, the LINE regexp already does understand backslashed in front of single quote, double quote and  backtick...

**Comment by motdotla** [comment]
a summary of each of these escape sequences for others happening across this issue:

1. **`\a`**: **Bell (alert)**  
   - Produces a bell sound or alert in some systems (mostly obsolete in modern consoles).

2. **`\b`**: **Backspace**  
   - Moves the cursor back by one position (doesn't delete the character in many environments).  
   - Example: `print("ABC\bD")` → Output: `ABD`.

3. **`\f`**: **Form feed**  
   - Advances the cursor to the start of the next "page" (useful in old-style printers).  
   - Example: `print("Hello\fWorld")`.

4. **`\n`**: **Newline**  
   - Moves the cursor to the beginning of the next line (common line-break character in Unix/Linux).  
   - Example: `print("Hello\nWorld")`.

5. **`\r`**: **Carriage return**  
   - Moves the cursor to the beginning of the current line (used with `\n` for Windows line endings, `\r\n`).  
   - Example: `print("Hello\rWorld")` → Output: `World` (overwrites "Hello").

6. **`\t`**: **Horizontal tab**  
   - Inserts a tab (spaces equivalent to a tab width, typically 4-8 spaces).  
   - Example: `print("Hello\tWorld")`.

7. **`\v`**: **Vertical tab**  
   - Advances the cursor vertically without moving horizontally (rarely used today).  
   - Example: `print("Hello\vWorld")`.


in context of dotenv and dotenvx, `\\`, `\'`, `\"`, `\n`, `\r` are already supported.

`\a`, `\b`, `\f`, `\v` are not needed for a `.env` file's use case so I'm not going to support those.

but `\t` is useful. i'm adding support for that to [dotenvx](https://github.com/dotenvx/dotenvx) now.
