### ISSUE TITLE
Set multiple environment variables to the same value

### ISSUE THREAD

**Issue by andrewfrankcare** [motdotla/dotenv#712]
Thanks for your work on the project!

I find myself in a situation where I need to (unfortunately) pass the same string to two differently named environment variables. I know I could use dotenv-expand to do this, but it seems like a simpler way to do this would be:

VAR1=VAR2="value"

Any thoughts on this?

**Comment by ritschwumm** [comment]
https://github.com/motdotla/dotenv-expand looks like it might helo with that

**Comment by motdotla** [comment]
Please use dotenv-expand for this.
