### ISSUE TITLE
terminal command override .env file bug

### ISSUE THREAD

**Issue by xgqfrms** [motdotla/dotenv#716]
# terminal command override .env file bug

> why the terminal command will override `dotenv.config()` ?

## codes

`.env`

```env
OPENAI_API_KEY=1
BUG=true
```

`index.js`

```js
const dotenv = require('dotenv');
console.log(`dotenv =`, dotenv.config());

// console.log(`env =`, process.env);

// terminal command override .env file bug ❌
console.log(`OPENAI_API_KEY =`, process.env.OPENAI_API_KEY);
console.log(`BUGf =`, process.env.BUG);
```

```sh
# set env variable
$ export OPENAI_API_KEY=1234567

# test
$ node ./index.js
```

<img width="513" alt="image" src="https://user-images.githubusercontent.com/7291672/217875627-1e837933-5e3a-4e27-af5e-154ed8d0c943.png">

**Comment by Moonshine27156** [comment]
Àß thé y. On my M. Ca


Ím liñdsey maxfield aka liñsey j.p. S. Ís on asSEREÑÍTy spriñg clamps  iñ sterilizatíon. C clampß, ón àpartments. Dóors  às DERAILED trañé freíght cars wíth welded uñit àírécóndítíoñng,

**Comment by Moonshine27156** [comment]
SAFP, DEPARTMENT GROWTH EXPANSIONS AND MALL FÓOD AS COURTS, DATES... IN CHAPERONES, AS MY STÓRY IS MADE ÍN:, THE AÇCESS ÍS ÓN THE RIGHT SÍDE ÍÑ TAG REGÍSTER CÑ RN SN DN ALL A+J, TO IT AÑD K+ Z TO IT. AS 5'S, 4' S, 3' S 2, 'S 1'S AS IF THE ALPHADEX STEMS ÓUV ÓVU OYY ÓYU OYV ÓVV THEMSELVES. ÑOTE; ELVEÑ  ÍTS MY ELEVEN ON DL. 113456971, 117965⁴³1.

**Comment by Moonshine27156** [comment]
Go FIGURE THEN CLEAR YOURSELF THOSE ON  A REAL CALCULATIVE INATEAD OF CHECKING ACCOUNTS ON A CHECK BOOK ICANADDA, DER DE DERRRR
