### ISSUE TITLE
Feature Suggestion: Generate .env file for specific environment by "switching env" after install

### ISSUE THREAD

**Issue by IMalyugin** [motdotla/dotenv#721]
**Prerequisites:**
Been using `dotenv` for quite some time now, had to rewrite quite a few times:
1. Used single `.env` file with a `.env.template`, that caused a lot of problems for new developers, who had to fill out `.env`, and another portion of troubles on CI;
2. Used `.env.${ENV}` files per environment, worked well, till i hit secrets, then I had to make two files `.env.secret.${ENV}` + `.env.${ENV}`, that got more complicated, also worked well till I hit some packages like prisma, that force you to use raw `.env`
3. Added default .env for localhost, didn't help much as during CI, we still need to wrap stuff up;
4. Switched to `dotenv-cli`, to run binaries with `dotenv -e .env.prod -e .env.secret.prod`, but that forces to rewrite a ton of `npm-scripts` clones for every environment, basically creating a mess from `npm-scripts`;

---

**Goal:**
To sum it up, what are we trying to achieve? We want everything to run well on localhost, dev, prod, and any other env, with least boilerplate possible. Thus it would be best to not reference concrete environment or `dotenv` files in `npm-scripts`, that also includes not using multiple `.env.{env} files`

---

**Feature Suggestion:**
With all the above in mind, why don't we pre-generate proper `.env` file with a dedicated binary? Everything would be using simple `.env` file, that is provided by nodejs developers.

A proper lifecycle could be this:
```
npm install
npm run dotenvgen production
npm run build
npm run serve
...etc
```

Basically we generate `.env` file for specific environment once with a script. For local development, we could just set `"postinstall": "dotenvgen localhost"`.

As to how, for single-env projects, containing:
```
.env.production
.env.dev
.env.localhost
```

It would simply copy `.env.dev` -> `.env`

As secrets is a common use-case, we could concat `.env.dev` + `.env.secret.dev` into a single .env file.

With this approach `dotenv` anti-pattern of using `.env.common` could become a good practice, as it would give you the flexibility without inheritance hell, after concatenation it would all be in one single file.

---

Wrote a code sample that does this without configuration option, in-case feature request never gets anywhere, feel free to use it:
```js
#!/usr/bin/env node

const path = require('path');
const fs = require('fs');
const { program } = require('commander');
const dotenv = require('dotenv');
const dotenvStringify = require('dotenv-stringify');

program
  .arguments('[args]')
  .parse();

const [env] = program.args;


const parseConfig = (envName, callback, fallback = null) => {
  const configPath = path.resolve(process.cwd(), `.env.${envName}`);
  if (!fs.existsSync(configPath)) return fallback;
  callback(configPath);
  return dotenv.parse(fs.readFileSync(configPath));
};


const composeUsageCollector = () => {
  const usages = [];
  return {
    register: (envName) => usages.push(envName),
    usages,
  };
};

/**
 * TODO-1: keep emptyLines, and comments (parse-dotenv)
 * TODO-2: group vars by comment and output clean joined result
 * TODO-3: group by dot-separated values
 * TODO-4: Add checksum and verification method
 * @param envName - string
 * @returns {EnvObject}
 */
const generateEnv = (envName) => {
  const usageCollector = composeUsageCollector();
  const config = parseConfig(envName, usageCollector.register);
  const secretConfig = parseConfig(`${envName}.secret`, usageCollector.register);

  const generatedConfigPath = path.resolve(process.cwd(), '.env');
  fs.writeFileSync(generatedConfigPath, [
    '# This config is automatically generated by dotgenv',
    `# From following sources: ${usageCollector.usages.map((configPath) => path.basename(configPath)).join(', ')}`,
    '# Please do not edit the file manually, to prevent change',
    '',
    dotenvStringify({
      ...config,
      ...secretConfig,
    }),
  ].join('\n'));
};

generateEnv(env);
```

**Comment by ritschwumm** [comment]
i haven't looked closely, but would using https://github.com/keithmorris/node-dotenv-extended help?

**Comment by IMalyugin** [comment]
I've used dotenv-extend before, it solves only the least problematic part: splitting configuration into multiple files.

The idea of switching env is more about actually generating .env file to avoid passing custom configuration everywhere.
Instead of processing env during script init time, we can do this much prior, like installation phase, or a separate script. That removes the need to pass hundreds of configuration options and integrating every package with dotenv-extend.

**Comment by motdotla** [comment]
I'm using a `.env.vault` file to solve this problem these days. 

We've recently added documentation to this repo around it.

Essentially the concept is:

1. Keep using a `.env` file for development (do NOT commit to code)
2. Put other values in `.env.ENVIRONMENT` files (do NOT commit to code)
3. Run `npx dotenv-vault local build` to build your encrypted `.env.vault` file (DO commit to code)
4. Use your `.env.keys` file to decrypt those (keep safe. these are the decryption keys that unlock a specific environment)

This makes it really easy to run your app in a different environment. Just run `DOTENV_KEY="<your decryption key>" node index.js`. The decryption key looks up the correct environment in your .env.vault file, decrypts it, and injects your environment variables and secrets into your app process.

**Comment by motdotla** [comment]
Here is a guide on it: https://www.dotenv.org/docs/languages/nodejs
