### ISSUE TITLE
Request to narrow types reference for node

### ISSUE THREAD

**Issue by shawnmcknight** [motdotla/dotenv#723]
Currently, the `main.d.ts` file in this package have the following triple slash directive, which brings in the entire set of typings for `@types/node`:
```ts
/// <reference types="node" />
```

However, referencing all of `@types/node` can have unanticipated side effects as it might bring the ambient declaration for all of the node types into scope. See this [gist](https://gist.github.com/RyanCavanaugh/702ebd1ca2fc060e58e634b4e30c1c1c) for a pretty good explainer of this issue from the TypeScript team.

I'd like to request that this directive be narrowed down to:
```ts
/// <reference types="node/buffer" />
```
since `Buffer` appears to be the only type that is used in the `main.d.ts` file from `@types/node`.  Although this will still bring the buffer types into scope, it will at least not bring the entirety of `@types/node` into scope.

I'm happy to submit a PR for this if you'd like.

**Comment by motdotla** [comment]
You have a good point but with Typescript and its many ongoing changes, we err on the side of least impact to dotenv users. So going to leave this as is for now to not cause any unintended side effects.
