### ISSUE TITLE
Override ENV VAR in dotenv: master conf from a dockerfile in runtime

### ISSUE THREAD

**Issue by karl18** [motdotla/dotenv#724]
Hi, I'm trying to alter some env VAR of dotenv (.env) file during runtime from a Dockerfile, Is this possible? 

Here are the changes that I added to the Dockerfile:

**Dockerfile**:

ARG SOURCE_BRANCH_NAME
ARG NODE_ENV
ARG ELASTIC_QUERY_PORTAL_BASE_URL
RUN echo "ELASTIC_QUERY_PORTAL_BASE_URL=$ELASTIC_QUERY_PORTAL_BASE_URL" >> .env
_also tried:_ RUN echo "$ELASTIC_QUERY_PORTAL_BASE_URL" >> .env

then I run using : docker run ** --build-arg SOURCE_BRANCH_NAME=master --build-arg NODE_ENV=production --build-arg ELASTIC_QUERY_PORTAL_BASE_URL=x_data/elastic-query-portal

here's **Output**:

```=> [build 10/17] RUN npm ci --no-optional --include=dev                                                                                                                      30.5s
 => [build 11/17] RUN env                                                                                                                                                      0.3s
 => [build 12/17] RUN echo "ELASTIC_QUERY_PORTAL_BASE_URL=<x_data>/elastic-query-portal" >> .env  --> x_data: the desired url that i need to set inside the variable                                                  0.3s
 => ERROR [build 13/17] RUN npm run build                                                                                                                                     50.3s
------
 > [build 13/17] RUN npm run build:
#23 0.921
#23 0.921 > webshop-client-app@1.0.0 build
#23 0.921 > webpack
#23 0.921
#23 2.989 config: {
#23 2.989   dotenv: 'master',
#23 2.989   ELASTIC_QUERY_PORTAL_BASE_URL: '<y_data>/elastic-query-portal', ``` ---> here I should see x_data

```

But I'm always seeing the configuration of the dotenv: master as per the branch that I'm using in this case. 
When the branch name is set to master | NODE_ENV=production, it has a specific configuration which I want to override with the ENV ELASTIC_QUERY_PORTAL_BASE_URL in the Dockerfile, Is this possible ?

I appreciate your response.

**Comment by karl18** [comment]
I appreciate any response on this issue .. thx! :))))

**Comment by ritschwumm** [comment]
try setting `DOTENV_CONFIG_OVERRIDE=""` in the environment to prevent dotenv from overriding existing environment variables with values from the `.env` file

**Comment by karl18** [comment]
I'm trying in a Dockerfile, but setting this `DOTENV_CONFIG_OVERRIDE=""` as an env var didn't change much.
Am I understood correctly ?

**Comment by ritschwumm** [comment]
i know if the node process running inside docker sees `process.env.DOTENV_CONFIG_OVERRIDE === ""`  here https://github.com/motdotla/dotenv/blob/master/lib/env-options.js#L16 then this line https://github.com/motdotla/dotenv/blob/master/lib/main.js#L81 will prevent dotenv from overwriting an existing value in `process.env` with a new value it read from a `.env` file.

if course this requires that `env-options.js` was actually used, but if you use `import "dotenv/config";` as recommended until recently, then it will be.

sorry, i was (deliberately) imprecise concerning what to put in the dockerfile - i don't know off the top of my head.

maybe just add something like `console.log("override <" + process.env.DOTENV_CONFIG_OVERRIDE + ">");` and if you see it printing `override <>` you should be able to set environment variables without them being overwritten by dotenv.

**Comment by ritschwumm** [comment]
sorry, it seems DOTENV_CONFIG_OVERRIDE is irrelevant to your problem: i just double-checked,  and `DOTENV_CONFIG_OVERRIDE` does not seem to work the way i remembered it to. at least in the current version, dotenv does leave values existing inr process.env alone by default, even if there is a conflicting value in the .env file.

**Comment by karl18** [comment]
Hi @ritschwumm Thanks for double-checking, I'm not sure if i can overcome this issue if possible ?

**Comment by ritschwumm** [comment]
well, if you somehow

a) get the ELASTIC_QUERY_PORTAL_BASE_URL set in a way that the node process gets to see it, and 
b) ensure https://github.com/motdotla/dotenv/blob/master/lib/env-options.js is ran (early enough)

then the rest should be purely a docker issue. 

i don't know enough about docker to tell you exactly what to do there - in a docker-compose.yaml something like this works just fine:
```
service:
    environment:
        ELASTIC_QUERY_PORTAL_BASE_URL: "test"
```
