### ISSUE TITLE
Official way of importing with ES6 modules no longer works

### ISSUE THREAD

**Issue by Zirafnik** [motdotla/dotenv#727]
Hey folks,
according to the official docs, you're supposed to ES6 import `dotenv` the following way: 
```js
import * as dotenv from 'dotenv';
dotenv.config();
import 'anotherModuleThatUsesProcessEnv';
```
Unfortunately, this has not worked in my case, because the other module which I import (where I already want to use `process.env.VARIABLE`), has no access to them yet. 

I believe reading somewhere, that ES6 imports are hoisted, so the `anotherModuleThatUsesProcessEnv` gets executed before the `dotenv.config()` ?

The old way of solving this problem seemed to work for me:
```js
import 'dotenv/config';
import 'anotherModuleThatUsesProcessEnv';
```
I would encourage for somebody to look into this and perhaps update the docs.

Node version: v16.10.0;
Framework: "express": "^4.18.2";

**Comment by Zirafnik** [comment]
Related: https://github.com/motdotla/dotenv/issues/704#issue-1500562505

**Comment by bambooom** [comment]
I'm using Node version v18.14.1, your solution `import https://github.com/motdotla/dotenv;` is not working for me either.... 😢

**Comment by motdotla** [comment]
README has been updated here: https://github.com/motdotla/dotenv/commit/d2f166ae080859bccc02eee291c622b3a37cd315
