### ISSUE TITLE
Problems after installation

### ISSUE THREAD

**Issue by avrit** [motdotla/dotenv#740]
![Screenshot from 2023-05-28 17-27-00](https://github.com/motdotla/dotenv/assets/19571465/f96c6b22-ddf0-42f9-93df-b8ce3c9d15b6)

**Comment by motdotla** [comment]
Hi @avrit, 

Install [dotenv@16.1.0-rc2](https://www.npmjs.com/package/dotenv/v/16.1.0-rc2)

```
$ npm install dotenv@16.1.0-rc2 --save
```

Does the resolve the issue for you?

**Comment by motdotla** [comment]
Are you still getting resolve os failure or `resolve crypto` failure? I missed adding `crypto: false` to the browser support in package.json.

Can you try installing from this sha directly?

https://github.com/motdotla/dotenv/pull/742

```bash
npm install motdotla/dotenv#cb9a51a9ca46455fcdc5f6c93741acc1dfb4938d
```

Related: https://github.com/motdotla/dotenv/issues/741

**Comment by motdotla** [comment]
`v16.1.1` should fix this. If it does not, let me know and I will reopen.
