### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by murluki** [motdotla/dotenv#741]
When calling dotenv keeps throwing this error regardless of npm library version:

**Module not found: Error: Can't resolve 'fs' in** 

I have installed and upgraded fs as well.

**Comment by motdotla** [comment]
Hi @murluki, are you using this on front-end only code? Try installing [dotenv@16.1.0-rc2](https://www.npmjs.com/package/dotenv/v/16.1.0-rc2)

```
$ npm install dotenv@16.1.0-rc2 --save
```

Does that resolve the issue for you?

**Comment by murluki** [comment]
> Hi @murluki, are you using this on front-end only code? Try installing [dotenv@16.1.0-rc2](https://www.npmjs.com/package/dotenv/v/16.1.0-rc2)
> 
> ```
> $ npm install dotenv@16.1.0-rc2 --save
> ```
> 
> Does that resolve the issue for you?

Thank you for your reply! 

Not really. I am still getting the following error even after installing crypto module and updating the webpack accordingly:

ERROR in ./node_modules/dotenv/lib/main.js 4:15-32
Module not found: Error: Can't resolve 'crypto' in '/Users/murluki/Desktop/payroll_v2/node_modules/dotenv/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

**Comment by motdotla** [comment]
v16.1.1 should fix this. If not, let me know and I will reopen.

**Comment by motdotla** [comment]
@murluki I'm pushing a patch shortly that will return this error to you. But it is by design.

You should be adding in a polyfill for front-end code. See the following: https://github.com/dotenv-org/examples/blob/master/dotenv-webpack3/webpack.config.js

Or ideally, your front-end code should not be calling require('dotenv'). That should happen on the node side only in your webpack.config.js. Putting require('dotenv') on front-end webpacked code is a smell.

**Comment by murluki** [comment]
@motdotla thank you, will try it out. I really appreciate such detailed feedback :)
