### ISSUE TITLE
Add Bower Support 

### ISSUE THREAD

**Issue by edmondchui** [motdotla/dotenv#75]
Could you please add bower.json for bower install? Thanks.

**Comment by maxbeatty** [comment]
Can you elaborate on how you're using bower and why npm isn't a suitable package manager? dotenv is intended to be used on the server and I've always viewed bower as a package manager for client-side packages. You could have a totally valid scenario. I'd just like to learn more before doing anything

**Comment by jcblw** [comment]
How would you see using this with bower? I thought bower was a frontend package manager, where dotenv is server side.

**Comment by edmondchui** [comment]
Thanks for your clarifications.
