### ISSUE TITLE
DotenvConfigOptions interface missing new processEnv field

### ISSUE THREAD

**Issue by JstnMcBrd** [motdotla/dotenv#755]
TypeScript gives the following error when trying to use the new `processEnv` option:
![image](https://github.com/motdotla/dotenv/assets/28303477/24781db9-242a-4956-aa5b-c096a3d1d875)

I believe this is because the interface for `DotenvConfigOptions` in [main.d.ts](https://github.com/motdotla/dotenv/blob/master/lib/main.d.ts#L22) does not include the `processEnv` field yet.

Until this is fixed, simply asserting the type is a valid workaround.
![image](https://github.com/motdotla/dotenv/assets/28303477/6e3b65a4-1cbe-4f82-bd43-326c41914407)

**Comment by motdotla** [comment]
Thank you. Repairing this now. The new `DOTENV_KEY` option is also missing from the type file.

**Comment by motdotla** [comment]
A couple examples added here:

* https://github.com/dotenv-org/examples/tree/master/dotenv-typescript-custom-target
* https://github.com/dotenv-org/examples/tree/master/dotenv-vault-typescript-custom-target

Released as `16.3.1`

**Comment by motdotla** [comment]
https://github.com/motdotla/dotenv/pull/756

https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1631-2023-06-17
