### ISSUE TITLE
Can't configure port

### ISSUE THREAD

**Issue by forkiven** [motdotla/dotenv#76]
Is it possible to configure PORT in a .env file? Tried for a while and gave up, is this a known issue?

**Comment by jcblw** [comment]
no know issue? It should work can you give an example that does not work?

**Comment by forkiven** [comment]
Sure thing,
I've got:

production.env
DB_USER=root
PORT=80

app.js
```javascript
if(config.env === 'production') {
  require('dotenv').config({path: './config/production.env'});
  // This works (root)
  console.log('DB user is: ' + process.env.DB_USER);
  // This is undefined
  console.log(process.env.PORT);
}
```

**Comment by maxbeatty** [comment]
I wasn't able to reproduce [here](https://gist.github.com/maxbeatty/d800de03a3e34986c043). If you could open a Pull Request with a failing test case, that would make it easier to address.
