### ISSUE TITLE
dotenv v16.3.1 giving off error with path, os and crypto packages being missing and or not working

### ISSUE THREAD

**Issue by KartikAroraOfficial** [motdotla/dotenv#763]
dotenv says the path, os and crypto packages are missing and needs to be replaced, the suggested update by the react app was to use following libraries as alternate to the ones already there 
![image](https://github.com/motdotla/dotenv/assets/90651659/b3b35123-c194-407a-ba07-967c7be4963e)

but upon further investigation, I just installed path and os packages

after that this is the current state of the app.

but crypto wouldn't install even when it's there in the packages.json

and would result in this error

![image](https://github.com/motdotla/dotenv/assets/90651659/c4a00a9b-7255-4557-bc56-f7edd41ad295)

to remedy it further I asked chatGPT what could be the possible fixes
it gave me the fix for webpack.config.js fix

![image](https://github.com/motdotla/dotenv/assets/90651659/1186d754-2bab-4d5c-a8f9-e2c56c49a434)

I added it in the root
still doesn't work at all.
please update the dependencies and reply with appropriate solution to it

**Comment by thisisnguyennhatquang** [comment]
I have the exact same issue.

**Comment by motdotla** [comment]
I believe you should be using node-polyfill-webpack-plugin. [source](https://github.com/dotenv-org/examples/blob/master/dotenv-webpack3/package.json)

If you run the following code what error do you receive:

```
git clone git@github.com:dotenv-org/examples.git
cd examples/dotenv-webpack3
npm install
npx webpack
node dist/bundle.js
```

If successful you should receive the response 'Hello World'

**Comment by KartikAroraOfficial** [comment]
Hi, Thanks for your answer.
I solved it by doing the following things after further analyzing why your suggested example worked 

It's just that the below package was missing and needed installing, and the above packages os, path, crypto had nothing to do

it's something that we need to install because of webpack >= 5

```
npm install node-polyfill-webpack-plugin
```

Thank You for your quick reply and resolution of this problem. Followed you up on Github ❤️!
