### ISSUE TITLE
Broken links on npmjs.com/package/dotenv page

### ISSUE THREAD

**Issue by alexander-mart** [motdotla/dotenv#764]
Broken links on npm page:
https://www.npmjs.com/package/dotenv

as-is (404):
https://github.com/dotenv-org/examples/tree/master/dotenv-nodejs

to-be:
https://github.com/dotenv-org/examples/tree/master/usage/dotenv-nodejs

**Comment by motdotla** [comment]
These have been updated in the README. When we release a new version npm will receive the updated README. Thank you for reporting.
