### ISSUE TITLE
ES6 import is not working with Node v14.18.3

### ISSUE THREAD

**Issue by elizatlawy** [motdotla/dotenv#766]
When I'm importing as explained n the documentation: 

`import 'dotenv/config' `

It does not work and the env variables do not get added to the  `process.env`

dotenv version: `16.3.1`
Node.js version: `v14.18.3`

**Comment by AbhayDonga007** [comment]
i think you need to update your Node.js version.
In Node.js version **v18.16.0** it's working perfectly.

**Comment by paraschouhan15** [comment]
I have node version 18.18.0 but notworking good...
PORT GETTING **UNDEFINED**

**Comment by motdotla** [comment]
unable to duplicate this on more modern node versions. closing.
