### ISSUE TITLE
Support for Arrays?

### ISSUE THREAD

**Issue by decoursin** [motdotla/dotenv#77]
Hi, is their support for arrays? If so, what's the syntax like? Thank you.

**Comment by jcblw** [comment]
We can not set any thing other then strings to the `process.env` object. Those get type casted on the setter. Eg.

```shell
node -e "process.env.ALPHA=['a', 'b']; console.log(typeof process.env.ALPHA);"
# will be "string"
```

but you can do this.

```shell
# .env file
ALPHA=a,b,c,d
```

```javascript
require('dotenv').config();
var alpha = process.env.ARRAY_ALPHA.split(',');
``` 

Sorry.

**Comment by decoursin** [comment]
Sounds good thank you so much that might work well enough

**Comment by niftylettuce** [comment]
Hey guys I had this same issue so I built this plugin for `dotenv` at https://github.com/niftylettuce/dotenv-parse-variables.  Hope it helps 👍

**Comment by andywer** [comment]
Why not add support for a generic solution like this? Achieves the same, but in an explicit and non-breaking way.

```ini
# .env
HOSTS[]=localhost
HOSTS[]=example.com
```

**Comment by mckenzieja** [comment]
@andywer 

Has your implementation been tested working? I am considering your method.

**Comment by andywer** [comment]
Haven‘t actually implemented it. A simple workaround that doesn‘t require anything new: Put JSON in the variable and `JSON.parse()` or make it a comma-separated list of items that you can easily `.split(',')` 😉

**Comment by drummy2** [comment]
> Haven‘t actually implemented it. A simple workaround that doesn‘t require anything new: Put JSON in the variable and `JSON.parse()` or make it a comma-separated list of items that you can easily `.split(',')`

I think this then means you have to have it all on a single line?

**Comment by appsparkler** [comment]
Hello People, 

I wanted `JSON`.  This is what worked for me:

```
// .env.development
...
WEBPACK_HTML_PLUGIN={"template": "src/index.html", "filename":}
SOME_ARRAY=["hello", "world"]
...


// module-file.js (accessing the .env variable)
typeof JSON.parse(process.env.WEBPACK_HTML_PLUGIN); // object
Array.isArray(JSON.parse(process.env.SOME_ARRAY)) // true
```

Good Luck...
