### ISSUE TITLE
Example usage links not working

### ISSUE THREAD

**Issue by Emmo00** [motdotla/dotenv#772]
![image](https://github.com/motdotla/dotenv/assets/88244468/a7496593-3de5-4e22-a5bb-60f40fd12f01)

all links to example usage on the npm package page are not working. LInks on the package page are to `https://github.com/dotenv-org/examples/tree/master/<example>` instead of `https://github.com/dotenv-org/examples/tree/master/usage/<example>`

**Comment by motdotla** [comment]
they've been fixed on the github readme but we haven't released a new version yet so yes, on npm they are broken. sorry about that! will be updated when we release the next version.

**Comment by motdotla** [comment]
these are fixed on npm now as well
