### ISSUE TITLE
only the page with require("dotenv").config is seeing values

### ISSUE THREAD

**Issue by Daxcor69** [motdotla/dotenv#773]
I might have missed something in the instructions, I was under the impression that I only had to include the require only once on the entry page of my application, and then the process.env  (my values) would be available on all pages without requiring it on each page.  This doesn't seem to be the case.  Is this the expected default behavior?

I see the preload directive, is this how this is accomplished?

thanks
Brad

**Comment by Daxcor69** [comment]
nm I removed dotenv and went with a different solution.

**Comment by motdotla** [comment]
sounds good @Daxcor69. depending on your use case you also might find [`dotenvx`](https://github.com/dotenvx/dotenvx) more useful. it adds a lot of helpful `--debug` logging. also because it wraps your process and injects envs just in time it has much less edge cases like the one you experienced.
