### ISSUE TITLE
Can we throw or stop execution through .env?

### ISSUE THREAD

**Issue by chaitanya71998** [motdotla/dotenv#777]
Hi
I was having a use case to use CODEBUILD_BUILD_NUMBER and assign it to one of the environment variable in .env file of react. 

I want to stop execution from .env file making it as global source and throw error if there is no CODEBUILD_BUILD_NUMBER value  as this is only place where every time different accesses of build/executions happens.

**Comment by motdotla** [comment]
Isn't `CODEBUILD_BUILD_NUMBER` injected at runtime by AWS?

**Comment by motdotla** [comment]
you can always half in your code if you do something just like this after dotenv:

```js
if (!process.env.CODE_BUILD_NUMBER) {
  // throw error here/halt
}
```

**Comment by chaitanya71998** [comment]
> you can always halt in your code if you do something just like this after dotenv:
> 
> ```js
> if (!process.env.CODE_BUILD_NUMBER) {
>   // throw error here/halt
> }
> ```

this works!
