### ISSUE TITLE
Adding on to variables

### ISSUE THREAD

**Issue by cadebward** [motdotla/dotenv#78]
In the examples there are some basic variables. Im trying to create a `ROOT` variable and then add on to it like this: `CLIENT_PATH=${ROOT}/path/to/client`. Is this sort of thing supported?

**Comment by maxbeatty** [comment]
Unfortunately, combining variables is not supported. That's a job better left to your shell or node.

```javascript
require("dotenv").config()

Object.keys(process.env).forEach(function(v) {
  if (/_PATH$/.test(v)) {
    process.env[v] = process.env.ROOT + v
  }
})
```

**Comment by vivekdoshi2** [comment]
@maxbeatty ,

https://stackoverflow.com/questions/48781629/variable-assignment-withing-env-file
Is there any chances, that this feature will be included in future ?

Thanks.

**Comment by maxbeatty** [comment]
[dotenv-expand](https://github.com/motdotla/dotenv-expand) exists to solve this specific problem
