### ISSUE TITLE
override system variables

### ISSUE THREAD

**Issue by its-dibo** [motdotla/dotenv#782]
When a key exists both in the runtime environment as an environment variable (e.g., via OS shell exports like `export DATABASE_USER=test`) and in a .env file, the runtime environment variable takes precedence.

this suggestion is to provide a syntax to use the same variable name overriding the system value

```
export DATABASE_USER=test
```
.env
```
# env.DATABASE_USER will be 'test'
DATABASE_USER=dev

# this syntax allows forcing override the system's var instead of creating another one
$DATABASE_USER=prod
```

so, in our app instead of doing this
```
// we use a different new env var here "NewDATABASE_USER", so it is not overridden by the system's one 
let dbUser = env.NewDATABASE_USER || env.DATABASE_USER;
```

we can do...
```

// because it prefixed with "$", it is forced to override the system's one
let dbUser = env.DATABASE_USER;
```

**Comment by motdotla** [comment]
If you want to override you can use the `override` option documented here: https://github.com/motdotla/dotenv#override

```
require('dotenv').config({ override: true })
```

Does that solve your problem for you?

**Comment by its-dibo** [comment]
nice option, but it forces one to completely override all system vars.
the other solution allows you to override individual vars
