### ISSUE TITLE
In ES6 DOTENV enviroment not getting 

### ISSUE THREAD

**Issue by paraschouhan15** [motdotla/dotenv#785]
**I have tried to get dotnev enviroment but getting **undefined**
//this is code i am using

`import express from 'express';
import dotenv from 'dotenv'

dotenv.config()

console.log(process.env.PORT)

const app = express();

//middlewares

app.get('/', (req, res) => {
    res.send(
        "<h1> Welcome to my aapp</h1>"
    );
})
//port

app.listen(8000, () => {
    console.log(`Server running on port number 8000`)
})
`

**Comment by paraschouhan15** [comment]
I have DOTENV file in which declared 
PORT = 8000

**Comment by AnirudhKaranth** [comment]
@paraschouhan15  This is the syntax for ES6
![image](https://github.com/motdotla/dotenv/assets/97871145/5f72e36e-83d1-4add-a5e9-ee4ea253a5b1)
