### ISSUE TITLE
Possible regression: `USERNAME` in .env file does not update process.env on Windows

### ISSUE THREAD

**Issue by Pomax** [motdotla/dotenv#794]
I found https://github.com/motdotla/dotenv/issues/505 which was supposedly addressed by https://github.com/motdotla/dotenv/issues/517 as of v14.1.0, but I just noticed that with v16.0.3 having an `.env` file that contains `USERNAME=something` does not set the `process.env.USERNAME` value and instead reports Windows' own environment variable. As `.env` files exist to explicitly set values regardless of whether they exist or not, and if they exist, regardless of what their original value is, this is highly surprising and a possible regression =)

**Comment by mxschmitt** [comment]
`"USERNAME" is already defined and was NOT overwritten` when enabling the debug logs for me. Downstream issue from the Playwright project: https://github.com/microsoft/playwright/issues/29030

**Comment by motdotla** [comment]
use `override` force it. 

```
require('dotenv').config({ override: true })
```

https://github.com/motdotla/dotenv#override

**Comment by Pomax** [comment]
That should be the other way around, with dotenv overriding everything _unless_ the user wants to preserve magic environment variables. The expectation is that .env files override any and all preexisting variables.

**Comment by motdotla** [comment]
I can understand the feeling. We went back and forth on that (many times) but for years now dotenv does NOT override if already set on your machine. Unless you pass the override option.

**Comment by Pomax** [comment]
In that case can I at least request a new feature where dotenv will throw an stdout warning about the fact that there will be magic and to add `override:true` is that magic is not wanted?

**Comment by motdotla** [comment]
@Pomax it does that here: https://github.com/motdotla/dotenv/blob/master/lib/main.js#L287

If you are looking for even more detailed logging, check out [`dotenvx`](https://github.com/dotenvx/dotenvx). It doesn't have the same constraint as dotenv (no dependencies) and as a result it able to much more detailed logging among many other things. I personally starting to move a lot of my .env and .env.vault usage to it.

**Comment by Pomax** [comment]
That looks like it's related to decryption? I didn't see dotenv warn me about this at all when I had a normal `USERNAME=...` in a plain `.env` file, and having it yell at me about that with an instruction on how to make it either stop warning or force the override would have prevented me from filing an issue =)

**Comment by motdotla** [comment]
how's this, better?

<img width="1021" alt="image" src="https://github.com/motdotla/dotenv/assets/3848/74a76fb5-3162-4c31-a222-9985cd2020ef">

(adjusting the /docs site to have this order as well)

**Comment by Pomax** [comment]
Ooh, that's pretty great! Though it would be good to mention the global install for all three OSses rather than only calling out brew.
