### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by MathiasBojda** [motdotla/dotenv#800]
It would behove you to update crypto in [lib/main.js ](https://github.com/motdotla/dotenv/blob/master/lib/main.js) to crypto-js, as the crypto package is long depcrecated. 

`Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/dotenv/lib/main.js:4:23:
      4 │ const crypto = require('crypto')`

Fixed it by trying to going into node_modues/lib/main.js and manually change to crypto-js. Fixed that issue.

**Comment by motdotla** [comment]
what version of node are you on? this is node's `crypto` lib - it's not a separate npm module.

https://nodejs.org/api/crypto.html
