### ISSUE TITLE
Getting error while reinstalling the dotenv (updating to `16.4.4` should fix. apologies for the bad patch release of `16.4.3` everyone)

### ISSUE THREAD

**Issue by utkarsh621x** [motdotla/dotenv#810]
Just got an error after running npm i and then npm start on my project. Strange thing is that this error started apearing after only when i deleted my package-lock.json and node modules folder then reinstalling them via npm i

`
D:\projects\Winkget proj\Partner\server\node_modules\dotenv\lib\main.js:210
  if (options?.encoding) {
              ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v20.10.0
[nodemon] app crashed - waiting for file changes before starting...
`
the file where the error os occuring is located in node modules folder & error is =>
![Screenshot (341)](https://github.com/motdotla/dotenv/assets/100912893/701ea4d2-217e-4b3e-8176-c3765a48f63f)

i have checked the same file from my old projects there is some changes that appeared after reinstalling the node modules
this is the old file ==> 
![image](https://github.com/motdotla/dotenv/assets/100912893/429b2871-f06a-4ce2-aeef-43b9ca053be4)

this is my main js file where i have import dotenv package => 
![image](https://github.com/motdotla/dotenv/assets/100912893/2cd74dfe-6efd-4bb2-aed8-a09c0e7de42e)

**Comment by utkarsh621x** [comment]
I am using node version 20

**Comment by Emmo00** [comment]
Found this issue with a similar problem...
https://github.com/Automattic/mongoose/issues/13971

Looks like the node dependency used might be a major cause.

**Comment by utkarsh621x** [comment]
I successfully resolved the error by removing the caret (^) from the dotenv version specifier in the package.json file. It appears that there were compatibility issues with the latest version being installed by the caret, so I switched to version 16.0.0, which is functioning as expected.

**Comment by ryanolson-aumni** [comment]
This was a major breaking change. Dependabot auto updated our project and this resulted in a hard crash on our client-side. We weren't expected that from a patch release.

**Comment by ryanolson-aumni** [comment]
<img width="503" alt="Screenshot 2024-02-13 at 8 24 10 AM" src="https://github.com/motdotla/dotenv/assets/107872820/9fb473d0-048b-44ea-b0fa-ee477dfdbe90">
It was failing on attempting to run existsSync on the client-side. (side note: this is in a Next.js app)

**Comment by motdotla** [comment]
this was a mistake with our patch release. so sorry, everyone. we are putting out a patch shortly.

**Comment by motdotla** [comment]
until we get the patch out you have 2 options:

1. Upgrade your node to 14 or higher
2. Hardcode your dotenv version to `v16.4.2` (the bug was introduced in yesterday's patch `16.4.3`)

**Comment by utkarsh621x** [comment]
> 1. Upgrade your node to 14 or higher

Sir i am already on node v20.10.0 but still facing the error

**Comment by motdotla** [comment]
effort happening here: https://github.com/motdotla/dotenv/pull/812

**Comment by uniqname** [comment]
Reiterating @utkarsh621x, we are on node v 20.10.0 when we got the error.

**Comment by motdotla** [comment]
released [`v16.4.4`](https://www.npmjs.com/package/dotenv?activeTab=versions)

please upgrade to `16.4.4` and report back.

@utkarsh621x let me know if that fixes it for you as well. that operator is supported for node 20 so i'm surprised you are receiving the error.

**Comment by motdotla** [comment]
> <img alt="Screenshot 2024-02-13 at 8 24 10 AM" width="503" src="https://private-user-images.githubusercontent.com/107872820/304460663-9fb473d0-048b-44ea-b0fa-ee477dfdbe90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NDY5MjUsIm5iZiI6MTcwNzg0NjYyNSwicGF0aCI6Ii8xMDc4NzI4MjAvMzA0NDYwNjYzLTlmYjQ3M2QwLTA0OGItNDRlYS1iMGZhLWVlNDc3ZGZkYmU5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNzUwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmJmYTQ4ZWNkNTY4MzRjNzc4OGQ1MWY4MmFlMmMwYmFhZjZiNDVlNzBiMjQ1YWUyMjc0ZmVmYmI3Mzk5NDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eY8ca4BawZnCYa4QhLiYAXZmxJA00s5FGBgCYVy8rcw">
> It was failing on attempting to run existsSync on the client-side. (side note: this is in a Next.js app)

what version did you upgrade from with dependabot? was it from `16.4.2` to `16.4.3` or was it from a much earlier version?

**Comment by utkarsh621x** [comment]
The issue has been **resolved** by updating to version **16.4.4**. I appreciate the prompt resolution.

**Comment by motdotla** [comment]
great!

**Comment by ryanolson-aumni** [comment]
@motdotla It was from 16.4.2 -> 16.4.3.

**Comment by ryanolson-aumni** [comment]
I updated to 16.4.4 and tested locally. I'm still seeing an issue (with the same error message "Unhandled Runtime Error
TypeError: fs.existsSync is not a function")

It's failing on fs.existsSync in this block of code:
```js
let optionPathsThatExist = []
  if (options && options.path) {
    if (!Array.isArray(options.path)) {
      if (fs.existsSync(options.path)) {
```

**Comment by motdotla** [comment]
@ryanolson-aumni are you using webpack? or is this back-end node code?

**Comment by ryanolson-aumni** [comment]
Using Next.js 14.1.0 with SWC (speedy web compiler). Then in our _app.jsx (for all pages), we've had:

```js
import dotenv from 'dotenv';

dotenv.config({ path: '.env' });

const App = () => {
// not showing implementation
}

export default App;
```

**Comment by magikcypress** [comment]
the same error message "Unhandled Runtime Error TypeError: fs.existsSync is not a function"

```
import dotenv from 'dotenv';
dotenv.config({ path: '../../.env' });
```

or

```
require('dotenv').config({ path: '../../.env' });
```

Node : 20.11.0
Webpack : 5.90.2

**Comment by motdotla** [comment]
@magikcypress looks like you are experiencing the same issue - attempting to use dotenv inside runtime front-end code. front-end does not have a filesystem available to it. you can use https://github.com/mrsteele/dotenv-webpack.

**Comment by ryanolson-aumni** [comment]
@motdotla I don't entirely disagree with you. However, we've been using it this way for over a year now without any issues until 16.4.3. The _app.jsx page runs on the server-side for server-side rendering. Then once pushed to the frontend, _can_ run things client side. Something that changed in 16.4.2->16.4.3 broke this.

**Comment by motdotla** [comment]
here's everything that changed since then: https://github.com/motdotla/dotenv/compare/v16.4.2...v16.4.4

i'll try and take a look soon and see why this would result in a front-end fs issue when prior it somehow got away with it.

**Comment by motdotla** [comment]
at a quick glance, it looks like prior there was no `fs.existsSync` to trip up on and then the `fs.readFileSync` was under a try/catch (for good reason in case the .env file does not exist).

for front-end that would result in dotenv.config() silently not working. https://github.com/motdotla/dotenv/blob/master/lib/main.js#L247

@ryanolson-aumni if you remove your historic code

```
import dotenv from 'dotenv';

dotenv.config({ path: '.env' });
```

does the app continue to function correctly? I anticipate it might because next.js is taking care of things.

**Comment by motdotla** [comment]
@ryanolson-aumni update to `16.4.5`. i think it will fix this problem for you. i removed the fs.existsSync checks

https://github.com/motdotla/dotenv/pull/814

**Comment by ryanolson-aumni** [comment]
Thanks @motdotla. We'll test out removing the import and `config` call. Thanks for maintaining dotenv. 🎉
