### ISSUE TITLE
[Feature request] Write to dotenv file

### ISSUE THREAD

**Issue by aswamy** [motdotla/dotenv#818]
Currently, the dotenv library exposes the following methods:

- config
- parse
- populate
- decrypt

I'd love to be able to write to the .env file, or patch it with existing variables.

Example:

```
const envVars = {
  API-KEY: "555",
  SECRET: 123
}

dotenv.write(envVars, file); // Writes the provided object into the .env file
```

```
const envVarsPatch = {
  API-KEY: "444",
}

dotenv.patch(envVarsPatch, file); // If the environment variables provided in the object exist in the file, update it; or else insert it
```

Some edge case considerations:
- If the value contains a new-line, enclose the variable value in double quotes
- If the string contains double quotes, use single quotes; if the string contains single & double quotes, use tilde
- `dotenv.patch` should be able to ignore comments and bad characters in the file

**Comment by motdotla** [comment]
this is outside of the scope of this library, but it will be added to [`dotenvx`](https://github.com/dotenvx/dotenvx) - which adds a lot of improved tooling and safety around .env files.

likely it will be `dotenvx set KEY=value`
