### ISSUE TITLE
Feature: Request for IntelliSense

### ISSUE THREAD

**Issue by talhameer** [motdotla/dotenv#820]
### Overview:
Currently, the npm dotenv package offers a convenient way to load environment variables from a `.env` file into Node.js applications. However, one significant usability enhancement that could greatly improve developer experience is the integration of IntelliSense support within code editors. 

### Feature Request:
The requested feature entails adding IntelliSense support to the dotenv package. Specifically, when developers access environment variables using `process.env.` within their code, IntelliSense should automatically suggest all the environment variables defined in the loaded `.env` file or any other files supported by dotenv.

**Comment by motdotla** [comment]
how would this work? i'm not familiar with intellisense.

**Comment by motdotla** [comment]
you can use https://marketplace.visualstudio.com/items?itemName=dotenv.dotenv-vscode for this

**Comment by talhameer** [comment]
Thanks @motdotla, that's what I'm looking for...
