### ISSUE TITLE
Attempting to import into ES6 yields error

### ISSUE THREAD

**Issue by GeorgeSchafer** [motdotla/dotenv#821]
### Expected behavior:

Import dotenv using the instructions in the readme.md

### Actual Behavior:

```
import 'dotenv/config'
```

Yields an error in Chrome

```
Uncaught TypeError: Failed to resolve module specifier "dotenv/config". Relative references must start with either "/", "./", or "../".
```

### notes:
Error files: I have preserved the error in a branch of [my project](https://github.com/GeorgeSchafer/gun-builder/tree/dotenv-module-specifier-error/public/js).
IDE: VSCode
Browser: Chrome Version 122.0.6261.129 (Official Build) (64-bit)
OS: Windows 10

**Comment by motdotla** [comment]
does this format work for you:

```
import { config } from "dotenv";
config();
```

**Comment by motdotla** [comment]
see this thread: https://github.com/motdotla/dotenv/issues/89#issuecomment-1962908568

**Comment by GeorgeSchafer** [comment]
Interesting, I am not using nextjs to my knowledge, unless Phaser uses that under the hood.

**Comment by GeorgeSchafer** [comment]
> does this format work for you:
> 
> ```
> import { config } from "dotenv";
> config();
> ```

Same result.

Console:

```
Uncaught TypeError: Failed to resolve module specifier "dotenv". Relative references must start with either "/", "./", or "../".
```

**Comment by GeorgeSchafer** [comment]
It doesn't look like Phaser uses NextJS under the hood. I don't have a next.config.js file to modify.

**Comment by jonjieviduya** [comment]
I still get "process not defined"
