### ISSUE TITLE
windows?

### ISSUE THREAD

**Issue by dcsan** [motdotla/dotenv#83]
I'm trying to use this to support users on windows (but don't have a windows box myself)
I got the feedback that creating a file just called `.env` doesn't work - win sees that as a file with no name, just an extension.

    > i cannot remove -EXAMPLE and name it just .env

is there a recommended way to do this? perhaps just rename the file to `dot.env` ?
and require like this:

    require('dotenv').config({path: 'dot.env'});

**Comment by maxbeatty** [comment]
yes, using a custom file name with the `path` option looks to be the best workaround

**Comment by caske33** [comment]
I believe you can create the file `.env.` (see the trailing dot) which will actually create the file `.env` (without the trailing dot)
