### ISSUE TITLE
Bug: populate() is not a function

### ISSUE THREAD

**Issue by marigarey** [motdotla/dotenv#830]
When I use the populate function, my code returns the error: "TypeError: dotenv.populate is not a function".

My code:
```javascript
const parsed = {TEST: 'test'}
dotenv.populate(process.env, parsed)
``` 

Not sure what is wrong, hopefully its on my end!

**Comment by motdotla** [comment]
it probably just hasnt been added to the types file. dotenv has never been a typescript project. you can either define your own type in your project for it or if you have time a PR contribution to add it to the project's type file would be very welcome :)

**Comment by marilg** [comment]
i've been using javascript, but I can try to look through the code and see how to fix it!

(also thank you for your dotenv work! your work makes my life so much easier!!)

**Comment by mrinal-c** [comment]
Hi, I am a programmer trying to get into open-source contribution and wanted to chime in here. It seems like populate is already defined in the lib/main.d.ts types file:

```
/**
 * Loads `source` json contents into `target` like process.env.
 *
 * See https://dotenvx.com/docs
 *
 * @param processEnv - the target JSON object. in most cases use process.env but you can also pass your own JSON object
 * @param parsed - the source JSON object
 * @param options - additional options. example: `{ debug: true, override: false }`
 * @returns {void}
 *
 */
export function populate(processEnv: DotenvPopulateInput, parsed: DotenvPopulateInput, options?: DotenvConfigOptions): void;
```
Not sure if I'm looking in the right place, maybe it's a config issue on the user's end?

**Comment by jswhisperer** [comment]
```export interface DotenvPopulateInput {
  [name: string]: string;
}
```
but the example shows to send the actual `process.env`
