### ISSUE TITLE
Using boolean expression inside the .env file

### ISSUE THREAD

**Issue by bathiatuss** [motdotla/dotenv#839]
I can't pass boolean variable on the .env file. I did quick search about this subject. The solution is you have to compare the data with a logical expression like this: " process.env.myBooleanData === 'true' ". Waiting for recommendation or solution.

**Comment by motdotla** [comment]
yes, that is the correct solution. .env files treat everything as strings.

**Comment by motdotla** [comment]
this is because all environment variables are stored as strings.
