### ISSUE TITLE
Preserve comments and formatting during `.env.example` generation

### ISSUE THREAD

**Issue by BenJackGill** [motdotla/dotenv#840]
Comments are very helpful inside a `.env.example` file to give a deeper explanation of each variable.

But the `dotenvx ext genexample` command (previously `dotenvx genexample`) strips out all comments and formatting. This makes the generated `.env.example` file much harder to understand for new users.

I suggest adding something like a `--preserve-formatting` flag to keep all comments and line spacing the same as the original `.env` file.

**Comment by motdotla** [comment]
good suggestion. issue moved here: https://github.com/dotenvx/dotenvx/issues/345
