### ISSUE TITLE
Why `main.d.ts` does not default-export `DotenvModule` types?

### ISSUE THREAD

**Issue by sor4chi** [motdotla/dotenv#846]
I believe this should be exported from `main.d.ts`.

```ts
export default {
  parse,
  config,
  configDotenv,
  populate,
  decrypt,
};
```

![Type error](https://github.com/user-attachments/assets/1c13d7a1-850b-44b3-b538-9bf9dcac6506)

**Comment by nezort11** [comment]
If anyone comes across this, then it has been fixed in the latest version (just update).

**Comment by sor4chi** [comment]
thank you so much
