### ISSUE TITLE
Unexpected output when using 'PROMPT' environment variable with dotenv

### ISSUE THREAD

**Issue by VArtzy** [motdotla/dotenv#850]
When using `dotenv` to load an environment variable named `PROMPT`, I noticed unexpected behavior. 

### Steps to Reproduce:
1. Create a `.env` file with the following content:
   ```
   PROMPT=test
   ```
2. Use the following `index.js` file:
   ```javascript
   import 'dotenv/config';
   console.log(process.env.PROMPT);
   ```
3. Run the script:
   ```
   $ node index.js
   ```

### Expected Behavior:
The output should be:
```
test
```

### Observed Behavior:
The output was:
```
$P$G
```

**Comment by motdotla** [comment]
I cannot repeat this and I would be hugely surprised if this was failing for 10 years and no one discovered it.

More than likely, you already have `PROMPT` set on your `env`. Try running:

```
env
```

on your machine to check.

If you don't see it there then if you are using a framework then it is likely doing its own loading of environment variables and I would raise the issue with them please. Thank you.

Also, you might find [dotenvx](https://github.com/dotenvx/dotenvx) makes this easier to debug in the future.

**Comment by VArtzy** [comment]
Okay thanks, I wasn’t aware that another software had set the system env variable
